"""
Core function shared amongst all 3 analysis types: PR1, FR1, and Bandit.
Code is based from code generated by Chantelle Murrell and Sebastian Alves 
6-30-2026
William B. Rubio
"""

import io
import os
import zipfile
import tempfile
from pathlib import Path
import pandas as pd
import numpy as np
import re
import textwrap

# plotting
import ipywidgets as widgets
import matplotlib.pyplot as plt
import seaborn as sns

# stats
import pingouin as pg
from statsmodels.formula.api import ols
import statsmodels.api as sm

# call cousins
from fedverse.extracted import fed3_loading
from fedverse.fedutils.fedlog import status 


#@@@@@@@@@@@@@@@@@@ GLOBAL VARIABLES @@@@@@@@@@@@@@@@@@#
# List of meta columns that we are interested in preserving and acting upon
#BANDIT_META_COLS = ["Genotype", "Gene", "Strain", "Sex", "Diet", "Treatment", "Condition","Pellets","Litter", "Sire_Geno", "Dam_Geno",]

# Set the alpha for plots
ALPHA = 0.6  # apply to both bars and dots


def set_plot_style(font_family="DejaVu Sans"):
    """
    Force one consistent font family across every text element (tick labels,
    axis labels, captions, titles) so the L4 composites all render in the same
    typeface.
    """
    plt.rcParams["font.family"] = "sans-serif"
    plt.rcParams["font.sans-serif"] = [
        font_family, "DejaVu Sans", "Liberation Sans", "sans-serif",
    ]
    plt.rcParams["pdf.fonttype"] = 42
    plt.rcParams["ps.fonttype"] = 42

### ---- create a set of functions to validate the assay argument within core calls --- ###

# Single source of truth for every per-assay column set.
# Structure: assay -> kind -> columns. Keeping meta and metric side by side
# means the valid-assay set is defined once and the two can never key-drift.
ASSAY_COLS = {
    "bandit": {
        "meta": [
            "Genotype", "Gene", "Strain", "Sex", "Diet", "Treatment",
            "Condition", "Pellets", "Litter", "Sire_Geno", "Dam_Geno",
        ],
        "metric": [
            "Win-stay", "Lose-shift", "PeakAccuracy", "Total_pellets", "Total_pokes",
            "PokesPerPellet", "RetrievalTime", "PokeTime", "Daily_Pellets",
            "Inactive_Pokes", "Active_Pokes", "Weight",
            "Win-stay_Day", "Win-stay_Night", "Lose-shift_Day", "Lose-shift_Night",
            "PeakAccuracy_Day", "PeakAccuracy_Night", "Left Poke with Pellet", "Right_Poke",
        ],
    },
    "pr1": {
        "meta": [
            "Genotype", "Gene", "Strain", "Sex", "Diet", "Treatment",
            "Condition", "Task",
        ],
        "metric": [
            "Left_Poke", "Right_Poke", "Total_Pokes", "Accuracy", "PokesPerPellet",
            "MedianBreakPoint", "Numberofblocks", "Daily_Pellets",
            "Demand_Q0_raw", "Demand_alpha_raw", "Demand_beta_raw",
            "Demand_alpha_FR", "Demand_beta_FR",
        ],
    },
    "fr1": {
        "meta": [
            "Genotype", "Gene", "Strain", "Sex", "Diet", "Treatment", 
            "Condition", "Task"
        ],
        "metric": [
            "Pellets", "Left_Poke", "Right_Poke", "Total_Pokes", "Accuracy",
            "PokesPerPellet", "RetrievalTime", "InterPelletInterval", "PokeTime",
            "%MealPellets", "%GrazingPellets", "NumMeals", "AvgMealSize",
            "AvgMealDuration", "RecordingHours", "MealsPerHour",
            "Daily_Pellets", "Left Poke with Pellet","Within_meal_pellet_rate",
            "%MealPellets_Day","%GrazingPellets_Day","Pellets_Day","NumMeals_Day","AvgMealSize_Day","AvgMealDuration_Day","MealsPerHour_Day","Accuracy_Day",
            "%MealPellets_Night","%GrazingPellets_Night","Pellets_Night","NumMeals_Night","AvgMealSize_Night","AvgMealDuration_Night","MealsPerHour_Night","Accuracy_Night",
        ]
    },
    "beam": {
        "meta": [
            "Genotype", "Gene", "Strain", "Sex", "Diet", "Treatment", 
            "Condition", "Pellets", "Mutation"
        ],
        "activity": [
            "activity_percent", "Activity_percent", "Activity %", "activity%", "activity", "Activity"
        ],
        "metric": [
            "MESOR_z", "Amplitude_z", "Acrophase_ZT_signed", "Cosinor_R2", "Night_z", "Day_z", "Mean_activity"
        ]

    },
}

def get_cols(assay, kind, status):
    """Validate `assay` and return the requested column list for it.

    `kind` is "meta", "metric", etc. Returns a *copy* so callers can trim or
    extend the list per-function without mutating the shared ASSAY_COLS.
    """
    # User-facing validation: assay came from the caller/user, so fail gracefully.
    if assay not in ASSAY_COLS:
        allowed = ", ".join(repr(a) for a in ASSAY_COLS)
        status.fail(f"Argument 'assay' needs to be one of: {allowed}.")
        # Insurance in case status.fail() is ever changed to not raise.
        raise ValueError(f"assay={assay!r} not in {allowed}")

    # Internal validation: a bad `kind` is a bug in fedverse, not user input —
    # so raise KeyError-style rather than routing it through status.fail.
    if kind not in ASSAY_COLS[assay]:
        raise KeyError(
            f"No {kind!r} columns defined for assay {assay!r}; "
            f"available kinds: {list(ASSAY_COLS[assay])}"
        )

    # Copy so per-function .append()/filtering can't poison the module-level list.
    return list(ASSAY_COLS[assay][kind])



#@@@@@@@@@@@@@@@@@@ SHARED LOGIC @@@@@@@@@@@@@@@@@@#
# these are functions that are repeated throughout the different assays 
# that are not tied to a specific section or most closely tied to ingest

# --- General workflow functions --- # 
def _get_timestamp_series(df, ts_col="MM:DD:YYYY hh:mm:ss"):
    if ts_col in df.columns:
        ts = pd.to_datetime(df[ts_col], format="%m:%d:%Y %H:%M:%S", errors="coerce")
        return pd.Series(ts, index=df.index)
    for cand in ["DateTime", "Datetime", "Timestamp", "timestamp", "datetime"]:
        if cand in df.columns:
            ts = pd.to_datetime(df[cand], errors="coerce")
            return pd.Series(ts, index=df.index)
    idx = df.index
    if isinstance(idx, pd.DatetimeIndex):
        return pd.Series(idx, index=df.index)
    return pd.to_datetime(pd.Series(idx, index=df.index), errors="coerce")


def _estimate_daily_pellets(df):
    ts = _get_timestamp_series(df)
    valid_ts = ts.dropna()
    if valid_ts.size < 2:
        return np.nan
    duration_hours = (valid_ts.max() - valid_ts.min()).total_seconds() / 3600.0
    if duration_hours <= 0:
        return np.nan

    pellet_events = np.nan
    if "Pellet_Count" in df.columns and df["Pellet_Count"].notna().any():
        pc = pd.to_numeric(df["Pellet_Count"], errors="coerce")
        if pc.notna().any():
            diffs = pc.diff().fillna(0).clip(lower=0)
            pellet_events = float(diffs.sum())
            if pellet_events == 0 and pc.iloc[-1] >= pc.iloc[0]:
                pellet_events = float(pc.iloc[-1] - pc.iloc[0])

    if (pd.isna(pellet_events)) and ("Event" in df.columns):
        pellet_events = float((df["Event"].astype(str) == "Pellet").sum())

    if pd.isna(pellet_events):
        return np.nan
    return (pellet_events / duration_hours) * 24.0


def pick_match_method(md, match_mode=None):
    """
    Picks what the id key column is from the metadata df
    Argument:
        md; Dataframe
            meta dataframe that contatins cropped bandit key created by build_bandit_metakey
        match_mode; str, default None
            accepts string argument specifying what column will be used as the id column. should be either mouse_id or filename
    Returns:
        id_col; string
            String detailing what column will serve as the key column to link both metadata and metric files
        other_id; string
            String detailing fallback key column to link metadata and metrics dataframes
    """
    
    if match_mode == 'filename':
        id_col = 'filename'
    elif match_mode == 'mouse_id':
        id_col = 'Mouse_ID'
    else:
        id_col = 'Mouse_ID' if 'Mouse_ID' in md.columns else 'filename'

    other_id = "Mouse_ID" if id_col == "filename" else "filename"

    return id_col, other_id


def with_session_suffix_for_csv(df, metrics, session_col="_Session_type_for_csv"):
    df = df.copy()
    for m in metrics:
        if m not in df.columns:
            continue
        for sess in df[session_col].dropna().unique():
            mask = df[session_col] == sess
            col_name = f"{m}_{sess}"
            if col_name not in df.columns:
                df[col_name] = np.nan
            df.loc[mask, col_name] = df.loc[mask, m]
        df.drop(columns=[m], inplace=True)
    return df.drop(columns=[session_col])


def _safe_col(df, candidates):
    """
    Called by:
        _prep_events
        _pellet_times_from_df : fr1
    """
    norm = lambda s: str(s).strip().lower().replace('-', '_').replace(' ', '_')
    lmap = {norm(c): c for c in df.columns}
    for cand in candidates:
        key = norm(cand)
        if key in lmap:
            return lmap[key]
    return None

def _prep_events(df):
    ev_col = _safe_col(df, ["Event", "event"])
    if ev_col is None:
        return df.iloc[0:0].copy(), None
    return df[df[ev_col].isin(["Left", "Right", "Pellet"])].copy(), ev_col


### ------ Attach metadata to metrics ------ ###
def attach_meta(metric_df, md, id_col):
    """
    Attaches cropped bandit metadata dataframe to the aggragated bandit metric dataframe

    Arguments:
        metric_df; Dataframe
            Dataframe containing aggragated metrics for multiple mice in a multiple assay types by a FED device
        md; Dataframe
            meta dataframe that contatins cropped bandit key created by build_bandit_metakey
        id_col; String, default "Mouse_ID"
            String detailing what column will serve as the key column   
    Returns:
        bm_md; Dataframe    
            Dataframe containing aggregated metrics with metadata
    """

    status.step("Attaching metadata to metrics")
    df = metric_df.copy()

    # catch instances where the filename column may be "File" instead of "filename"
    if "File" in df.columns:
        df["filename"] = df["File"].astype(str).map(_basename)


    if "filename" in md.columns and "Mouse_ID" in md.columns:
        mouse_map = md.dropna(subset=["filename"]).drop_duplicates("filename").set_index("filename")["Mouse_ID"]
        df["Mouse_ID"] = df["filename"].map(mouse_map)

        # attempt to fill missing mouse ID's
        if df["Mouse_ID"].isna().any():
            # find known ids
            known_ids = md["Mouse_ID"].dropna().unique().tolist()
            # iterate over empty id's
            for i, r in df.loc[df["Mouse_ID"].isna()].iterrows():
                base = _file_base_lower(r["filename"])
                hits = [mid for mid in known_ids if str(mid).lower() in base]
                if len(hits) == 1:
                    df.at[i, "Mouse_ID"] = hits[0]
                elif len(hits) > 1:
                    longest = max(len(str(h)) for h in hits)
                    best = [h for h in hits if len(str(h)) == longest]
                    if len(best) == 1:
                        df.at[i, "Mouse_ID"] = best[0]

    # check if the id_col is mouse_id and if both dataframes have a mouse_id column and if the mouse_id column in the metric dataframe has any non-null values
    if (id_col == "Mouse_ID") and ("Mouse_ID" in df.columns) and ("Mouse_ID" in md.columns) and df["Mouse_ID"].notna().any():
        md_unique = md.drop_duplicates(subset=["Mouse_ID"], keep="first")
        df_md = df.merge(md_unique, on="Mouse_ID", how="left", suffixes=("", "_md"))
    else:
        if "filename" not in md.columns:
            raise ValueError("metadata_df has no 'filename' column, but filename is needed for this mode.")
        md_unique = md.drop_duplicates(subset=["filename"], keep="first")
        df_md = df.merge(md_unique, on="filename", how="left", suffixes=("", "_md"))

    status.ok("metadata attached")
    status.preview(df_md, msg="merged metric dataframe")

    return df_md


#@@@@@@@@@@@@@@@@@@ UPLOADING FILES @@@@@@@@@@@@@@@@@@#

# functions need for reading in cleaned FED files
def extract_session_type(csv_path, fallback="Unknown"):
    """
    Read 'Session_Type ' or variants; return first non-empty value.
    Called by: 
        ingest_l1
    Argument:
        csv_path - has to be a pathway to a csv within a zipped file
    """
    try:
        # Read in the individual file
        df = pd.read_csv(csv_path, sep=None, engine='python', dtype=str)
        # isolate columns names 
        df.columns = [c.strip() for c in df.columns]
        lower = {c.casefold(): c for c in df.columns}
        # Loop through column names to locate the session column
        for cand in ["session_type", "session type", "sessiontype", "session"]:
            if cand in lower:
                col = lower[cand]
                vals = df[col].dropna().astype(str).str.strip()
                vals = vals[vals.ne("")]
                if not vals.empty:
                    # Return the first value of the session-like column
                    return vals.iloc[0]
    except Exception:
        pass
    return fallback


def ingest_l1(l1_path):
    """
    Define a function that will ingest data derived from a zipped folder contating fed data
    Argument: 
        l1_path - is required to be a path to a zipped folder that contains processed data from a fed. 
    """
    status.step("Beginning Ingest") 
    # check if the path is a zip file else pass error
    if not zipfile.is_zipfile(l1_path):
        raise ValueError(f"RAW_PATH must be a zip archive: {l1_path}")

    # define lists to populate
    fed_list, loaded_files, session_types = [], [], []

    # Create a empty list to catch error messages
    errors = []
    
    # pathify the name and create dictionary
    l1_path = Path(l1_path)
    uploaded = {l1_path.name: l1_path.read_bytes()}

    # iteracte through the dictionary
    for name, data in uploaded.items():
        ### for ZIP files
        if name.lower().endswith(".zip"):
            with zipfile.ZipFile(io.BytesIO(data)) as zf:
                for zi in zf.infolist():
                    if not zi.filename.lower().endswith(".csv"):
                        continue
                    file_data = zf.read(zi)
                    # if the file is short remove the file
                    if len(file_data) <= 1024:
                        continue
                    with tempfile.NamedTemporaryFile(mode="w+b", suffix=".csv", delete=False) as tmp:
                        tmp.write(file_data); tmp_path = tmp.name
                    # attempt to populate lists
                    try:
                        session_type = extract_session_type(tmp_path)
                        # try to open on basic datetime else try beam index
                        try:
                            df = fed3_loading.load(tmp_path)
                        except Exception as e:
                            df = fed3_loading.load(tmp_path, index_col="datetime")

                        df.name = os.path.basename(zi.filename)
                        df.attrs = {"Session_type": session_type}
                        fed_list.append(df)
                        loaded_files.append(os.path.basename(zi.filename))
                        session_types.append(session_type)
                    except Exception as e:
                        errors.append(f"Error loading {zi.filename}: {e}")
                    finally:
                        os.remove(tmp_path)
        ### if a csv file happens to be uploaded
        elif name.lower().endswith(".csv"):
            if len(data) <= 1024:
                continue
            with tempfile.NamedTemporaryFile(mode="w+b", suffix=".csv", delete=False) as tmp:
                tmp.write(data); tmp_path = tmp.name
            try:
                session_type = extract_session_type(tmp_path)

                # try to open on basic datetime else try beam index
                try:
                    df = fed3_loading.load(tmp_path)
                except Exception:
                    df = fed3_loading.load(tmp_path, index_col="datetime")

                df.name = os.path.basename(name)
                df.attrs = {"Session_type": session_type}
                fed_list.append(df)
                loaded_files.append(os.path.basename(name))
                session_types.append(session_type)
            except Exception as e:
                errors.append(f"Error loading {name}: {e}")
            finally:
                os.remove(tmp_path)

    # if any errors occoured return the errors
    if errors:
        print()
        for err in errors:
            status.warn(err)
    
    status.ok(f"Ingest Complete - Loaded {len(loaded_files)} files. Session types captured for all.")

    # ensure that a datetime column exists
    for df in fed_list:
        has_col = 'MM:DD:YYYY hh:mm:ss' in df.columns or 'datetime' in df.columns
        if not has_col and df.index.name in ('MM:DD:YYYY hh:mm:ss', 'datetime'):
            df[df.index.name] = df.index
            df.index.name = None

        has_ts = 'MM:DD:YYYY hh:mm:ss' in df.columns or 'datetime' in df.columns
        print(f"{df.name}: timestamp column present = {has_ts}")

    # return three lists
    return fed_list, loaded_files, session_types

#@@@@@@@@@@@@@@@@@@ KEY CREATION @@@@@@@@@@@@@@@@@@#

# functions needed for creating key columns
def _make_base_key_df(loaded_files, session_types):
    """
    Use two lists from ingest to make a basic df to house meta data
    Called by:
        build_or_rematch_key_df
    Arguments:
        loaded_files - list output from ingest_l1
        session_types - list output from ingest_l1
    """
    return pd.DataFrame({"filename": loaded_files, "Session_type": session_types})

def _file_base(s):
    """
    Called by: 
        build_or_rematch_key_df
    """
    return os.path.splitext(os.path.basename(str(s)))[0].strip()

def _norm_base_lower(s):
    """
    generic function to lowercase strings passed into it
    Called by:
        build_or_rematch_key_df
    """
    return _file_base(s).lower()


def _scan_key_columns(df):
    """
    Accepts keys that have either Mouse_ID or a filename column (filename/File).
    Called by:
        _read_key_from_upload
        build_or_rematch_key_df
    Returns dict:
      {
        'has_mouse': bool,
        'has_filename': bool,
        'filename_col': 'filename'|'File'|None,
        'msg': str
      }
    """
    info = {'has_mouse': False, 'has_filename': False, 'filename_col': None, 'msg': ''}
    try:
        cols = [str(c).strip() for c in df.columns]
        has_mouse = 'Mouse_ID' in cols
        fname_col = 'filename' if 'filename' in cols else ('File' if 'File' in cols else None)
        info.update({
            'has_mouse': has_mouse,
            'has_filename': fname_col is not None,
            'filename_col': fname_col
        })
        if has_mouse:
            info['msg'] = "'Mouse_ID' found."
        elif fname_col:
            info['msg'] = f"'{fname_col}' found; will match on filename."
        else:
            info['msg'] = "Neither 'Mouse_ID' nor 'filename'/'File' found in provided key."
    except Exception as e:
        info['msg'] = f"Error while checking key: {e}"
    return info

def _match_mouse_id_to_filenames(filenames, key_df):
    """
    Called by:
        build_or_rematch_key_df
    Returns:
        DataFrame: filename, Mouse_ID, match_status based on Mouse_ID substring in filename.
    """
    base_names_lower = [_norm_base_lower(f) for f in filenames]
    mouse_ids = (
        key_df['Mouse_ID']
        .dropna().astype(str).map(str.strip)
        .replace({'': np.nan}).dropna().unique().tolist()
    )
    rows = []
    for fname, base in zip(filenames, base_names_lower):
        hits = [mid for mid in mouse_ids if str(mid).lower() in base]
        if len(hits) == 1:
            rows.append({"filename": fname, "Mouse_ID": hits[0], "match_status": "Matched (Mouse_ID in filename)"})
        elif len(hits) > 1:
            longest = max(len(str(h)) for h in hits)
            best = [h for h in hits if len(str(h)) == longest]
            if len(best) == 1:
                rows.append({"filename": fname, "Mouse_ID": best[0], "match_status": "Matched (longest Mouse_ID token)"})
            else:
                rows.append({"filename": fname, "Mouse_ID": None, "match_status": f"Ambiguous Mouse_ID: {hits}"})
        else:
            rows.append({"filename": fname, "Mouse_ID": None, "match_status": "Mouse_ID not found in filename"})
    return pd.DataFrame(rows)

def _collapse_key_suffixes(df, keep_filename_from_base=True):
    """
    Remove duplicate columns created by merge suffixes.
    - If both 'col' and 'col_key' exist, keep the key version (rename col_key -> col, drop base col).
    - Special-case: if keep_filename_from_base and base == 'filename',
      drop 'filename_key' and keep the base 'filename'.

    Called by:
        build_or_rematch_key_df
    """
    cols = list(df.columns)
    rename_map = {}
    drop_cols = []

    for col in cols:
        if col.endswith('_key'):
            base = col[:-4]
            if keep_filename_from_base and base == 'filename':
                # keep the 'filename' from the bare-bones (actual loaded_files)
                drop_cols.append(col)
            elif base in df.columns:
                # key version wins: drop base col, rename *_key -> base
                drop_cols.append(base)
                rename_map[col] = base
            else:
                # no base column; just strip "_key"
                rename_map[col] = base

    df = df.drop(columns=drop_cols, errors='ignore').rename(columns=rename_map)
    return df
    
def _read_key_from_upload(key_path, hom_hemi_merge=True):
    """
    Reads CSV/XLSX bytes from Colab upload.

    Arguments:
        key_path: String
            Path to the uploaded key file.
        hom_hemi_merge: Boolean
            Whether to merge Hom and Hemi genotypes.

    Returns: 
        a Dataframe or None, returns a message.
    """
    status.step("Reading in key file")
    # Read in the from the path provided
    name = key_path.name
    content_bytes = key_path.read_bytes()
    
    ext = name.lower().rsplit('.', 1)[-1] if '.' in name else ''
    try:
        bio = io.BytesIO(content_bytes)
        if ext == 'xlsx':
            xls = pd.ExcelFile(bio, engine='openpyxl')
            frames = [pd.read_excel(xls, sheet_name=s) for s in xls.sheet_names]
            key_df = pd.concat(frames, ignore_index=True, sort=False)
        elif ext == 'csv':
            key_df = pd.read_csv(bio, sep=None, engine='python')
        else:
            return None, f"Unsupported key type .{ext}"

        key_df = key_df.copy()
        key_df.columns = [str(c).strip() for c in key_df.columns]
        scan = _scan_key_columns(key_df)
        if not (scan['has_mouse'] or scan['has_filename']):
            return None, scan['msg']

        # Normalize types/columns we might use later
        if scan['has_mouse']:
            globals()['KEY_MATCH_MODE'] = 'mouse_id'
            key_df['Mouse_ID'] = key_df['Mouse_ID'].astype(str).str.strip()

        if scan['has_filename']:
            globals()['KEY_MATCH_MODE'] = 'filename'
            fcol = scan['filename_col']
            key_df[fcol] = key_df[fcol].astype(str).str.strip()
            key_df['_key_file_base_lower'] = key_df[fcol].map(_norm_base_lower)
        else:
            globals()['KEY_MATCH_MODE'] = None

        # REMOVED - Persist a deterministic copy on disk for reproducibility
        #fixed_path = f"_uploaded_key.{ext}"
        #with open(fixed_path, "wb") as f:
        #    f.write(content_bytes)
        #globals()['uploaded_key_path'] = fixed_path

        status.ok("Done - Key loaded")

        # we catch if there is a hemi and adjust the key_df accordingly 
        if hom_hemi_merge:
            if 'hemi' in key_df["Genotype$"].str.lower().unique():
                status.sub("Can merge Hom and Hemi genotypes into a single category")
                key_df['Genotype$'] = key_df['Genotype$'].str.replace('Hom|Hemi', 'Hom/Hemi', regex=True)
            else:
                status.sub("No Hemi genotypes found in key; no merge needed")

        return key_df, f"Key loaded from upload ({name}). {scan['msg']}"
    except Exception as e:
        return None, f"Error reading uploaded key: {e}"


def build_or_rematch_key_df(loaded_files, session_types, key_df = None, msg_hint = ""):
    """
    If key_df provided and valid:
      - If a filename column exists (filename/File), always use filename-based merge.
        - If Mouse_ID is also present, it is preserved from the key file.
      - Else, if only Mouse_ID exists, use substring-based Mouse_ID matching.
    Else: keep bare-bones.

    When a key is used, any duplicate column names between the bare-bones
    and the key are resolved so that the key's values win (except 'filename').
    """
    #global Key_Df
    status.step("Building key dataframe") 
    files_df = _make_base_key_df(loaded_files, session_types)#.copy()
    files_df['_file_base_lower'] = files_df['filename'].map(_norm_base_lower)

    # In pipeline should never happen as Red key from download is always called before to make a key
    if key_df is None:
        # Pure bare-bones Key_Df
        Key_Df = files_df.drop(columns=['_file_base_lower']).copy()
        Key_Df["match_status"] = "No key"
        # REMOVED - widget based interactable
        #with status_box:
        #clear_output(wait=True)
        status.sub("Key status: No key provided; showing bare-bones Key_Df.")
        return Key_Df

    # Identify key capabilities
    scan = _scan_key_columns(key_df)
    kd = key_df.copy()

    # Helper: make a unique version of the key for whichever join we use
    def _dedup(df, subset_cols):
        dup_counts = df[subset_cols].astype(str).agg('|'.join, axis=1).value_counts()
        n_dups = int((dup_counts > 1).sum())
        if n_dups:
            # REMOVED - widget based interactable
            #with status_box:
            #clear_output(wait=True)
            status.sub(f"Note: {n_dups} duplicate key(s) on {subset_cols}; taking the first occurrence.")
        return df.drop_duplicates(subset=subset_cols, keep="first")

    # ---------------------------
    # 1) Prefer filename-based route whenever filename column exists
    #    (whether or not Mouse_ID is present)
    # ---------------------------
    if scan['has_filename']:
        fcol = scan['filename_col']

        # Normalize filename column in key
        kd[fcol] = kd[fcol].astype(str).str.strip()
        kd['_key_file_base_lower'] = kd[fcol].map(_norm_base_lower)

        # One row per normalized filename in the key
        key_unique = _dedup(kd, ['_key_file_base_lower'])

        # Merge by normalized basename (case-insensitive, extension-stripped)
        Key_Df = (
            files_df
            .merge(
                key_unique,
                left_on="_file_base_lower",
                right_on="_key_file_base_lower",
                how="left",
                suffixes=("", "_key")
            )
            .drop(columns=['_file_base_lower', '_key_file_base_lower'])
        )

        # Clean up duplicate columns so key overwrites bare-bones where appropriate
        Key_Df = _collapse_key_suffixes(Key_Df, keep_filename_from_base=True)

        # match_status for filename-based matching
        Key_Df["match_status"] = np.where(
            Key_Df[fcol].notna(),
            "Matched (filename)",
            "Filename not found in key"
        )

    # ---------------------------
    # 2) If no filename column but Mouse_ID exists, use substring route
    # ---------------------------
    elif scan['has_mouse']:
        # Mouse_ID route (fallback when no filename column exists)
        kd['Mouse_ID'] = kd['Mouse_ID'].astype(str).str.strip()
        key_unique = _dedup(kd, ['Mouse_ID'])

        matched = _match_mouse_id_to_filenames(
            files_df['filename'].tolist(),
            key_unique
        )[["filename", "Mouse_ID", "match_status"]]

        Key_Df = (
            files_df
            .merge(matched, on="filename", how="left")
            .merge(key_unique, on="Mouse_ID", how="left", suffixes=("", "_key"))
            .drop(columns=['_file_base_lower'])
        )

        # Clean up duplicate columns (e.g., Mouse_ID vs Mouse_ID_key)
        Key_Df = _collapse_key_suffixes(Key_Df, keep_filename_from_base=True)

    # ---------------------------
    # 3) Neither filename nor Mouse_ID in key
    # ---------------------------
    else:
        # Neither route available (shouldn't happen due to earlier check)
        Key_Df = files_df.drop(columns=['_file_base_lower']).copy()
        Key_Df["match_status"] = "Key missing Mouse_ID and filename columns"
    
    # REMOVED - widget based interactable
    #with status_box:
    #clear_output(wait=True)
    
    if msg_hint:
        status.ok(msg_hint)
    status.ok(f"Merged key columns into Key_Df ({len(Key_Df)} rows, {len(Key_Df.columns)} cols).")
    return Key_Df


#@@@@@@@@@@@@@@@@@@ CLEAN KEY @@@@@@@@@@@@@@@@@@#


def _basename(pathlike) -> str:
    """
    Is called by build_metakey as well as other functions throughout 
    Argument:
        pathlike; string
            string of path
    Returns:
        basename from a path
    """
    s = str(pathlike).replace("\\", "/")
    return s.split("/")[-1]

def _clean_colname(c):
    """
    Cleans column name, called typiclly within a loop to clean all columnnames 
    Called by:
        build_metakey
    Argument:
        c; string
            string of column name
    """
    c = str(c).strip()
    c = c.replace("$", "")
    c = re.sub(r"\s+", "_", c)
    c = re.sub(r"_+", "_", c)
    return c




### ------ Build clean metakey ------ ### 
def build_metakey(key_df, assay = None):
    """
    Crops the metadatakey for the Bandit FR and PR1 analysis workflow.
    Argument:
        key_df; Dataframe
            A dataframe contating meta information of the mice assayed via a FED (bandit) device.
    Returns:
        md; Dataframe
            Cropped version of ingested dataframe
    """

    # check the assigned assay type and supply the appropriate columns for needed metadata
    #if assay == "bandit":
    #    meta_cols = ["Genotype", "Gene", "Strain", "Sex", "Diet", "Treatment", "Condition","Pellets","Litter", "Sire_Geno", "Dam_Geno",]
    #elif assay == "pr1":
    #    meta_cols = ["Genotype", "Gene", "Strain", "Sex", "Diet", "Treatment", "Condition", "Task"]
    #else:
    #    status.fail("Argument 'assay' needs to be supplied with one of the following: 'bandit', 'pr1', or 'fr1'.")
    
    meta_cols = get_cols(assay, "meta", status)

    # copy key
    metadata_df = key_df.copy().reset_index(drop=True)
    # Clean every column name
    metadata_df.columns = [_clean_colname(c) for c in metadata_df.columns]
    
    if "filename" in metadata_df.columns:
        metadata_df["filename"] = metadata_df["filename"].astype(str).map(os.path.basename).map(_basename)
    if "Mouse_ID" in metadata_df.columns:
        metadata_df["Mouse_ID"] = metadata_df["Mouse_ID"].astype(str).str.strip()
    
    
    
    lower_map = {c.lower(): c for c in metadata_df.columns}
    rename_map = {}
    for w in meta_cols:
        c = lower_map.get(w.lower(), None)
        if c is not None and c != w:
            rename_map[c] = w
    metadata_df = metadata_df.rename(columns=rename_map)
    
    merge_cols = [c for c in ["filename", "Mouse_ID"] if c in metadata_df.columns]
    naming_cols = [c for c in ["Session_type", "Gene_ID", "Strain_ID"] if c in metadata_df.columns]
    keep_cols = list(dict.fromkeys(merge_cols + [c for c in meta_cols if c in metadata_df.columns] + naming_cols))
    metadata_df = metadata_df.loc[:, keep_cols].copy()
    
    md = metadata_df.copy()
    if "filename" in md.columns:
        md["filename"] = md["filename"].astype(str).map(_basename)
    if "Mouse_ID" in md.columns:
        md["Mouse_ID"] = md["Mouse_ID"].astype(str).str.strip()

    return meta_cols, md


#@@@@@@@@@@@@@@@@@@ OUTPUT L3 @@@@@@@@@@@@@@@@@@#

def output_l3(df_md, id_col, other_id, meta_cols, root_path, assay = None, resolve_hom_hemi = True):
    """
    Arguemnts:
        df_md; Dataframe
            Dataframe containing aggregated metrics with metadata
        id_col; string
            String detailing what column will serve as the key column to link both metadata and metric files
        other_id; string
            String detailing fallback key column to link metadata and metrics dataframes
        meta_cols; List
            list of columns we are interested in outputing to the L3
        assay; str
            a strong defining what assays L3 should be output
        resolve_hom_hemi; bool, default True
            If True, the L3 file written to disk resolves ambiguous "Hom/Hemi" Genotype
            labels to "Hom" or "Hemi" using Sex (Female -> Hom, Male -> Hemi). If False
            (i.e., resolve_hom_hemi=False), "Hom/Hemi" is written out as-is. The returned dataframe always
            keeps "Hom/Hemi" unresolved regardless of this setting.
    """

    status.step("Preparing L3")

    # prepare the L3 Directory for population
    status.sub("Creating L3 directory")

    out_dir = Path(root_path,)
    out_dir.mkdir(parents=True, exist_ok=True)

    status.ok("L3 directory created")

    df = df_md.copy()

    # get metric columns based on assay type
    metric_cols = get_cols(assay, "metric", status)

    # check for agreement between columns in metric file and columns specified
    metric_cols = [c for c in metric_cols if c in df.columns]


    if "Session_type" in df.columns:
        session_series = df["Session_type"].astype(str).str.strip()
    else:
        status.warn("'Session_type' column not found in metric file")
        sess_map = {
            core._basename(getattr(_sessions[i], "name", f"File_{i}")):
            (_sessions[i].attrs.get("Session_type") or "Unknown")
            for i in range(len(_sessions))
        }
        session_series = df["filename"].map(sess_map).fillna("Unknown").astype(str)

    session_series = session_series.str.replace(r"\s+", "_", regex=True)
    df["_Session_type_for_csv"] = session_series

   

    df_merged = df.copy()
    metric_csv = with_session_suffix_for_csv(df_merged, metric_cols)



    ### Prepare final export columns
    def _metric_match(col: str) -> bool:
        return any(col.startswith(base + "_") for base in metric_cols)

    metric_keep = [c for c in metric_csv.columns if _metric_match(c)]
    if not metric_keep:
        raise RuntimeError("No session-suffixed metric columns matched; check 'metric_cols'.")

    meta_keep = [c for c in meta_cols if c in metric_csv.columns]

    drop_cols = []
    if other_id in metric_csv.columns:
        drop_cols.append(other_id)
    for c in ["File", "FileIndex"]:
        if c in metric_csv.columns:
            drop_cols.append(c)

    metric_csv = metric_csv.drop(columns=drop_cols, errors="ignore")

    cols_out = [id_col] + meta_keep + metric_keep
    cols_out = [c for c in cols_out if c in metric_csv.columns]
    metric_csv = metric_csv.loc[:, cols_out].copy()

    # Resolve ambiguous Hom/Hemi genotype labels using Sex (Female -> Hom, Male -> Hemi)
    # Applied only to the CSV export; the returned dataframe keeps "Hom/Hemi" as-is.
    if resolve_hom_hemi and "Genotype" in metric_csv.columns and "Sex" in metric_csv.columns:
        ambiguous = metric_csv["Genotype"].astype(str).str.lower() == "hom/hemi"
        if ambiguous.any():
            is_female = metric_csv.loc[ambiguous, "Sex"].astype(str).str.lower().str.startswith("f")
            metric_csv.loc[ambiguous, "Genotype"] = is_female.map({True: "Hom", False: "Hemi"})

    ### get name of file ###
    example = df_merged.iloc[0]

    strain_name = str(example.get("Gene", example.get("Strain", "NA"))).replace(" ", "_")
    strain_num_raw = example.get("Gene_ID", example.get("Strain_ID", "NA"))
    try:
        strain_num = f"{int(strain_num_raw):03d}"
    except Exception:
        strain_num = str(strain_num_raw).zfill(3)

    task_name = str(example.get("Session_type", "Unknown")).replace(" ", "_")
    fname = f"{strain_name}_{strain_num}_{task_name}_L3.csv"

    # Return 
    status.ok("L3 prepared")
    status.preview(df_md, msg="L3 Dataframe")

    out_path = out_dir / fname
    metric_csv_out.to_csv(out_path, index=False)

    return(metric_csv)







#@@@@@@@@@@@@@@@@@@ GROUPING CODE @@@@@@@@@@@@@@@@@@#
# helps to determine grouping for downstream plotting


### ------ General Helper functions ------ ###

def _norm_val(x):
    """
    Called by:
        _build_group_row
    """
    s = str(x).strip()
    if s == "" or s.lower() in {"nan", "none"}:
        return "UNK"
    return s.upper()

def _build_group_row(row, ordered_cols):
    """
    Called by:
        build_mapping
    """
    if not ordered_cols:
        return "ALL"
    return " | ".join(_norm_val(row[c]) for c in ordered_cols)

def _build_file_column(df):
    """
    Called by:
        build_mapping
    """
    if "filename" in df.columns:
        return df["filename"].apply(lambda p: os.path.basename(str(p)))
    if "FED3_from_file" in df.columns and "Date_from_file" in df.columns:
        return "FED" + df["FED3_from_file"].astype(str) + "_" + df["Date_from_file"].astype(str)
    if "FED3_from_file" in df.columns:
        return "FED" + df["FED3_from_file"].astype(str)
    return df.index.astype(str)

def build_mapping(md, ordered_cols):
    """
    Arguments:
        md; Dataframe
            meta dataframe that contatins cropped bandit key created by build_bandit_metakey
    Called in:
        build_group_selections
    """
    _meta = md.copy()
    #_meta = metadata_df.copy()
    
    _meta["filename"] = _build_file_column(_meta)
    _meta["Group"] = _meta.apply(lambda r: _build_group_row(r, ordered_cols), axis=1)
    mapping = (
        _meta[["filename", "Group"]]
        .dropna(subset=["filename"])
        .drop_duplicates()
        .sort_values(["Group", "filename"])
        .reset_index(drop=True)
    )
    return mapping



### ------ Set Groups For Plotting Purposes ------ ###
def build_group_selections(md, right_x = ["Genotype"], right_hue = ["Sex"]):
    """
    Arguments:
        md; Dataframe
            meta dataframe that contatins cropped bandit key created by build_bandit_metakey
        right_x; List
            List of metadata columns selected to define main plotting purposes
        right_hue; List
            List of metadata columns selected to define supplementary plotting purposes

    Returns:
        mapping_both; Dataframe
            Dataframe mapping filenames what category the file is based on mapping groupings.
    """

    status.step("Building group selection dataframe")
    
    ordered_cols_x = list(right_x)
    ordered_cols_hue = list(right_hue)
    #ordered_cols_x = list(right_x.options)
    #ordered_cols_hue = list(right_hue.options)

    mapping_x = build_mapping(md, ordered_cols_x)
    mapping_hue = build_mapping(md, ordered_cols_hue)

    _meta = md.copy()
    #_meta = metadata_df.copy()
    
    _meta["filename"] = _build_file_column(_meta)
    _meta["XGroup"] = _meta.apply(lambda r: _build_group_row(r, ordered_cols_x), axis=1)
    _meta["HueGroup"] = _meta.apply(lambda r: _build_group_row(r, ordered_cols_hue), axis=1)
    mapping_both = (
        _meta[["filename", "XGroup", "HueGroup"]]
        .dropna(subset=["filename"])
        .drop_duplicates()
        .sort_values(["XGroup", "HueGroup", "filename"])
        .reset_index(drop=True)
    )

    globals()['files_to_group_x'] = mapping_x.copy()
    globals()['files_to_group_hue'] = mapping_hue.copy()
    globals()['files_to_group_both'] = mapping_both.copy()
    globals()['selected_group_cols_x'] = ordered_cols_x.copy()
    globals()['selected_group_cols_hue'] = ordered_cols_hue.copy()

    status.ok(f"X-axis grouping (hierarchy): {ordered_cols_x if ordered_cols_x else ["ALL"]}")
    status.ok(f"Total unique files (X map): {mapping_x['filename'].nunique()}")
    #display(widgets.HTML("<b>X-group summary</b>"))
    status.table((mapping_x.groupby("Group", dropna=False)["filename"]
             .nunique().sort_values(ascending=False)
             .rename("UniqueFiles").to_frame()))

    status.ok(f"Hue grouping: {ordered_cols_hue if ordered_cols_hue else ["ALL"]}")
    status.ok(f"Total unique files (Hue map): {mapping_hue['filename'].nunique()}")
    #display(widgets.HTML("<b>Hue-group summary</b>"))
    status.table((mapping_hue.groupby("Group", dropna=False)["filename"]
             .nunique().sort_values(ascending=False)
             .rename("UniqueFiles").to_frame()))
    #print("\nCombined mapping available as `files_to_group_both` (filename, XGroup, HueGroup)")

    status.ok("Grouping dataframe built")

    return mapping_both


### ------ Merge metrics and metadata ------ ###
def _src_name(df):
    if "filename" in df.columns:
        return "filename"
    return None

def _basename_col(s):
    return os.path.basename(str(s))

def merge_group_selections(bm, mapping_both):
    """
    Attempts to merge in grouping selections to the bandit metrics for plotting purposes later

    Arguments:
        bm; Dataframe
            Dataframe merged with metadata; not L3 dataframe
    """

    status.step("Merging group df and metric df")

    if ("XGroup" not in bm.columns) or ("HueGroup" not in bm.columns):
        if 'files_to_group_both' in globals() and files_to_group_both is not None and not files_to_group_both.empty:
            m = files_to_group_both.copy()
            m_src = _src_name(m)
            if m_src is None:
                raise RuntimeError("Grouping table must include 'filename' (or legacy 'File').")
            m["file_base"]  = m[m_src].apply(_basename_col)
            bm["file_base"] = bm["filename"].apply(_basename_col)
            bm = bm.merge(m[["file_base","XGroup","HueGroup"]], on="file_base", how="left").drop(columns=["file_base"])
            bm["XGroup"]   = bm["XGroup"].fillna("UNASSIGNED")
            bm["HueGroup"] = bm["HueGroup"].fillna("UNASSIGNED")
        elif 'files_to_group' in globals() and files_to_group is not None and not files_to_group.empty:
            m = files_to_group.copy()
            m_src = _src_name(m)
            if m_src is None:
                raise RuntimeError("Grouping table must include 'filename' (or legacy 'File').")
            m["file_base"]  = m[m_src].apply(_basename_col)
            bm["file_base"] = bm["filename"].apply(_basename_col)
            bm = bm.merge(m[["file_base","Group"]], on="file_base", how="left").drop(columns=["file_base"])
            bm["Group"] = m["Group"].fillna("UNASSIGNED")
            bm["XGroup"] = bm["Group"]
            bm["HueGroup"] = "ALL"
        else:
            raise RuntimeError("Missing X/Hue mapping. Run the grouping widget (Build Groups) first.")
        
        status.ok("Group and Metric dataframe merged")
        return bm
    


#@@@@@@@@@@@@@@@@@@ MELT DATAFRAME @@@@@@@@@@@@@@@@@@#
def melt_metric(df_l3, x_group = "Genotype", hue_group = "Sex", assay = None):
    """
    Melt the bandit metrics from wide to long

    Arguments:
        bm_l3; Dataframe
            Bandit metric L3 file
    Returns:
        long_df; Dataframe
            Bandit metric dataframe in a long format
    """

    status.step(f"Melting L3 to long format")

    df = df_l3.copy()

    #base_metric_names = [
    #"Win-stay","Lose-shift","PeakAccuracy",
    #"Total_pellets","Total_pokes","PokesPerPellet", "Weight",
    #"RetrievalTime","PokeTime","Daily_Pellets", "Left Poke with Pellet", "Right_Poke", "Inactive_Pokes", "Active_Pokes",
    #"Win-stay_Day","Win-stay_Night","Lose-shift_Day","Lose-shift_Night",
    #"PeakAccuracy_Day","PeakAccuracy_Night",
    #]

    base_metric_names = get_cols(assay, "metric", status)
    

    metric_cols = []

    # find all non meta feature columns
    for c in df.columns:
        if pd.api.types.is_numeric_dtype(df[c]):
            for base in base_metric_names:
                if c == base or c.startswith(base + "_"):
                    metric_cols.append(c); break
    seen = set(); metric_cols = [c for c in metric_cols if not (c in seen or seen.add(c))]
    if not metric_cols:
        raise RuntimeError("No numeric metric columns found among expected metrics.")

    candidate_id_vars = ["Gene", "Gene_ID", "Genotype","Sex","Strain","Start_Date","filename","Mouse_ID","Session_type","XGroup","HueGroup"]

    id_vars = [c for c in candidate_id_vars if c in df.columns]
    for need in ["XGroup","HueGroup","filename"]:
        if need not in id_vars: id_vars.append(need)

    long_df = pd.melt(
        df,
        id_vars=id_vars,
        value_vars=metric_cols,
        var_name="variable",
        value_name="value"
    )

    status.ok("Metric dataframe Melted")
    return long_df


#@@@@@@@@@@@@@@@@@@ DEFINE AESTHETICS @@@@@@@@@@@@@@@@@@#

### ------ General Helper functions ------ ###
def _hier_sort_key(g):
    """
    Called in:
    """
    lv = _x_levels(g)
    norm = []
    for tok in lv:
        is_blank = 1 if _is_unassigned_token(tok) else 0
        norm.append((is_blank, str(tok).upper()))
    wt_present = any(_is_wt_group(tok) for tok in lv) or _is_wt_group(g)
    wt_rank = 0 if wt_present else 1
    return (wt_rank,) + tuple(norm) + (str(g).upper(),)


def _order_x_groups(groups):
    return sorted(groups, key=_hier_sort_key)



def _x_levels(xname):
    s = str(xname)
    parts = [p.strip() for p in s.split("|")]
    wanted = globals().get("selected_group_cols_x", None)
    if isinstance(wanted, (list, tuple)) and wanted:
        if len(parts) < len(wanted):
            parts += [""] * (len(wanted) - len(parts))
        else:
            parts = parts[:len(wanted)]
    return parts

def _is_unassigned_token(s):
    return (str(s).strip().upper() in {"", "UNASSIGNED", "NONE", "NA", "N/A"})

def _is_wt_group(g):
    u = str(g).strip().upper()
    tokens = [t for t in re.split(r'[^A-Z0-9]+', u) if t]
    WT_ALIASES = {"WT", "WILDTYPE", "CONTROL", "CTRL"}
    return any(t in WT_ALIASES for t in tokens)




def define_aesthetics(long_df):
    """
    uses a very hacky solution of relying on widget package to pass structured strings containing something like a 
    dictionary defining the aesthetics.
    Arguments:
        long_df; Dataframe
            Long format dataframe of metrics 
    Returns:
        x_checks;
        x_colors; 
        ordered_x;
    """

    status.step("Defining Aesthetics for Plotting")

    named_defaults = [
    "dodgerblue", "red", "green", "orange", "purple",
    "brown", "pink", "gray", "olive", "cyan"]

    genotype_colors = {
        "WT":   "#7ACAFF",
        "HET":  "#9BDF94",
        "HOM/HEMI": "#FFB193",
        "HOM":      "#FFB193",
        "HEMI":     "#D2ACD3",
    }
    #add an argument that passes in a list or column  


    def _default_color(group, idx):
        """Explicitly apply genotype color if we have one else use positional default."""
        key = str(group).strip().upper()
        # Treat common wildtype aliases as WT so they pick up the WT hex.
        if key in {"WILDTYPE", "CONTROL", "CTRL"}:
            key = "WT"
        return genotype_colors.get(key, named_defaults[idx % len(named_defaults)])

    # Build the ordered list of XGroup levels
    all_x_groups = long_df["XGroup"].dropna().unique().tolist()
    if not all_x_groups:
        raise RuntimeError("No XGroup values found – check that the grouping step ran correctly.")

    ordered_x = _order_x_groups(all_x_groups)

    x_checks, x_colors = {}, {}
    group_rows = []
    for i, g in enumerate(ordered_x):
        chk = widgets.Checkbox(value=True, description=g, indent=False, 
                               layout=widgets.Layout(width="260px"))
        #col = widgets.Text(value=named_defaults[i % len(named_defaults)],
        #                layout=widgets.Layout(width="120px"))
        col = widgets.Text(value=_default_color(g, i),
                        layout=widgets.Layout(width="120px"))
        x_checks[g] = chk
        x_colors[g] = col
        # more compact row
        group_rows.append(widgets.HBox([chk, widgets.Label(""), col],
                                    layout=widgets.Layout(align_items="center", height="28px")))


    picker = widgets.VBox(group_rows, layout=widgets.Layout(gap="2px"))

    btn_all  = widgets.Button(description="Select all", layout=widgets.Layout(width="140px"))
    btn_none = widgets.Button(description="Clear", layout=widgets.Layout(width="140px"))
    def _set_all(val):
        for c in x_checks.values(): c.value = val
    btn_all.on_click(lambda _: _set_all(True))
    btn_none.on_click(lambda _: _set_all(False))

    # scrollable container for the (possibly long) group list
    picker_container = widgets.Box([picker],
        layout=widgets.Layout(overflow="auto", max_height="420px",
                            border="1px solid #ddd", padding="6px", width="360px"))

    left_col = widgets.VBox([
        widgets.HTML("<b>Groups & Colors</b>"),
        widgets.HBox([btn_all, btn_none], layout=widgets.Layout(gap="8px")),
        picker_container
    ], layout=widgets.Layout(width="380px"))

    status.ok(f"Aesthetics defined - x_checks: {x_checks}")
    status.ok(f"Aesthetics defined - x_colors: {x_colors}")
    status.ok(f"Aesthetics defined - ordered_x: {ordered_x}")
    

    return x_checks, x_colors, ordered_x




#@@@@@@@@@@@@@@@@@@ STATS @@@@@@@@@@@@@@@@@@#
def _fmt_p(p):
    if not np.isfinite(p):
        return "n/a"
    return f"p = {p:.3f}" if p >= 0.001 else "p < 0.001"

def _fmt_p_num(p):
    if p is None or (isinstance(p, float) and (not np.isfinite(p))):
        return "n/a"
    p = float(p)
    return f"{p:.4f}" if p >= 0.0001 else "<0.0001"

def _fmt_F(df_num, df_den, F):
    if df_num is None or df_den is None or F is None:
        return "n/a"
    if not np.isfinite(F):
        return "n/a"
    return f"F({int(df_num)}, {int(df_den)}) = {float(F):.3f}"

def _p_to_stars(p):
    if not np.isfinite(p): 
        return ""
    if p < 1e-4: 
        return "****"
    if p < 1e-3: 
        return "***"
    if p < 1e-2: 
        return "**"
    if p < 5e-2: 
        return "*"
    return ""


def _anova_subset(df):
    """
    If >=2 Hue levels: two-way ANOVA (XGroup, HueGroup, interaction)
    Else: one-way ANOVA (XGroup).
    """
    out = {"p_x": np.nan, "p_h": np.nan, "p_int": np.nan, "n_h": 0, "ok": False, "err": None}
    d = df.dropna(subset=["value","XGroup"])
    if d.empty or d["XGroup"].nunique() < 2:
        out["err"] = "Too few groups"; return out
    n_h = d["HueGroup"].nunique(dropna=True); out["n_h"] = n_h
    try:
        if n_h >= 2:
            model = ols('value ~ C(XGroup) + C(HueGroup) + C(XGroup):C(HueGroup)', data=d).fit()
            an = sm.stats.anova_lm(model, typ=2)
            out["p_x"]   = float(an.loc['C(XGroup)','PR(>F)'])
            out["p_h"]   = float(an.loc['C(HueGroup)','PR(>F)'])
            out["p_int"] = float(an.loc['C(XGroup):C(HueGroup)','PR(>F)'])
            out["ok"] = True
        else:
            model = ols('value ~ C(XGroup)', data=d).fit()
            out["p_x"] = float(model.f_pvalue); out["ok"] = True
    except Exception as e:
        out["err"] = str(e)
    return out

### P-value Call ###
# Pingouin p-value helper
def _pg_get_pval(pg_res):
    """
    Robustly extract p-value from a Pingouin result DataFrame.
    Works across versions that rename p-value columns.
    """
    if pg_res is None:
        return np.nan
    if not isinstance(pg_res, pd.DataFrame) or pg_res.empty:
        return np.nan

    candidates = [
        "p-val", "p_val", "pval", "pvalue", "p_value",
        "p-unc", "p_unc", "p", "P-val", "P_val"
    ]
    for c in candidates:
        if c in pg_res.columns:
            try:
                return float(pg_res[c].values[0])
            except Exception:
                return np.nan

    raise KeyError(f"Pingouin result has no known p-value column. Columns: {pg_res.columns.tolist()}")


### Alternative P-Value Call ### 
"""
def _get_p_col(df):
    for col in ["p-val", "p-unc", "p-corr", "p", "pval", "PR(>F)"]:
        if col in df.columns:
            return col
    raise KeyError(f"No p-value column found. Available columns: {list(df.columns)}")

def _safe_ttest_p(a, b, paired=False):
    if pg is None:
        return np.nan
    try:
        res = pg.ttest(a, b, paired=paired)
        p_col = _get_p_col(res)
        return float(res[p_col].iloc[0])
    except Exception:
        return np.nan
"""




def _stats_text(dfm, x_label, hue_label, *, mode="ref", ref_group=None, pair_list=None):
    df = dfm.dropna(subset=["value"]).copy()
    g_n = df["XGroup"].nunique(dropna=True)
    h_n = df["HueGroup"].nunique(dropna=True)

    if mode == "pairs" and pair_list:
        lines = ["Selected pairwise ANOVA tests:"]
        for a,b in pair_list:
            sub = df[df["XGroup"].isin([a,b])]
            res = _anova_subset(sub)
            if not res["ok"]:
                lines.append(f"{a} vs {b}: {res['err'] or 'failed'}"); continue
            if res["n_h"] >= 2:
                lines.append(
                    f"{a} vs {b} (Two-way: {x_label}, {hue_label})  "
                    f"{x_label}: {_fmt_p(res['p_x'])} | {hue_label}: {_fmt_p(res['p_h'])} | "
                    f"{x_label}×{hue_label}: {_fmt_p(res['p_int'])}"
                )
            else:
                lines.append(f"{a} vs {b} (One-way {x_label}): {_fmt_p(res['p_x'])}")
        return "\n".join(lines)

    def fmt(p): return _fmt_p(p)
    if g_n == 2 and h_n <= 1:
        g1, g2 = sorted(df["XGroup"].unique())
        v1 = df[df["XGroup"] == g1]["value"].dropna()
        v2 = df[df["XGroup"] == g2]["value"].dropna()
        if len(v1) > 1 and len(v2) > 1:
            p = _pg_get_pval(pg.ttest(v1, v2, paired=False))
            ### Alternative p-value call ###
            # p = _safe_ttest_p(v1, v2, paired=False)
            return f"t-test ({x_label}): {fmt(p)}\n{g1} vs {g2}"
        return "t-test: not enough data"

    if g_n >= 2 and h_n >= 2:
        try:
            model = ols('value ~ C(XGroup) + C(HueGroup) + C(XGroup):C(HueGroup)', data=df).fit()
            an = sm.stats.anova_lm(model, typ=2)
            return (
                "Two-way ANOVA\n"
                f"{x_label}: {fmt(float(an.loc['C(XGroup)','PR(>F)']))}\n"
                f"{hue_label}: {fmt(float(an.loc['C(HueGroup)','PR(>F)']))}\n"
                f"{x_label}×{hue_label}: {fmt(float(an.loc['C(XGroup):C(HueGroup)','PR(>F)']))}"
            )
        except Exception as e:
            return f"ANOVA failed: {e}"

    if g_n >= 2:
        try:
            model = ols('value ~ C(XGroup)', data=df).fit()
            return f"One-way ANOVA ({x_label}): {fmt(float(model.f_pvalue))}"
        except Exception as e:
            return f"One-way ANOVA failed: {e}"
    return "Too few groups for stats"



def _twoway_anova_full(df):
    """
    Returns dict with full ANOVA stats including df for F.
    If HueGroup has <2 levels -> one-way (XGroup only).
    """
    d = df.dropna(subset=["value","XGroup"]).copy()
    if d.empty or d["XGroup"].nunique() < 2:
        return {"ok": False, "err": "Too few groups"}

    n_h = d["HueGroup"].nunique(dropna=True) if "HueGroup" in d.columns else 0

    try:
        if n_h >= 2:
            model = ols("value ~ C(XGroup) + C(HueGroup) + C(XGroup):C(HueGroup)", data=d).fit()
            an = sm.stats.anova_lm(model, typ=2)

            residual_row = "Residual"
            ss_error = float(an.loc[residual_row, "sum_sq"])
            df_den = int(an.loc[residual_row, "df"])

            ss_x = float(an.loc["C(XGroup)", "sum_sq"])
            ss_h = float(an.loc["C(HueGroup)", "sum_sq"])
            ss_int = float(
                an.loc["C(XGroup):C(HueGroup)", "sum_sq"]
            )

            eta_p_x = (
                ss_x / (ss_x + ss_error)
                if (ss_x + ss_error) > 0
                else np.nan
            )

            eta_p_h = (
                ss_h / (ss_h + ss_error)
                if (ss_h + ss_error) > 0
                else np.nan
            )

            eta_p_int = (
                ss_int / (ss_int + ss_error)
                if (ss_int + ss_error) > 0
                else np.nan
            )

            return {
                "ok": True,
                "test": "Two-way ANOVA",

                "F_x": float(an.loc["C(XGroup)", "F"]),
                "df_x_num": int(an.loc["C(XGroup)", "df"]),
                "df_x_den": df_den,
                "p_x": float(an.loc["C(XGroup)", "PR(>F)"]),
                "ss_x": ss_x,
                "eta_p_x": eta_p_x,

                "F_h": float(an.loc["C(HueGroup)", "F"]),
                "df_h_num": int(an.loc["C(HueGroup)", "df"]),
                "df_h_den": df_den,
                "p_h": float(an.loc["C(HueGroup)", "PR(>F)"]),
                "ss_h": ss_h,
                "eta_p_h": eta_p_h,

                "F_int": float(an.loc["C(XGroup):C(HueGroup)", "F"]),
                "df_int_num": int(an.loc["C(XGroup):C(HueGroup)", "df"]),
                "df_int_den": df_den,
                "p_int": float(an.loc["C(XGroup):C(HueGroup)", "PR(>F)"]),
                "ss_int": ss_int,
                "eta_p_int": eta_p_int,
                "ss_error": ss_error,
            }

        else:
            model = ols("value ~ C(XGroup)", data=d).fit()
            an = sm.stats.anova_lm(model, typ=2)

            ss_x = float(an.loc["C(XGroup)", "sum_sq"])
            ss_error = float(an.loc["Residual", "sum_sq"])

            eta_p_x = (
                ss_x / (ss_x + ss_error)
                if (ss_x + ss_error) > 0
                else np.nan
            )

            return {
                "ok": True,
                "test": "One-way ANOVA",
                "F_x": float(an.loc["C(XGroup)", "F"]),
                "df_x_num": int(an.loc["C(XGroup)", "df"]),
                "df_x_den": int(an.loc["Residual", "df"]),
                "p_x": float(an.loc["C(XGroup)", "PR(>F)"]),
                "ss_x": ss_x,
                "eta_p_x": eta_p_x,
                "ss_error": ss_error,
            }

    except Exception as e:
        return {"ok": False, "err": str(e)}


def _subjects_n_per_group(dfm):
    # n per XGroup (counts non-NaN values)
    n_per_x = dfm.groupby("XGroup")["value"].apply(lambda s: int(s.dropna().shape[0]))
    groups = _order_x_groups(dfm["XGroup"].dropna().unique().tolist())
    parts = [f"{g}: n={n_per_x.get(g, 0)}" for g in groups]
    return " | ".join(parts)


def _posthoc_ref_ttests(dfm, ref_group):
    d = dfm.dropna(subset=["value","XGroup"]).copy()
    ref = d[d["XGroup"] == ref_group]["value"].dropna().to_numpy()
    if ref_group is None or ref_group not in d["XGroup"].unique():
        return "n/a"

    groups = [g for g in d["XGroup"].unique().tolist() if g != ref_group]
    lines = []
    for g in _order_x_groups(groups):
        vals = d[d["XGroup"] == g]["value"].dropna().to_numpy()
        if len(vals) < 2 or len(ref) < 2:
            lines.append(f"{g} vs {ref_group}: not enough data")
            continue
        try:
            p = _pg_get_pval(pg.ttest(vals, ref, paired=False))
        except Exception:
            p = np.nan
        lines.append(f"{g} vs {ref_group}: p={_fmt_p_num(p)} {_p_to_stars(p)}")
    return " | ".join(lines) if lines else "n/a"


def _posthoc_pairs_anova(dfm, pair_list, x_label, hue_label):
    if not pair_list:
        return "n/a"
    lines = []
    for a, b in pair_list:
        sub = dfm[dfm["XGroup"].isin([a, b])].dropna(subset=["value"])
        if sub["XGroup"].nunique() < 2:
            continue
        res = _anova_subset(sub)  # uses existing helper (p only)
        if not res["ok"]:
            lines.append(f"{a} vs {b}: {res['err'] or 'failed'}")
            continue
        if res["n_h"] >= 2:
            lines.append(
                f"{a} vs {b}: {x_label} p={_fmt_p_num(res['p_x'])} {_p_to_stars(res['p_x'])}, "
                f"{hue_label} p={_fmt_p_num(res['p_h'])}, int p={_fmt_p_num(res['p_int'])}"
            )
        else:
            lines.append(f"{a} vs {b}: p={_fmt_p_num(res['p_x'])} {_p_to_stars(res['p_x'])}")
    return " | ".join(lines) if lines else "n/a"


def _fmt_eta_p2(value):
    """
    Format partial eta squared to three decimal places.
    """
    try:
        value = float(value)
    except (TypeError, ValueError):
        return "n/a"

    if not np.isfinite(value):
        return "n/a"

    return f"{value:.3f}"










def build_stats_table(long_df, ordered_x, root_path, mode = "ref", 
                      assay = None, ref_group=None, pair_list=None):
    """
    Arguments:
        long_df : Dataframe
            melted dataframe in a long format
        ordered : List
            List of genotypes that will be tested against eachother
        root_path : Path
            Path to the root directory where the stats table will be saved
    """

    status.step("Building Stats Table")

    # Create the directory that will be writen to
    out_dir = Path(root_path, "stats_table")
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # get metric columns
    metric_cols = get_cols(assay, "metric", status)

    # get the groupings for which stats will be conducted
    sel_x = ordered_x

    
    ### Define Dictionaries to control tests dome
    # check for hemi genotypes and warn user that stats will be conducted with hemi groups
    # we need to conduct post hoc tests to account for hemi groups
    # and the stats will be divided into two groups by sex to account for the hemi groups
    # Male: WT x HEMI
    # Female: WT x HET & WT x HOM

    hemi_match = [geno for geno in sel_x if 'hemi' in geno.lower()]
    ref = ref_group or "WT"

    affected = "HOM/HEMI"   # merged X-linked group; Sex separates Hom(F) from Hemi(M)

    if hemi_match:
        status.warn("'hemi' genotype detected: running pooled + sex-split post hocs")
        test_dict = {
            "pooled":     {"filter": {},                                           "test_mode": "ref", "ref_grp": ref},
            "male_hemi":  {"filter": {"HueGroup": "M", "XGroup": [ref, affected]}, "test_mode": "pairs", "ref_grp": ref},
            "female_hom": {"filter": {"HueGroup": "F", "XGroup": [ref, affected]}, "test_mode": "pairs", "ref_grp": ref},
            "female_het": {"filter": {"HueGroup": "F", "XGroup": [ref, "HET"]},    "test_mode": "pairs", "ref_grp": ref},
        }
    else:
        test_dict = {
            "pooled": {"filter": {}, "test": mode, "ref": ref, "pairs": pair_list or []},
        }
        



    ### Information about tests going to be run ###
    # inform the user which groups are availabel for testing
    status.ok(f"Stats will be conducted for the following X groups: {sel_x}")

    # Pull our names and hues
    x_label_name = _grouping_label("X")
    hue_label_name = _grouping_label("Hue")


    # Declare empty rows to write to
    rows = []

    for key, value in test_dict.items():
        status.sub(f"Conducting stats for {key}")

        filt = value.get("filter", {})
        status.ok(f"filter: {filt}")
        # unpack test
        ref_group = value.get("ref_grp")
        status.ok(f"ref_grp: {ref_group}")
        # unpack ref-mode
        mode = value.get("test_mode")
        status.ok(f"Running mode: {mode}")

        # Unpack Pairs
        xg = filt.get("XGroup")
        if value.get("pairs"):
            pairs = value["pairs"]
        elif isinstance(xg, (list, tuple)) and len(xg) == 2:
            pairs = [tuple(xg)]                 # e.g. [("WT", "HOM/HEMI")]
        else:
            pairs = []
        status.ok(f"Pair List: {pairs}")


        ### Run the stats ###
        # iterate over dict of dict
        
        for metric in metric_cols:

            # Adjust dfm
            dfm = long_df[(long_df["variable"] == metric) & (long_df["XGroup"].isin(sel_x))].copy()

            # Apply THIS test's filter (empty filter = pooled, no-op).
            for col, val in filt.items():
                dfm = dfm[dfm[col].isin(val)] if isinstance(val, (list, tuple, set)) \
                      else dfm[dfm[col] == val]



            dfm = dfm.dropna(subset=["value"])

            if dfm.empty:
                continue



            stats = _twoway_anova_full(dfm)
            subjects = _subjects_n_per_group(dfm)

            if not stats.get("ok", False):
                rows.append({
                    "Comparison": key,
                    "Figure": metric,
                    "Test": "ANOVA failed",
                    "Subjects": subjects,
                    "F value interaction": "n/a",
                    "p value interaction": "n/a",
                    "Partial eta squared interaction": "n/a",
                    "Main effects": stats.get("err", "unknown error"),
                    "Partial eta squared main effects": "n/a",
                    "Post hoc test": "n/a",
                    "Post hoc results": "n/a",
                })
                continue

            if stats["test"] == "Two-way ANOVA":
                main_effects = (
                    f"{x_label_name}: {_fmt_F(stats['df_x_num'], stats['df_x_den'], stats['F_x'])}, "
                    f"p={_fmt_p_num(stats['p_x'])} {_p_to_stars(stats['p_x'])}; "
                    f"{hue_label_name}: {_fmt_F(stats['df_h_num'], stats['df_h_den'], stats['F_h'])}, "
                    f"p={_fmt_p_num(stats['p_h'])} {_p_to_stars(stats['p_h'])}"
                )
                main_effect_sizes = (
                    f"{x_label_name}: "
                    f"partial η²={_fmt_eta_p2(stats['eta_p_x'])}; "
                    f"{hue_label_name}: "
                    f"partial η²={_fmt_eta_p2(stats['eta_p_h'])}"
                )

                f_int = _fmt_F(stats["df_int_num"], stats["df_int_den"], stats["F_int"])
                p_int = _fmt_p_num(stats["p_int"]) + (f" {_p_to_stars(stats['p_int'])}" if np.isfinite(stats["p_int"]) else "")

                if np.isfinite(stats["p_int"]):
                    stars = _p_to_stars(stats["p_int"])
                    if stars:
                        p_int += f" {stars}" 
                eta_p_int = _fmt_eta_p2(
                    stats["eta_p_int"]
                )
            else:
                main_effects = (
                    f"{x_label_name}: {_fmt_F(stats['df_x_num'], stats['df_x_den'], stats['F_x'])}, "
                    f"p={_fmt_p_num(stats['p_x'])} {_p_to_stars(stats['p_x'])}"
                )
                #f_int, p_int = "n/a", "n/a"
                main_effect_sizes = (
                    f"{x_label_name}: "
                    f"partial η²={_fmt_eta_p2(stats['eta_p_x'])}"
                )
                f_int, p_int, eta_p_int = "n/a", "n/a", "n/a"

            if mode == "ref":
                posthoc_test = "Unpaired t-tests vs reference"
                posthoc_res  = _posthoc_ref_ttests(dfm, ref_group)
            else:
                posthoc_test = "Selected pairwise ANOVA"
                posthoc_res  = _posthoc_pairs_anova(dfm, pair_list or [], x_label_name, hue_label_name)

            rows.append({
                "Comparison": key,
                "Figure": metric,
                "Test": stats["test"],
                "Subjects": subjects,
                "F value interaction": f_int,
                "p value interaction": p_int,
                "Partial eta squared interaction": eta_p_int,
                "Main effects": main_effects,
                "Partial eta squared main effects": main_effect_sizes,
                "Post hoc test": posthoc_test,
                "Post hoc results": posthoc_res,
            })

    # change list to dataframe
    stats_df = pd.DataFrame(rows)


    
    ### Prepare to write ###
    # Grab example row
    example = long_df.iloc[0]

    # Grab the strain number
    strain_num_raw = example.get("Gene_ID", example.get("Strain_ID", "NA"))
    try:
        strain_num = f"{int(strain_num_raw):03d}"
    except Exception:
        strain_num = str(strain_num_raw).zfill(3)

    # grab the task name
    task_name = str(example.get("Session_type", "Unknown")).replace(" ", "_")

    # grab the strain name
    strain_name = str(example.get("Gene", example.get("Strain", "NA"))).replace(" ", "_")

    # pull the name together
    fname = f"{strain_name}_{strain_num}_{task_name}_stats_table.csv"
    out_path = out_dir / fname
    
    # write stats table
    stats_df.to_csv(out_path, index=False)

    ### Return ###
    status.ok("Stats table built")

    return stats_df



def build_stats_table_old(long_df, ordered_x, root_path, mode = "ref", hemicatch = True, assay = None, ref_group=None, pair_list=None):
    """
    Arguments:
        long_df : Dataframe
            metled dataframe in a long format
        ordered : List
            List of genotypes that will be tested against eachother
    """

    status.step("Building Stats Table")

    
    # Create the directory that will be writen to
    out_dir = Path(root_path, "stats_table")
    out_dir.mkdir(parents=True, exist_ok=True)
    
    # get metric columns
    metric_cols = get_cols(assay, "metric", status)

    # get the groupings for which stats will be conducted
    sel_x = ordered_x

    
    x_label_name = _grouping_label("X")
    hue_label_name = _grouping_label("Hue")

    ### run the stats ###
    rows = []
    for metric in metric_cols:
        dfm = long_df[(long_df["variable"] == metric) & (long_df["XGroup"].isin(sel_x))].copy()
        dfm = dfm.dropna(subset=["value"])
        if dfm.empty:
            continue

        stats = _twoway_anova_full(dfm)
        subjects = _subjects_n_per_group(dfm)

        if not stats.get("ok", False):
            rows.append({
                "Figure": metric,
                "Test": "ANOVA failed",
                "Subjects": subjects,
                "F value interaction": "n/a",
                "p value interaction": "n/a",
                "Partial eta squared interaction": "n/a",
                "Main effects": stats.get("err", "unknown error"),
                "Partial eta squared main effects": "n/a",
                "Post hoc test": "n/a",
                "Post hoc results": "n/a",
            })
            continue

        if stats["test"] == "Two-way ANOVA":
            main_effects = (
                f"{x_label_name}: {_fmt_F(stats['df_x_num'], stats['df_x_den'], stats['F_x'])}, "
                f"p={_fmt_p_num(stats['p_x'])} {_p_to_stars(stats['p_x'])}; "
                f"{hue_label_name}: {_fmt_F(stats['df_h_num'], stats['df_h_den'], stats['F_h'])}, "
                f"p={_fmt_p_num(stats['p_h'])} {_p_to_stars(stats['p_h'])}"
            )
            main_effect_sizes = (
                f"{x_label_name}: "
                f"partial η²={_fmt_eta_p2(stats['eta_p_x'])}; "
                f"{hue_label_name}: "
                f"partial η²={_fmt_eta_p2(stats['eta_p_h'])}"
            )

            f_int = _fmt_F(stats["df_int_num"], stats["df_int_den"], stats["F_int"])
            p_int = _fmt_p_num(stats["p_int"]) + (f" {_p_to_stars(stats['p_int'])}" if np.isfinite(stats["p_int"]) else "")

            if np.isfinite(stats["p_int"]):
                stars = _p_to_stars(stats["p_int"])
                if stars:
                    p_int += f" {stars}" 
            eta_p_int = _fmt_eta_p2(
                stats["eta_p_int"]
            )
        else:
            main_effects = (
                f"{x_label_name}: {_fmt_F(stats['df_x_num'], stats['df_x_den'], stats['F_x'])}, "
                f"p={_fmt_p_num(stats['p_x'])} {_p_to_stars(stats['p_x'])}"
            )
            #f_int, p_int = "n/a", "n/a"
            main_effect_sizes = (
                f"{x_label_name}: "
                f"partial η²={_fmt_eta_p2(stats['eta_p_x'])}"
            )
            f_int, p_int, eta_p_int = "n/a", "n/a", "n/a"

        if mode == "ref":
            posthoc_test = "Unpaired t-tests vs reference"
            posthoc_res  = _posthoc_ref_ttests(dfm, ref_group)
        else:
            posthoc_test = "Selected pairwise ANOVA"
            posthoc_res  = _posthoc_pairs_anova(dfm, pair_list or [], x_label_name, hue_label_name)

        rows.append({
            "Figure": metric,
            "Test": stats["test"],
            "Subjects": subjects,
            "F value interaction": f_int,
            "p value interaction": p_int,
            "Partial eta squared interaction": eta_p_int,
            "Main effects": main_effects,
            "Partial eta squared main effects": main_effect_sizes,
            "Post hoc test": posthoc_test,
            "Post hoc results": posthoc_res,
        })

    # change list to dataframe
    stats_df = pd.DataFrame(rows)
    
    ### Prepare to write ###
    # Grab example row
    example = long_df.iloc[0]

    # Grab the strain number
    strain_num_raw = example.get("Gene_ID", example.get("Strain_ID", "NA"))
    try:
        strain_num = f"{int(strain_num_raw):03d}"
    except Exception:
        strain_num = str(strain_num_raw).zfill(3)

    # grab the task name
    task_name = str(example.get("Session_type", "Unknown")).replace(" ", "_")

    # grab the strain name
    strain_name = str(example.get("Gene", example.get("Strain", "NA"))).replace(" ", "_")

    # pull the name together
    fname = f"{strain_name}_{strain_num}_{task_name}_stats_table.csv"
    out_path = out_dir / fname
    
    # write stats table
    stats_df.to_csv(out_path, index=False)

    ### Return ###
    status.ok("Stats table built")

    return stats_df




#@@@@@@@@@@@@@@@@@@ METRIC PLOTTING @@@@@@@@@@@@@@@@@@#

def _dot_palette(hues):
    hues = list(hues)
    if len(hues) == 0: 
        return {}
    if len(hues) == 1: 
        return {hues[0]: "black"}
    if len(hues) == 2: 
        return {hues[0]: "white", hues[1]: "black"}
    defaults = plt.rcParams.get('axes.prop_cycle', None)
    colors = defaults.by_key()['color'] if defaults else ["C0","C1","C2","C3","C4","C5","C6","C7","C8","C9"]
    return {h: colors[i % len(colors)] for i, h in enumerate(hues)}


def _draw_bracket(ax, x1, x2, y, h, text):
    ax.plot([x1, x1, x2, x2], [y, y+h, y+h, y], lw=1, c="black", zorder=5)
    ax.text((x1+x2)/2, y+h, text, ha="center", va="bottom", fontsize=16, fontweight="bold")

def _selected_x_and_colors(x_checks,x_colors):
    """
    Called in _run_plots
    """
    sel = _selected_x(x_checks)
    color_map = {}
    for g in sel:
        val = x_colors[g].value.strip()
        color_map[g] = val if val else "tab:blue"
    return sel, color_map

def _selected_x(x_checks):
    return _order_x_groups([g for g, cb in x_checks.items() if cb.value])


def _choose_ref_group(order):
    for g in order:
        if _is_wt_group(g):
            return g
    return order[0] if order else None


def _grouping_label(which="X"):
    if which.lower().startswith("x"):
        cols = globals().get("selected_group_cols_x", [])
        default = "XGroup"
    else:
        cols = globals().get("selected_group_cols_hue", [])
        default = "HueGroup"
    cols = [str(c).strip() for c in (cols or []) if str(c).strip()]
    return " | ".join(cols) if cols else default


def _order_hue_groups(hues):
    hp = globals().get("HUE_PRIORITY", ["Female", "Male", "F", "M", "ALL", "UNASSIGNED"])
    hp_lower = [p.lower() for p in hp]
    def _prio(h):
        u = str(h).strip()
        try:
            return (0, hp_lower.index(u.lower()), u.upper())
        except ValueError:
            return (1, u.upper())
    return sorted([h for h in hues if h is not None], key=_prio)




### main plotting function ###
def _plot_metric_clean(df_metric, variable, x_color_map, *, mode="ref", 
                       ref_group=None, pair_list=None, return_fig=False):
    dfm = df_metric.copy()
    order = _order_x_groups(dfm["XGroup"].dropna().unique().tolist())
    if not order: return None
    if (not ref_group) or (ref_group not in order):
        ref_group = _choose_ref_group(order)

    x_label_name   = _grouping_label("X")
    hue_label_name = _grouping_label("Hue")

    hue_levels = [h for h in dfm["HueGroup"].dropna().unique().tolist()]
    pal_dots = _dot_palette(hue_levels)

    width = max(5, 1 * len(order))
    height = 4.0
    fig, (ax_plot, ax_text) = plt.subplots(
        1, 2, figsize=(width, height), gridspec_kw={'width_ratios': [3, 1]}
    )

    # Bars
    #bar_palette = [x_color_map.get(g, "tab:blue") for g in order]
    bar_palette = {g: x_color_map.get(g, "tab:blue") for g in order}
    # replaced original barplot call
    #sns.barplot(data=dfm, x="XGroup", y="value", order=order, 
    #            ci=None, alpha=ALPHA, ax=ax_plot, 
    #            palette=bar_palette)
    sns.barplot(data=dfm, x="XGroup", y="value", order=order,
                hue="XGroup", legend=False,
                errorbar=None,
                alpha=ALPHA, ax=ax_plot, palette=bar_palette)   

    # Determine hue levels in a controlled order
    raw_hues = dfm["HueGroup"].dropna().unique().tolist()
    hue_levels = _order_hue_groups(raw_hues)

    # Colors for dots — your helper already maps 2 hues as {hues[0]: "white", hues[1]: "black"}
    pal_dots = _dot_palette(hue_levels)

    # Points
    sns.stripplot(
        data=dfm, x="XGroup", y="value",
        order=order,
        hue="HueGroup",
        hue_order=hue_levels,        # <-- enforce hue order
        jitter=True, dodge=False, size=7,
        edgecolor="black", linewidth=1,
        palette=pal_dots,            # <-- colors aligned to hue_order
        ax=ax_plot, zorder=3, alpha=ALPHA
    )
    if ax_plot.legend_ is not None:
        ax_plot.legend_.remove()

    # Legend (right panel) in the same hue order
    if len(hue_levels) >= 2:
        handles = [plt.Line2D([0],[0], marker='o', linestyle='None',
                              markerfacecolor=pal_dots[h], markeredgecolor='black', label=str(h))
                  for h in hue_levels]
        ax_text.legend(handles=handles, title=hue_label_name, loc="upper left", bbox_to_anchor=(0, 0.6))

    # Annotations
    y_min, y_max = ax_plot.get_ylim()
    span = (y_max - y_min) if y_max > y_min else 1.0
    bump = 0.06 * span
    data_max = dfm["value"].max() if dfm["value"].notna().any() else y_max

    if mode == "ref" and (ref_group in order):
        ref_vals = dfm[dfm["XGroup"] == ref_group]["value"].dropna().to_numpy()
        for g in order:
            if g == ref_group: continue
            vals = dfm[dfm["XGroup"] == g]["value"].dropna().to_numpy()
            if len(vals) >= 2 and len(ref_vals) >= 2:
                try:
                    p = _pg_get_pval(pg.ttest(vals, ref_vals, paired=False))
                except Exception:
                    p = np.nan
                if np.isfinite(p) and p < 0.05:
                    xloc = order.index(g)
                    gmax = dfm[dfm["XGroup"] == g]["value"].max()
                    y_star = (gmax if np.isfinite(gmax) else data_max) + bump
                    ax_plot.text(xloc, y_star, _p_to_stars(p),
                                 ha="center", va="bottom", fontsize=16, fontweight="bold")
                    y_max = max(y_max, y_star + bump)
        ax_plot.set_ylim(y_min, y_max)

    elif mode == "pairs" and pair_list:
        base = (dfm["value"].max() if dfm["value"].notna().any() else y_max) + bump
        step = 0.12 * span
        k = 0
        for a,b in pair_list:
            if (a not in order) or (b not in order):
                continue
            sub = dfm[dfm["XGroup"].isin([a,b])].dropna(subset=["value"])
            if sub["XGroup"].nunique() < 2:
                continue
            res = _anova_subset(sub)
            # draw bracket ONLY if XGroup effect significant
            if res["ok"] and np.isfinite(res["p_x"]) and (res["p_x"] < 0.05):
                x1 = order.index(a); x2 = order.index(b)
                if x1 > x2: x1, x2 = x2, x1
                y_here = base + k * step
                _draw_bracket(ax_plot, x1, x2, y_here, 0.04 * span, _p_to_stars(res["p_x"]))
                y_max = max(y_max, y_here + 0.08 * span)
                k += 1
        ax_plot.set_ylim(y_min, y_max)

    ax_plot.set_title("")
    ax_plot.set_xlabel("")
    ax_plot.set_ylabel(variable)
    plt.setp(ax_plot.get_xticklabels(), rotation=45, ha='right')
    sns.despine(ax=ax_plot)

    # Right panel: stats + Hue legend
    ax_text.axis("off")
    ax_text.text(
        0, 1,
        _stats_text(dfm, x_label_name, hue_label_name, mode=mode, ref_group=ref_group, pair_list=pair_list),
        va="top", ha="left", fontsize=12, transform=ax_text.transAxes
    )
    if len(hue_levels) >= 2:
        handles = [plt.Line2D([0],[0], marker='o', linestyle='None',
                              markerfacecolor=pal_dots[h], markeredgecolor='black', label=str(h))
                   for h in hue_levels]
        ax_text.legend(handles=handles, title=hue_label_name, loc="upper left", bbox_to_anchor=(0, 0.6))

    plt.tight_layout()

    return fig if return_fig else plt.show()



def _run_plots(long_df, x_checks, x_colors, ordered_x, root_path, mode = "ref", _=None):
    """
    Function that wraps around the _plot_metric_clean to loop through different metrics
    Returns:
        saved_paths; List
            list of saved paths to the bandit metric plots
    """
    #clear_output()

    status.step("Creating Metric Plots")
    # intitate a empty list to capture the results
    saved_paths  = []

    # Create the directory that will be writen to
    out_dir = Path(root_path, "metric_bar_plots")
    out_dir.mkdir(parents=True, exist_ok=True)


    sel_x, color_map = _selected_x_and_colors(x_checks, x_colors)
    if len(sel_x) < 1:
        print("Select at least one X group."); return

    #mode = mode_radio.valuez
    ref_dropdown = widgets.Dropdown(
        options = ordered_x, value=_choose_ref_group(ordered_x),
        description = "Reference:", layout=widgets.Layout(width="320px")
    )   

    if mode == "ref":
        ref = ref_dropdown.value if (ref_dropdown.value in sel_x) else _choose_ref_group(sel_x)
        status.ok(f"Showing X groups: {sel_x}  |  reference for stars: {ref}")
    else:
        pair_list = _current_pairs()
        if not pair_list:
            print(f"Showing X groups: {sel_x}  |  no pairs selected (select at least one)."); return
        print(f"Showing X groups: {sel_x}  |  pairs: {pair_list}")

    exclude = {"PeakAccuracy_Day","PeakAccuracy_Night",
                "Win-stay_Day","Win-stay_Night",
                "Lose-shift_Day","Lose-shift_Night"}
    metrics = [m for m in long_df["variable"].dropna().unique() if m not in exclude]

    for metric in metrics:
        subset = long_df[(long_df["variable"] == metric) & (long_df["XGroup"].isin(sel_x))]
        if subset["value"].dropna().empty:
            status.warn(f"Skipping {metric} — no data for selected X groups."); continue
        if mode == "ref":
            fig = _plot_metric_clean(
                subset, metric,
                x_color_map={g: color_map[g] for g in sel_x if g in subset['XGroup'].unique()},
                mode="ref", ref_group=ref,
                return_fig=True
            )
        else:
            fig = _plot_metric_clean(
                subset, metric,
                x_color_map={g: color_map[g] for g in sel_x if g in subset['XGroup'].unique()},
                mode="pairs", pair_list=_current_pairs(),
                return_fig=True
            )

        if fig is None:
            status.warn(f"Skipping {metric} — no figure produced.")
            continue

        safe_name = re.sub(r"[^A-Za-z0-9_-]+", "_", metric).strip("_")
        out_path = out_dir / f"{safe_name}.pdf"

        # Save the per-metric bar plots as PDFs for archival/print-friendly use.
        # The final L4 composite figure keeps its own format handling in each assay.
        fig.savefig(out_path, dpi=300, bbox_inches="tight")

        plt.close(fig)

        saved_paths.append(out_path)
        status.ok(f"Saved {metric} -> {out_path}")
    
    return saved_paths 


#@@@@@@@@@@@@@@@@@@ L4 SPECIFIC FUNCTIONS @@@@@@@@@@@@@@@@@@#
def _plot_metric_display(dfm, variable, ax, x_color_map, *,
                         group_order=None, hue_order=None, ylabel=None,
                         xlabel=None,
                         pval_fontsize=11, label_fontsize=13):
    """
    Draw ONE metric as a stripped-down bar+strip panel onto a caller-supplied
    Axes, for use in the composite L4 figure.

    Unlike _plot_metric_clean (which owns a 2-panel figure with a stats
    sidebar), this draws only the bar + individual dots + a single top-centered
    genotype p-value. It creates no figure and no per-panel legend: the caller
    (assemble_l4) supplies the Axes and builds one shared Sex legend for the
    whole figure.

    Arguments:
        dfm : DataFrame
            Long-format rows for a SINGLE metric (already filtered to `variable`),
            with columns XGroup / HueGroup / value.
        variable : str
            Metric name; used only as the y-label fallback.
        ax : matplotlib Axes
            Target axes to draw into.
        x_color_map : dict
            {XGroup -> color string} for the bars. Keys must match the (already
            relabeled) XGroup values.
        group_order : list | None
            Bar order along x. Defaults to the library's standard order.
        hue_order : list | None
            Controlled Sex order so dot colors stay consistent across panels.
        ylabel : str | None
            Y-axis label (e.g. "Total pokes"). Falls back to `variable`.

    Returns:
        handles : list[Line2D]
            Legend proxy handles for the hue (Sex) levels, so the caller can
            build a single shared legend. Empty list if fewer than 2 hue levels.
    """


    dfm = dfm.copy()

    # Bar order: caller-provided, else fall back to the library's standard order.
    order = group_order or _order_x_groups(dfm["XGroup"].dropna().unique().tolist())
    if not order:
        return []

    # Hue (Sex) order + dot colors, matching _plot_metric_clean's convention
    # (helper maps 2 hues as {hues[0]: "white", hues[1]: "black"}).
    hue_levels = hue_order or core._order_hue_groups(dfm["HueGroup"].dropna().unique().tolist())
    pal_dots = _dot_palette(hue_levels)

    # --- Bars: mean per XGroup, no seaborn error bars, alpha shared with dots ---
    bar_palette = {g: x_color_map.get(g, "tab:blue") for g in order}


    sns.barplot(
        data=dfm, x="XGroup", y="value", order=order,
        hue="XGroup", legend=False, errorbar=None,
        alpha=ALPHA, ax=ax, palette=bar_palette,
    )

    # --- Individual animals as dots, colored by Sex, drawn above the bars ---
    sns.stripplot(
        data=dfm, x="XGroup", y="value", order=order,
        hue="HueGroup", hue_order=hue_levels,
        jitter=True, dodge=False, size=6,
        edgecolor="black", linewidth=1,
        palette=pal_dots, ax=ax, zorder=3, alpha=ALPHA,
    )
    # stripplot auto-attaches a legend to the axes; remove it, because the
    # composite figure carries ONE shared Sex legend built by the caller.
    if ax.legend_ is not None:
        ax.legend_.remove()

    # --- Single genotype p-value from the two-way ANOVA (matches L4 caption) ---
    # We report the XGroup (genotype) main effect p_x, NOT per-group t-tests
    # this reads e.g. "p = 0.002" / "p < 0.001"
    res = _twoway_anova_full(dfm)
    if res.get("ok") and np.isfinite(res.get("p_x", np.nan)):
        ax.text(
            0.5, 1.05, _fmt_p(res["p_x"]),
            transform=ax.transAxes, ha="center", va="top",
            fontsize=pval_fontsize, fontstyle="italic",
        )

    # --- Cosmetics: no title/xlabel, metric name on y, clean spines ---
    ax.set_title("")
    ax.set_xlabel(xlabel or "", fontsize=label_fontsize, )
    ax.set_ylabel(ylabel or variable, fontsize=label_fontsize)

    # tile the labels
    ax.tick_params(axis="x", labelrotation=45)
    for lbl in ax.get_xticklabels():
        lbl.set_ha("right")


    sns.despine(ax=ax)

    # Build (but do NOT place) the Sex legend proxies for the caller to use once.
    handles = []
    if len(hue_levels) >= 2:
        handles = [
            plt.Line2D([0], [0], marker="o", linestyle="None",
                       markerfacecolor=pal_dots[h], markeredgecolor="black",
                       label=str(h))
            for h in hue_levels
        ]
    return handles


def _fed_for_mouse(fed_list, metadata_df, mouse_id):
    """
    Return the FIRST FED session DataFrame whose filename maps (via metadata_df)
    to `mouse_id`, or None if not found. Used by Option 2 above to draw a mouse's
    trace directly rather than re-reading a saved PNG.

    Note: a mouse may have several sessions; this returns the first match. Pick a
    specific session upstream if you need a particular one.
    """
    if "Mouse_ID" not in metadata_df.columns or "filename" not in metadata_df.columns:
        return None
    # All filenames belonging to this mouse.
    files = set(
        metadata_df.loc[metadata_df["Mouse_ID"].astype(str) == str(mouse_id), "filename"]
    )
    if not files:
        return None
    for fed in fed_list:
        name = os.path.basename(str(getattr(fed, "name", "")))
        if name in files:
            return fed
    return None


def _panel_label(ax, letter, *, dx=-0.08, dy=1.08, fontsize=18):
    """
    Stamp a bold panel letter (e.g. "A") just outside the top-left corner of an
    Axes, in axes-fraction coords so it tracks the panel through any layout
    change. 
    dx/dy are nudges in axes fractions
    """
    ax.text(dx, dy, letter, transform=ax.transAxes,
            ha="right", va="bottom", fontsize=fontsize, fontweight="bold")

def _wrap_caption(text, fig_width_in, *, fontsize=14, left=0.1, right=0.9, char_w=0.5):
    """
    Wrap a caption string to fit within the figure width, given a font size for the caption. 
    This is a rough estimate for the L4 figure captions, which are often long and need to be 
    wrapped to avoid overflow.
    
    Returns: a single string with embedded newlines.
    """
    # char_w = mean glyph advance as a fraction of fontsize (pts). ~0.5 is a safe
    # over-estimate for DejaVu Sans, so lines err narrow rather than overflow.
    usable_pts = fig_width_in * 72 * (right - left)   # drawable width, 72 pt/in
    ncols = max(20, int(usable_pts / (char_w * fontsize)))  # char budget per line
    flat = " ".join(text.split())                     # drop any existing hard breaks
    return textwrap.fill(flat, width=ncols)