"""
Functions specificlly for bandit assay and plotting from a FED device
William B. Rubio
"""

# import dependancies
import os
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import re
import tqdm
import ipywidgets as widgets
from dataclasses import dataclass
#import matplotlib as mpl


# stats
import pingouin as pg
from statsmodels.formula.api import ols
import statsmodels.api as sm

# import cousins
from fedlib.fedutils.fedlog import status 
from fedlib.extracted import fed3bandit_extracted, fed3_loading, fed3_fedframe
from fedlib import fedassets
from fedlib.fedcore import core



#@@@@@@@@@@@@@@@@@@ GLOBAL VARIABLES @@@@@@@@@@@@@@@@@@#
# List of bandit meta columns that we are interested in preserving and acting upon
# currenly passed in as a global in this script but scope may change
BANDIT_META_COLS = ["Genotype", "Gene", "Strain", "Sex", "Diet", "Treatment", "Condition","Pellets","Litter", "Sire_Geno", "Dam_Geno",]

# Define exclusions for group plotting
exclude_lower = {"match_status"} # everything else is allowed

# Set the alpha for plots
ALPHA = 0.6  # apply to both bars and dots

# Define hue order priority
HUE_PRIORITY = ["Female", "Male", "F", "M", "Day", "Night", "Light", "Dark", "ALL", "UNASSIGNED"]

# for peak accuracy
TRIALS = 11 

#@@@@@@@@@@@@@@@@@@ Bandit Plotting @@@@@@@@@@@@@@@@@@#
### ------ General Helper functions ------- ###
def clean_key_filename_column(key_df):
    """
    ensure that the filename column in the meta data key file is normalized
    Arguments:
        key_df; Dataframe
            Metadatafile dataframe generated by key creation step
    Returns:
        key_df; Dataframe
            Dataframe with normalized "filename" column
    """
    key_df = key_df.copy().reset_index(drop=True)
    if 'filename' in key_df.columns:
        key_df['filename'] = key_df['filename'].astype(str).map(os.path.basename)
    return key_df


def _coerce_numeric_col(df, col, clip_upper=None, na_map=None):
    """
    This function will attempt to coerce columns that are numeric to a numeric typing
    Called in:
        _plot_file_core
    Arguments:
        df; Dataframe
            A FED dataframe
        col - Specified column for attempted coercion to numeric type
    """
    if col not in df.columns:
        return
    s = df[col]
    if na_map:
        s = s.replace(na_map)
    s = pd.to_numeric(s, errors='coerce')
    if clip_upper is not None:
        s.loc[s > clip_upper] = np.nan
    df[col] = s











### ------- Main Plotting Function ------ ###
def _plot_file_core(fed_list, metadata_df, root_path, dpi=150):
    """
    This function will take in a file index to create a switch bandit plot for a particular file.

    Has a mode for creating displays for the L4, this mode requires the input of a dataframe supplied later.

    Aguments:
        fed_list; List
            List contating multiple FED Dataframes  
        metadata_df - the metadata file that has been stiched together in previous step of the workflow
        root_path; string or Path object
            the root path defined where the data lives
        dpi; int, default 150
            resolution for saved pictures
    """

    status.step("Beginning to plot bandit assays")


    # intitate a empty list to capture the results
    saved_paths  = []

    # Create the directory that will be writen to
    out_dir = Path(root_path, "indv_bandit_plots")
    out_dir.mkdir(parents=True, exist_ok=True)
    
    
    # iterate through all the df's within the list 
    for fed in fed_list:
        df = fed.copy()
        full_name = getattr(df, 'name', f"File_{fed}")
        file_basename = os.path.basename(str(full_name))

        # Preserve original index once
        if "Original_Timestamp" not in df.columns:
            df["Original_Timestamp"] = df.index

        # Attach metadata by filename (matching already done upstream)
        meta_row = None
        if 'filename' in metadata_df.columns:
            mr = metadata_df.loc[metadata_df['filename'] == file_basename]
            if not mr.empty:
                meta_row = mr.iloc[0]
        if meta_row is not None:
            for col in meta_row.index:
                if col == 'filename':
                    continue
                if col not in df.columns:
                    df[col] = meta_row[col]
                else:
                    if pd.isna(df[col]).all() and pd.notna(meta_row[col]):
                        df[col] = meta_row[col]

        # Time + cleanup
        try:
            df['timestamp'] = pd.to_datetime(df.index)
        except Exception:
            df['timestamp'] = np.arange(len(df))

        _coerce_numeric_col(df, 'Poke_Time', clip_upper=2)
        _coerce_numeric_col(df, 'Retrieval_Time', na_map={"Timed_out": np.nan})

        if len(df) == 0:
            status.warn(f"[!] Empty dataframe for {file_basename}. Skipping plot.")
            #return None, None
            continue
        
        true_left = fed3bandit_extracted.true_probs(df, offset=5)[0]
        mouse_left = fed3bandit_extracted.binned_paction(df, window=10)


        # Plot
        fig, ax = plt.subplots(figsize=(10, 3))
        ax.plot(np.arange(len(true_left)), true_left, color="black", linewidth=2, alpha=0.5)

        color = "dodgerblue"
        if 'Sex' in df.columns and pd.notna(df['Sex']).any():
            try:
                color = "red" if str(df['Sex'].iloc[0]).strip().lower().startswith("f") else "dodgerblue"
            except Exception:
                pass

        
        ax.plot(np.arange(len(mouse_left)), mouse_left, color=color, linewidth=3, alpha=0.7)

        ax.set_ylabel("P(Left)")
        ax.set_xlabel("Trial")
        ax.set_yticks([1, 0.5, 0])

        # Title = Mouse_ID (fallback to filename)
        title_text = str(meta_row['Mouse_ID']) if (meta_row is not None and 'Mouse_ID' in meta_row and pd.notna(meta_row['Mouse_ID'])) else file_basename
        ax.set_title(title_text)

        sns.despine()
        plt.tight_layout()
        #plt.show()

        # suggest a base filename for saving
        safe_title = "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in title_text)
        suggested = f"{safe_title}_pLeft"

        out_path = out_dir / suggested
        
        
        fig.savefig(out_path, dpi=dpi, bbox_inches="tight")

        # Close the current figure to save memory
        plt.close(fig)

        saved_paths.append(out_path)
        status.ok(f"saved {out_path.name}")


    status.ok(f"Plots saved to: {out_dir} ")

    # return final results
    return saved_paths 




#@@@@@@@@@@@@@@@@@@ Build Bandit L3 @@@@@@@@@@@@@@@@@@#

### ------ General Helper functions ------ ###
def _clean_colname(c):
    """
    Cleans column name, called typiclly within a loop to clean all columnnames 
    Called by:
        build_bandit_metakey
    Argument:
        c; string
            string of column name
    """
    c = str(c).strip()
    c = c.replace("$", "")
    c = re.sub(r"\s+", "_", c)
    c = re.sub(r"_+", "_", c)
    return c


def _basename(pathlike) -> str:
    """
    Argument:
        pathlike; string
            string of path
    Returns:
        basename from a path
    """
    s = str(pathlike).replace("\\", "/")
    return s.split("/")[-1]

def _file_base_lower(pathlike):
    """
    Returns pathname to all lowercase
    
    Argument:
        pathlike; string
            string of path
    """
    return os.path.splitext(os.path.basename(str(pathlike)))[0].lower()


def _safe_col(df, candidates):
    norm = lambda s: str(s).strip().lower().replace('-', '_').replace(' ', '_')
    lmap = {norm(c): c for c in df.columns}
    for cand in candidates:
        key = norm(cand)
        if key in lmap:
            return lmap[key]
    return None


def _prep_events(df):
    ev_col = _safe_col(df, ["Event", "event"])
    if ev_col is None:
        return df.iloc[0:0].copy(), None
    return df[df[ev_col].isin(["Left", "Right", "Pellet"])].copy(), ev_col


def _get_timestamp_series(df, ts_col="MM:DD:YYYY hh:mm:ss"):
    if ts_col in df.columns:
        ts = pd.to_datetime(df[ts_col], format="%m:%d:%Y %H:%M:%S", errors="coerce")
        return pd.Series(ts, index=df.index)
    for cand in ["DateTime", "Datetime", "Timestamp", "timestamp", "datetime"]:
        if cand in df.columns:
            ts = pd.to_datetime(df[cand], errors="coerce")
            return pd.Series(ts, index=df.index)
    idx = df.index
    if isinstance(idx, pd.DatetimeIndex):
        return pd.Series(idx, index=df.index)
    return pd.to_datetime(pd.Series(idx, index=df.index), errors="coerce")


def _split_day_night(df, ts_col="MM:DD:YYYY hh:mm:ss"):
    """Day: 07:00–19:00; Night: otherwise."""
    ts = _get_timestamp_series(df, ts_col=ts_col)
    valid = ts.notna()
    hrs = ts.dt.hour
    day_mask = valid & (hrs >= 7) & (hrs < 19)
    night_mask = valid & ~day_mask
    return df.loc[day_mask], df.loc[night_mask]


def compute_withinbout_lose_shift(c_df, max_gap_s=120):
    try:
        if "Event" not in c_df.columns or len(c_df) < 2:
            return np.nan
        events = c_df["Event"].to_numpy()
        times = _get_timestamp_series(c_df).to_numpy()
        total = shifted = 0
        for i in range(len(events) - 1):
            curr_evt, next_evt = events[i], events[i + 1]
            if curr_evt not in ("Left", "Right"):
                continue
            dt_s = (times[i + 1] - times[i]) / np.timedelta64(1, "s")
            if np.isnan(dt_s) or dt_s > max_gap_s:
                continue
            if next_evt == "Pellet":
                continue
            if next_evt in ("Left", "Right"):
                total += 1
                if next_evt != curr_evt:
                    shifted += 1
        return (shifted / total) if total > 0 else np.nan
    except Exception:
        return np.nan
    

def compute_withinbout_win_stay(c_df, max_gap_s=120):
    try:
        if "Event" not in c_df.columns or len(c_df) < 3:
            return np.nan
        events = c_df["Event"].to_numpy()
        times = _get_timestamp_series(c_df).to_numpy()
        pellet_idx = [i for i in range(1, len(events) - 1) if events[i] == "Pellet"]
        total = same = 0
        for i in pellet_idx:
            prev_event, next_event = events[i - 1], events[i + 1]
            dt_s = (times[i + 1] - times[i]) / np.timedelta64(1, "s")
            if not np.isnan(dt_s) and dt_s <= max_gap_s:
                if prev_event in ("Left", "Right") and next_event in ("Left", "Right"):
                    total += 1
                    if next_event == prev_event:
                        same += 1
        return (same / total) if total > 0 else np.nan
    except Exception:
        return np.nan
    

def compute_peak_accuracy(c_df):
    try:
        rev_avg = fed3bandit_extracted.reversal_peh(c_df, (-10, 10), True)
        if len(rev_avg) == 0:
            return np.nan
        return float(np.mean(rev_avg[:10])) if len(rev_avg) >= 10 else float(np.mean(rev_avg))
    except Exception:
        return np.nan


def estimate_daily_pellets(c_df):
    ts = _get_timestamp_series(c_df)
    valid_ts = ts.dropna()
    if valid_ts.size < 2:
        return np.nan
    duration_hours = (valid_ts.max() - valid_ts.min()).total_seconds() / 3600.0
    if duration_hours <= 0:
        return np.nan

    pellet_events = np.nan
    if "Pellet_Count" in c_df.columns and c_df["Pellet_Count"].notna().any():
        pc = pd.to_numeric(c_df["Pellet_Count"], errors="coerce")
        if pc.notna().any():
            diffs = pc.diff().fillna(0).clip(lower=0)
            pellet_events = float(diffs.sum())
            if pellet_events == 0 and pc.iloc[-1] >= pc.iloc[0]:
                pellet_events = float(pc.iloc[-1] - pc.iloc[0])
    if (pd.isna(pellet_events)) and ("Event" in c_df.columns):
        pellet_events = float((c_df["Event"] == "Pellet").sum())

    if pd.isna(pellet_events):
        return np.nan
    return (pellet_events / duration_hours) * 24.0


def compute_inactive_pokes(c_df):
    try:
        if not all(col in c_df.columns for col in ['Event', 'High_prob_poke']):
            return np.nan
        pokes = c_df[c_df['Event'].isin(['Left', 'Right'])].copy()
        if pokes.empty:
            return 0
        inactive = pokes[pokes['Event'] != pokes['High_prob_poke']]
        return len(inactive)
    except Exception:
        return np.nan


def compute_active_pokes(c_df):
    try:
        if not all(col in c_df.columns for col in ['Event', 'High_prob_poke']):
            return np.nan
        pokes = c_df[c_df['Event'].isin(['Left', 'Right'])].copy()
        if pokes.empty:
            return 0
        active = pokes[pokes['Event'] == pokes['High_prob_poke']]
        return len(active)
    except Exception:
        return np.nan
    

### ------ Create bandit firendly key ------ ### 
def build_bandit_metakey(key_df):
    """
    Crops the metadatakey for the bandit analtsis workflow.
    Argument:
        key_df; Dataframe
            A dataframe contating meta information of the mice assayed via a FED (bandit) device.
    Returns:
        md; Dataframe
            Cropped version of ingested dataframe
    """
    metadata_df = key_df.copy().reset_index(drop=True)
    # Clean every column name
    metadata_df.columns = [_clean_colname(c) for c in metadata_df.columns]
    
    if "filename" in metadata_df.columns:
        metadata_df["filename"] = metadata_df["filename"].astype(str).map(os.path.basename).map(_basename)
    if "Mouse_ID" in metadata_df.columns:
        metadata_df["Mouse_ID"] = metadata_df["Mouse_ID"].astype(str).str.strip()
    
    
    
    lower_map = {c.lower(): c for c in metadata_df.columns}
    rename_map = {}
    for w in BANDIT_META_COLS:
        c = lower_map.get(w.lower(), None)
        if c is not None and c != w:
            rename_map[c] = w
    metadata_df = metadata_df.rename(columns=rename_map)
    
    merge_cols = [c for c in ["filename", "Mouse_ID"] if c in metadata_df.columns]
    naming_cols = [c for c in ["Session_type", "Gene_ID", "Strain_ID"] if c in metadata_df.columns]
    keep_cols = list(dict.fromkeys(merge_cols + [c for c in BANDIT_META_COLS if c in metadata_df.columns] + naming_cols))
    metadata_df = metadata_df.loc[:, keep_cols].copy()
    
    md = metadata_df.copy()
    if "filename" in md.columns:
        md["filename"] = md["filename"].astype(str).map(_basename)
    if "Mouse_ID" in md.columns:
        md["Mouse_ID"] = md["Mouse_ID"].astype(str).str.strip()

    return md


def pick_match_method(md, match_mode=None):
    """
    Picks what the id key column is from the metadata df
    Argument:
        md; Dataframe
            meta dataframe that contatins cropped bandit key created by build_bandit_metakey
        match_mode; str, default None
            accepts string argument specifying what column will be used as the id column. should be either mouse_id or filename
    Returns:
        id_col; string
            String detailing what column will serve as the key column to link both metadata and metric files
        other_id; string
            String detailing fallback key column to link metadata and metrics dataframes
    """
    
    if match_mode == 'filename':
        id_col = 'filename'
    elif match_mode == 'mouse_id':
        id_col = 'Mouse_ID'
    else:
        id_col = 'Mouse_ID' if 'Mouse_ID' in md.columns else 'filename'

    other_id = "Mouse_ID" if id_col == "filename" else "filename"

    return id_col, other_id


### --- crunch the numbers --- ###
def compute_bandit_metrics(fed_list, md, id_col="Mouse_ID"):
    """
    Computes the metrics from the badnit tasks
    Arguments:
        fed_list; List
            List contating multiple FED Dataframes
        md; Dataframe
            meta dataframe that contatins cropped bandit key created by build_bandit_metakey   
        id_col; String, default "Mouse_ID"
            String detailing what column will serve as the key column to link both metadata and metric files
    Returns:
        Banditmetrics; Dataframe
            Dataframe containing aggragate metrics from all mice for Bandit assays
    """

    status.step("Computing Bandit metrics")

    rows = []

    for idx in tqdm.tqdm(range(len(fed_list))):
        c_df = fed_list[idx]
        file_name = _basename(getattr(c_df, "name", f"File_{idx}"))
        d, ev = _prep_events(c_df)


        if ev is None or d.empty:
            pellets = left = right = lwp = 0
            rt_med = ipi_med = pt_med = np.nan
        else:
            pellets = int((d[ev] == "Pellet").sum())
            left    = int((d[ev] == "Left").sum())
            right   = int((d[ev] == "Right").sum())
            lwp     = int((c_df[ev] == "LeftWithPellet").sum()) if ev in c_df.columns else 0

        try:
            pre_acc_all = compute_peak_accuracy(c_df)
            clean_retrieval_time = pd.to_numeric(c_df.get("Retrieval_Time", pd.Series(dtype=float)), errors="coerce")
            clean_poke_time = pd.to_numeric(c_df.get("Poke_Time", pd.Series(dtype=float)), errors="coerce")
            clean_poke_time = clean_poke_time[clean_poke_time > 0]

            # Retrieve weight from Key_Df/metadata_df
            weight_val = np.nan
            if id_col in md.columns:
                # Attempt to find the metadata row for this specific session
                # First try to match by filename if possible, then by Mouse_ID if it exists
                meta_match = md.loc[md['filename'] == file_name]
                if meta_match.empty and 'Mouse_ID' in md.columns:
                    # If we can't match filename directly, try to infer Mouse_ID from the filename
                    known_ids = md['Mouse_ID'].dropna().unique().tolist()
                    base_lower = file_name.lower()
                    hits = [mid for mid in known_ids if str(mid).lower() in base_lower]
                    if hits:
                        best_hit = max(hits, key=len)
                        meta_match = md.loc[md['Mouse_ID'] == best_hit]

                if not meta_match.empty and 'Weight5_Friday' in meta_match.columns:
                    weight_val = pd.to_numeric(meta_match['Weight5_Friday'], errors='coerce').mean()

            row = {
                "filename": file_name,
                "PeakAccuracy": pre_acc_all,
                "Total_pellets": fed3bandit_extracted.count_pellets(c_df),
                "Total_pokes": fed3bandit_extracted.count_pokes(c_df),
                "PokesPerPellet": fed3bandit_extracted.pokes_per_pellet(c_df),
                "RetrievalTime": clean_retrieval_time.median() if not clean_retrieval_time.empty else np.nan,
                "PokeTime": clean_poke_time.median() if not clean_poke_time.empty else np.nan,
                "Win-stay": compute_withinbout_win_stay(c_df),
                "Lose-shift": compute_withinbout_lose_shift(c_df),
                "Daily_Pellets": estimate_daily_pellets(c_df),
                "Inactive_Pokes": compute_inactive_pokes(c_df),
                "Active_Pokes": compute_active_pokes(c_df),
                "Left Poke with Pellet": lwp,
                "Right_Poke": right,
                "Weight": weight_val
            }
        except Exception as e:
            status.fail(f"Failed to compute OVERALL metrics for {file_name} (idx {idx}): {e}")
            continue

        try:
            day_df, night_df = _split_day_night(c_df, ts_col="MM:DD:YYYY hh:mm:ss")
            row.update({
                "PeakAccuracy_Day": compute_peak_accuracy(day_df),
                "PeakAccuracy_Night": compute_peak_accuracy(night_df),
                "Win-stay_Day": compute_withinbout_win_stay(day_df),
                "Win-stay_Night": compute_withinbout_win_stay(night_df),
                "Lose-shift_Day": compute_withinbout_lose_shift(day_df),
                "Lose-shift_Night": compute_withinbout_lose_shift(night_df),
            })
        except Exception as e:
            status.fail(f"Failed to compute DAY/NIGHT metrics for {file_name} (idx {idx}): {e}")

        rows.append(row)

    Banditmetrics = pd.DataFrame(rows)
    if Banditmetrics.empty:
        display(HTML("<b style='color:#b00'>No files to analyze.</b>"))
        raise SystemExit
    
    status.ok("metrics computed:")
    status.preview(Banditmetrics, msg="metadata key after build_bandit_metakey")

    return Banditmetrics



### ------ Attach metadata to bandit metrics ------ ###
def attach_meta_bm(bm_df, md, id_col):
    """
    Attaches cropped bandit metadata dataframe to the aggragated bandit metric dataframe

    Arguments:
        bm; Dataframe
            Dataframe containing aggragated bandit metrics for multiple mice in a Bandit assay by a FED device
        md; Dataframe
            meta dataframe that contatins cropped bandit key created by build_bandit_metakey
        id_col; String, default "Mouse_ID"
            String detailing what column will serve as the key column   
    Returns:
        bm_md; Dataframe    
            Dataframe containing aggregated metrics with metadata
    """

    status.step("Attaching metadata to bandit metrics")
    bm = bm_df.copy()

    if "filename" in md.columns and "Mouse_ID" in md.columns:
        mouse_map = md.dropna(subset=["filename"]).drop_duplicates("filename").set_index("filename")["Mouse_ID"]
        bm["Mouse_ID"] = bm["filename"].map(mouse_map)

        if bm["Mouse_ID"].isna().any():
            known_ids = md["Mouse_ID"].dropna().unique().tolist()
            for i, r in bm.loc[bm["Mouse_ID"].isna()].iterrows():
                base = _file_base_lower(r["filename"])
                hits = [mid for mid in known_ids if str(mid).lower() in base]
                if len(hits) == 1:
                    bm.at[i, "Mouse_ID"] = hits[0]
                elif len(hits) > 1:
                    longest = max(len(str(h)) for h in hits)
                    best = [h for h in hits if len(str(h)) == longest]
                    if len(best) == 1:
                        bm.at[i, "Mouse_ID"] = best[0]

    if (id_col == "Mouse_ID") and ("Mouse_ID" in bm.columns) and ("Mouse_ID" in md.columns) and bm["Mouse_ID"].notna().any():
        md_unique = md.drop_duplicates(subset=["Mouse_ID"], keep="first")
        bm_md = bm.merge(md_unique, on="Mouse_ID", how="left", suffixes=("", "_md"))
    else:
        if "filename" not in md.columns:
            raise ValueError("metadata_df has no 'filename' column, but filename is needed for this mode.")
        md_unique = md.drop_duplicates(subset=["filename"], keep="first")
        bm_md = bm.merge(md_unique, on="filename", how="left", suffixes=("", "_md"))

    status.ok("metadata attached")
    status.preview(bm_md, msg="merged bandit metric dataframe")
    return bm_md



### ------ Define session type suffixing ------ ###
def output_l3(bm_md, id_col, other_id, root_path):
    """
    Arguemnts:
        bm_md; Dataframe
            Dataframe containing aggregated metrics with metadata
        id_col; string
            String detailing what column will serve as the key column to link both metadata and metric files
        other_id; string
            String detailing fallback key column to link metadata and metrics dataframes
    """

    status.step("Preparing L3")

    # prepare the L3 Directory for population
    status.sub("Creating L3 directory")
    out_dir = Path(root_path, "L3")
    out_dir.mkdir(parents=True, exist_ok=True)
    status.ok("L3 directory created")

    bm = bm_md.copy()

    metric_cols = [
        "Win-stay", "Lose-shift", "PeakAccuracy", "Total_pellets", "Total_pokes",
        "PokesPerPellet", "RetrievalTime", "PokeTime", "Daily_Pellets",
        "Inactive_Pokes", "Active_Pokes", "Weight",
        "Win-stay_Day", "Win-stay_Night", "Lose-shift_Day", "Lose-shift_Night",
        "PeakAccuracy_Day", "PeakAccuracy_Night","Left Poke with Pellet","Right_Poke",
    ]

    if "Session_type" in bm.columns:
        session_series = bm["Session_type"].astype(str).str.strip()
    else:
        sess_map = {
            _basename(getattr(_sessions[i], "name", f"File_{i}")):
            (_sessions[i].attrs.get("Session_type") or "Unknown")
            for i in range(len(_sessions))
        }
        session_series = bm["filename"].map(sess_map).fillna("Unknown").astype(str)

    session_series = session_series.str.replace(r"\s+", "_", regex=True)
    bm["_Session_type_for_csv"] = session_series

    def with_session_suffix_for_csv(df, metrics=metric_cols, session_col="_Session_type_for_csv"):
        df = df.copy()
        for m in metrics:
            if m not in df.columns:
                continue
            for sess in df[session_col].dropna().unique():
                mask = df[session_col] == sess
                col_name = f"{m}_{sess}"
                if col_name not in df.columns:
                    df[col_name] = np.nan
                df.loc[mask, col_name] = df.loc[mask, m]
            df.drop(columns=[m], inplace=True)
        return df.drop(columns=[session_col])

    Banditmetrics_merged = bm.copy()
    Banditmetrics_csv = with_session_suffix_for_csv(Banditmetrics_merged)

    ### Prepare final export columns
    def _metric_match(col: str) -> bool:
        return any(col.startswith(base + "_") for base in metric_cols)

    metric_keep = [c for c in Banditmetrics_csv.columns if _metric_match(c)]
    if not metric_keep:
        raise RuntimeError("No session-suffixed metric columns matched; check 'metric_cols'.")

    meta_keep = [c for c in BANDIT_META_COLS if c in Banditmetrics_csv.columns]

    drop_cols = []
    if other_id in Banditmetrics_csv.columns:
        drop_cols.append(other_id)
    for c in ["File", "FileIndex"]:
        if c in Banditmetrics_csv.columns:
            drop_cols.append(c)

    Banditmetrics_csv = Banditmetrics_csv.drop(columns=drop_cols, errors="ignore")

    cols_out = [id_col] + meta_keep + metric_keep
    cols_out = [c for c in cols_out if c in Banditmetrics_csv.columns]
    Banditmetrics_csv = Banditmetrics_csv.loc[:, cols_out].copy()

    ### get name of file
    example = Banditmetrics_merged.iloc[0]

    strain_name = str(example.get("Gene", example.get("Strain", "NA"))).replace(" ", "_")
    strain_num_raw = example.get("Gene_ID", example.get("Strain_ID", "NA"))
    try:
        strain_num = f"{int(strain_num_raw):03d}"
    except Exception:
        strain_num = str(strain_num_raw).zfill(3)

    task_name = str(example.get("Session_type", "Unknown")).replace(" ", "_")
    fname = f"{strain_name}_{strain_num}_{task_name}_L3.csv"

    # Return 
    status.ok("L3 prepared")
    status.preview(bm_md, msg="L3 Dataframe")

    out_path = out_dir / fname
    Banditmetrics_csv.to_csv(out_path, index=False)

    return(Banditmetrics_csv)




#@@@@@@@@@@@@@@@@@@ Determine groups for plotting later @@@@@@@@@@@@@@@@@@#
# helps to determine grouping for downstream plotting


### ------ General Helper functions ------ ###
def build_mapping(md, ordered_cols):
    """
    Arguments:
        md; Dataframe
            meta dataframe that contatins cropped bandit key created by build_bandit_metakey
    """
    _meta = md.copy()
    #_meta = metadata_df.copy()
    
    _meta["filename"] = _build_file_column(_meta)
    _meta["Group"] = _meta.apply(lambda r: _build_group_row(r, ordered_cols), axis=1)
    mapping = (
        _meta[["filename", "Group"]]
        .dropna(subset=["filename"])
        .drop_duplicates()
        .sort_values(["Group", "filename"])
        .reset_index(drop=True)
    )
    return mapping


def _build_file_column(df):
    if "filename" in df.columns:
        return df["filename"].apply(lambda p: os.path.basename(str(p)))
    if "FED3_from_file" in df.columns and "Date_from_file" in df.columns:
        return "FED" + df["FED3_from_file"].astype(str) + "_" + df["Date_from_file"].astype(str)
    if "FED3_from_file" in df.columns:
        return "FED" + df["FED3_from_file"].astype(str)
    return df.index.astype(str)


def _build_group_row(row, ordered_cols):
    if not ordered_cols:
        return "ALL"
    return " | ".join(_norm_val(row[c]) for c in ordered_cols)


def _norm_val(x):
    s = str(x).strip()
    if s == "" or s.lower() in {"nan", "none"}:
        return "UNK"
    return s.upper()


### ------ Main functions ------ ###

def build_group_selections(md, right_x = ["Genotype"], right_hue = ["Sex"]):
    """
    Arguments:
        md; Dataframe
            meta dataframe that contatins cropped bandit key created by build_bandit_metakey
        right_x; List
            List of metadata columns selected to define main plotting purposes
        right_hue; List
            List of metadata columns selected to define supplementary plotting purposes

    Returns:
        mapping_both; Dataframe
            Dataframe mapping filenames what category the file is based on mapping groupings.
    """

    status.step("Building group selection dataframe")
    
    ordered_cols_x = list(right_x)
    ordered_cols_hue = list(right_hue)
    #ordered_cols_x = list(right_x.options)
    #ordered_cols_hue = list(right_hue.options)

    mapping_x = build_mapping(md, ordered_cols_x)
    mapping_hue = build_mapping(md, ordered_cols_hue)

    _meta = md.copy()
    #_meta = metadata_df.copy()
    
    _meta["filename"] = _build_file_column(_meta)
    _meta["XGroup"] = _meta.apply(lambda r: _build_group_row(r, ordered_cols_x), axis=1)
    _meta["HueGroup"] = _meta.apply(lambda r: _build_group_row(r, ordered_cols_hue), axis=1)
    mapping_both = (
        _meta[["filename", "XGroup", "HueGroup"]]
        .dropna(subset=["filename"])
        .drop_duplicates()
        .sort_values(["XGroup", "HueGroup", "filename"])
        .reset_index(drop=True)
    )

    globals()['files_to_group_x'] = mapping_x.copy()
    globals()['files_to_group_hue'] = mapping_hue.copy()
    globals()['files_to_group_both'] = mapping_both.copy()
    globals()['selected_group_cols_x'] = ordered_cols_x.copy()
    globals()['selected_group_cols_hue'] = ordered_cols_hue.copy()

    status.ok(f"X-axis grouping (hierarchy): {ordered_cols_x if ordered_cols_x else ["ALL"]}")
    status.ok(f"Total unique files (X map): {mapping_x['filename'].nunique()}")
    #display(widgets.HTML("<b>X-group summary</b>"))
    status.table((mapping_x.groupby("Group", dropna=False)["filename"]
             .nunique().sort_values(ascending=False)
             .rename("UniqueFiles").to_frame()))

    status.ok(f"Hue grouping: {ordered_cols_hue if ordered_cols_hue else ["ALL"]}")
    status.ok(f"Total unique files (Hue map): {mapping_hue['filename'].nunique()}")
    #display(widgets.HTML("<b>Hue-group summary</b>"))
    status.table((mapping_hue.groupby("Group", dropna=False)["filename"]
             .nunique().sort_values(ascending=False)
             .rename("UniqueFiles").to_frame()))
    #print("\nCombined mapping available as `files_to_group_both` (filename, XGroup, HueGroup)")

    status.ok("Grouping dataframe built")

    return mapping_both





def merge_group_selections(bm, mapping_both):
    """
    Attempts to merge in grouping selections to the bandit metrics for plotting purposes later

    Arguments:
        bm; Dataframe
            Dataframe merged with metadata; not L3 dataframe
    """

    status.step("Merging group df and metric df")

    if ("XGroup" not in bm.columns) or ("HueGroup" not in bm.columns):
        if 'files_to_group_both' in globals() and files_to_group_both is not None and not files_to_group_both.empty:
            m = files_to_group_both.copy()
            m_src = _src_name(m)
            if m_src is None:
                raise RuntimeError("Grouping table must include 'filename' (or legacy 'File').")
            m["file_base"]  = m[m_src].apply(_basename_col)
            bm["file_base"] = bm["filename"].apply(_basename_col)
            bm = bm.merge(m[["file_base","XGroup","HueGroup"]], on="file_base", how="left").drop(columns=["file_base"])
            bm["XGroup"]   = bm["XGroup"].fillna("UNASSIGNED")
            bm["HueGroup"] = bm["HueGroup"].fillna("UNASSIGNED")
        elif 'files_to_group' in globals() and files_to_group is not None and not files_to_group.empty:
            m = files_to_group.copy()
            m_src = _src_name(m)
            if m_src is None:
                raise RuntimeError("Grouping table must include 'filename' (or legacy 'File').")
            m["file_base"]  = m[m_src].apply(_basename_col)
            bm["file_base"] = bm["filename"].apply(_basename_col)
            bm = bm.merge(m[["file_base","Group"]], on="file_base", how="left").drop(columns=["file_base"])
            bm["Group"] = m["Group"].fillna("UNASSIGNED")
            bm["XGroup"] = bm["Group"]
            bm["HueGroup"] = "ALL"
        else:
            raise RuntimeError("Missing X/Hue mapping. Run the grouping widget (Build Groups) first.")
        
        status.ok("Group and Metric dataframe merged")
        return bm







#@@@@@@@@@@@@@@@@@@ Plot groups @@@@@@@@@@@@@@@@@@#

### ------ General Helper functions ------ ###
def _basename_col(s):
    return os.path.basename(str(s))

def _src_name(df):
    if "filename" in df.columns:
        return "filename"
    return None

def _hier_sort_key(g):
    lv = _x_levels(g)
    norm = []
    for tok in lv:
        is_blank = 1 if _is_unassigned_token(tok) else 0
        norm.append((is_blank, str(tok).upper()))
    wt_present = any(_is_wt_group(tok) for tok in lv) or _is_wt_group(g)
    wt_rank = 0 if wt_present else 1
    return (wt_rank,) + tuple(norm) + (str(g).upper(),)

def _x_levels(xname):
    s = str(xname)
    parts = [p.strip() for p in s.split("|")]
    wanted = globals().get("selected_group_cols_x", None)
    if isinstance(wanted, (list, tuple)) and wanted:
        if len(parts) < len(wanted):
            parts += [""] * (len(wanted) - len(parts))
        else:
            parts = parts[:len(wanted)]
    return parts

def _is_unassigned_token(s):
    return (str(s).strip().upper() in {"", "UNASSIGNED", "NONE", "NA", "N/A"})

def _is_wt_group(g):
    u = str(g).strip().upper()
    tokens = [t for t in re.split(r'[^A-Z0-9]+', u) if t]
    WT_ALIASES = {"WT", "WILDTYPE", "CONTROL", "CTRL"}
    return any(t in WT_ALIASES for t in tokens)


def melt_bandit(bm_l3, x_group = "Genotype", hue_group = "Sex"):
    """
    Melt the bandit metrics from wide to long

    Arguments:
        bm_l3; Dataframe
            Bandit metric L3 file
    Returns:
        long_df; Dataframe
            Bandit metric dataframe in a long format
    """

    status.step("Melting bandit L3 to long format")
    bm = bm_l3.copy()

    base_metric_names = [
    "Win-stay","Lose-shift","PeakAccuracy",
    "Total_pellets","Total_pokes","PokesPerPellet", "Weight",
    "RetrievalTime","PokeTime","Daily_Pellets", "Left Poke with Pellet", "Right_Poke", "Inactive_Pokes", "Active_Pokes",
    "Win-stay_Day","Win-stay_Night","Lose-shift_Day","Lose-shift_Night",
    "PeakAccuracy_Day","PeakAccuracy_Night",
    ]

    metric_cols = []

    # find all non meta feature columns
    for c in bm.columns:
        if pd.api.types.is_numeric_dtype(bm[c]):
            for base in base_metric_names:
                if c == base or c.startswith(base + "_"):
                    metric_cols.append(c); break
    seen = set(); metric_cols = [c for c in metric_cols if not (c in seen or seen.add(c))]
    if not metric_cols:
        raise RuntimeError("No numeric metric columns found among expected Bandit metrics.")

    candidate_id_vars = ["Genotype","Sex","Strain","Start_Date","flename","Mouse_ID","Session_type","XGroup","HueGroup"]
    id_vars = [c for c in candidate_id_vars if c in bm.columns]
    for need in ["XGroup","HueGroup","filename"]:
        if need not in id_vars: id_vars.append(need)

    long_df = pd.melt(
        bm,
        id_vars=id_vars,
        value_vars=metric_cols,
        var_name="variable",
        value_name="value"
    )

    status.ok("bandit melted")
    return long_df




def define_aesthetics(long_df):
    """
    uses a very hacky solution of relying on widget package to pass structured strings
    Arguments:
        long_df; Dataframe
            Long format dataframe of metrics 
    Returns:
        x_checks;
        x_colors; 
        ordered_x;
    """
    named_defaults = [
    "dodgerblue", "red", "green", "orange", "purple",
    "brown", "pink", "gray", "olive", "cyan"]

    # Build the ordered list of XGroup levels
    all_x_groups = long_df["XGroup"].dropna().unique().tolist()
    if not all_x_groups:
        raise RuntimeError("No XGroup values found – check that the grouping step ran correctly.")

    ordered_x = _order_x_groups(all_x_groups)

    x_checks, x_colors = {}, {}
    group_rows = []
    for i, g in enumerate(ordered_x):
        chk = widgets.Checkbox(value=True, description=g, indent=False, layout=widgets.Layout(width="260px"))
        col = widgets.Text(value=named_defaults[i % len(named_defaults)],
                        layout=widgets.Layout(width="120px"))
        x_checks[g] = chk
        x_colors[g] = col
        # more compact row
        group_rows.append(widgets.HBox([chk, widgets.Label(""), col],
                                    layout=widgets.Layout(align_items="center", height="28px")))

    picker = widgets.VBox(group_rows, layout=widgets.Layout(gap="2px"))

    btn_all  = widgets.Button(description="Select all", layout=widgets.Layout(width="140px"))
    btn_none = widgets.Button(description="Clear", layout=widgets.Layout(width="140px"))
    def _set_all(val):
        for c in x_checks.values(): c.value = val
    btn_all.on_click(lambda _: _set_all(True))
    btn_none.on_click(lambda _: _set_all(False))

    # scrollable container for the (possibly long) group list
    picker_container = widgets.Box([picker],
        layout=widgets.Layout(overflow="auto", max_height="420px",
                            border="1px solid #ddd", padding="6px", width="360px"))

    left_col = widgets.VBox([
        widgets.HTML("<b>Groups & Colors</b>"),
        widgets.HBox([btn_all, btn_none], layout=widgets.Layout(gap="8px")),
        picker_container
    ], layout=widgets.Layout(width="380px"))

    return x_checks, x_colors, ordered_x



### ------ Stats Helper functions ------ ###
# Pingouin p-value helper
def _pg_get_pval(pg_res):
    """
    Robustly extract p-value from a Pingouin result DataFrame.
    Works across versions that rename p-value columns.
    """
    if pg_res is None:
        return np.nan
    if not isinstance(pg_res, pd.DataFrame) or pg_res.empty:
        return np.nan

    candidates = [
        "p-val", "p_val", "pval", "pvalue", "p_value",
        "p-unc", "p_unc", "p", "P-val", "P_val"
    ]
    for c in candidates:
        if c in pg_res.columns:
            try:
                return float(pg_res[c].values[0])
            except Exception:
                return np.nan

    raise KeyError(f"Pingouin result has no known p-value column. Columns: {pg_res.columns.tolist()}")


def _stats_text(dfm, x_label, hue_label, *, mode="ref", ref_group=None, pair_list=None):
    df = dfm.dropna(subset=["value"]).copy()
    g_n = df["XGroup"].nunique(dropna=True)
    h_n = df["HueGroup"].nunique(dropna=True)

    if mode == "pairs" and pair_list:
        lines = ["Selected pairwise ANOVA tests:"]
        for a,b in pair_list:
            sub = df[df["XGroup"].isin([a,b])]
            res = _anova_subset(sub)
            if not res["ok"]:
                lines.append(f"{a} vs {b}: {res['err'] or 'failed'}"); continue
            if res["n_h"] >= 2:
                lines.append(
                    f"{a} vs {b} (Two-way: {x_label}, {hue_label})  "
                    f"{x_label}: {_fmt_p(res['p_x'])} | {hue_label}: {_fmt_p(res['p_h'])} | "
                    f"{x_label}×{hue_label}: {_fmt_p(res['p_int'])}"
                )
            else:
                lines.append(f"{a} vs {b} (One-way {x_label}): {_fmt_p(res['p_x'])}")
        return "\n".join(lines)

    def fmt(p): return _fmt_p(p)
    if g_n == 2 and h_n <= 1:
        g1, g2 = sorted(df["XGroup"].unique())
        v1 = df[df["XGroup"] == g1]["value"].dropna()
        v2 = df[df["XGroup"] == g2]["value"].dropna()
        if len(v1) > 1 and len(v2) > 1:
            p = _pg_get_pval(pg.ttest(v1, v2, paired=False))
            return f"t-test ({x_label}): {fmt(p)}\n{g1} vs {g2}"
        return "t-test: not enough data"

    if g_n >= 2 and h_n >= 2:
        try:
            model = ols('value ~ C(XGroup) + C(HueGroup) + C(XGroup):C(HueGroup)', data=df).fit()
            an = sm.stats.anova_lm(model, typ=2)
            return (
                "Two-way ANOVA\n"
                f"{x_label}: {fmt(float(an.loc['C(XGroup)','PR(>F)']))}\n"
                f"{hue_label}: {fmt(float(an.loc['C(HueGroup)','PR(>F)']))}\n"
                f"{x_label}×{hue_label}: {fmt(float(an.loc['C(XGroup):C(HueGroup)','PR(>F)']))}"
            )
        except Exception as e:
            return f"ANOVA failed: {e}"

    if g_n >= 2:
        try:
            model = ols('value ~ C(XGroup)', data=df).fit()
            return f"One-way ANOVA ({x_label}): {fmt(float(model.f_pvalue))}"
        except Exception as e:
            return f"One-way ANOVA failed: {e}"
    return "Too few groups for stats"

def _fmt_p(p):
    if not np.isfinite(p): return "n/a"
    return f"p = {p:.3f}" if p >= 0.001 else "p < 0.001"

def _anova_subset(df):
    """
    If >=2 Hue levels: two-way ANOVA (XGroup, HueGroup, interaction)
    Else: one-way ANOVA (XGroup).
    """
    out = {"p_x": np.nan, "p_h": np.nan, "p_int": np.nan, "n_h": 0, "ok": False, "err": None}
    d = df.dropna(subset=["value","XGroup"])
    if d.empty or d["XGroup"].nunique() < 2:
        out["err"] = "Too few groups"; return out
    n_h = d["HueGroup"].nunique(dropna=True); out["n_h"] = n_h
    try:
        if n_h >= 2:
            model = ols('value ~ C(XGroup) + C(HueGroup) + C(XGroup):C(HueGroup)', data=d).fit()
            an = sm.stats.anova_lm(model, typ=2)
            out["p_x"]   = float(an.loc['C(XGroup)','PR(>F)'])
            out["p_h"]   = float(an.loc['C(HueGroup)','PR(>F)'])
            out["p_int"] = float(an.loc['C(XGroup):C(HueGroup)','PR(>F)'])
            out["ok"] = True
        else:
            model = ols('value ~ C(XGroup)', data=d).fit()
            out["p_x"] = float(model.f_pvalue); out["ok"] = True
    except Exception as e:
        out["err"] = str(e)
    return out



def _fmt_p_num(p):
    if p is None or (isinstance(p, float) and (not np.isfinite(p))):
        return "n/a"
    p = float(p)
    return f"{p:.4f}" if p >= 0.0001 else "<0.0001"

def _fmt_F(df_num, df_den, F):
    if df_num is None or df_den is None or F is None:
        return "n/a"
    if not np.isfinite(F):
        return "n/a"
    return f"F({int(df_num)}, {int(df_den)}) = {float(F):.3f}"

def _twoway_anova_full(df):
    """
    Returns dict with full ANOVA stats including df for F.
    If HueGroup has <2 levels -> one-way (XGroup only).
    """
    d = df.dropna(subset=["value","XGroup"]).copy()
    if d.empty or d["XGroup"].nunique() < 2:
        return {"ok": False, "err": "Too few groups"}

    n_h = d["HueGroup"].nunique(dropna=True) if "HueGroup" in d.columns else 0

    try:
        if n_h >= 2:
            model = ols("value ~ C(XGroup) + C(HueGroup) + C(XGroup):C(HueGroup)", data=d).fit()
            an = sm.stats.anova_lm(model, typ=2)
            df_den = int(model.df_resid)

            return {
                "ok": True,
                "test": "Two-way ANOVA",

                "F_x": float(an.loc["C(XGroup)", "F"]),
                "df_x_num": int(an.loc["C(XGroup)", "df"]),
                "df_x_den": df_den,
                "p_x": float(an.loc["C(XGroup)", "PR(>F)"]),

                "F_h": float(an.loc["C(HueGroup)", "F"]),
                "df_h_num": int(an.loc["C(HueGroup)", "df"]),
                "df_h_den": df_den,
                "p_h": float(an.loc["C(HueGroup)", "PR(>F)"]),

                "F_int": float(an.loc["C(XGroup):C(HueGroup)", "F"]),
                "df_int_num": int(an.loc["C(XGroup):C(HueGroup)", "df"]),
                "df_int_den": df_den,
                "p_int": float(an.loc["C(XGroup):C(HueGroup)", "PR(>F)"]),
            }

        else:
            model = ols("value ~ C(XGroup)", data=d).fit()
            an = sm.stats.anova_lm(model, typ=2)

            return {
                "ok": True,
                "test": "One-way ANOVA",
                "F_x": float(an.loc["C(XGroup)", "F"]),
                "df_x_num": int(an.loc["C(XGroup)", "df"]),
                "df_x_den": int(model.df_resid),
                "p_x": float(an.loc["C(XGroup)", "PR(>F)"]),
            }

    except Exception as e:
        return {"ok": False, "err": str(e)}

def _subjects_n_per_group(dfm):
    # n per XGroup (counts non-NaN values)
    n_per_x = dfm.groupby("XGroup")["value"].apply(lambda s: int(s.dropna().shape[0]))
    groups = _order_x_groups(dfm["XGroup"].dropna().unique().tolist())
    parts = [f"{g}: n={n_per_x.get(g, 0)}" for g in groups]
    return " | ".join(parts)

def _p_to_stars(p):
    if not np.isfinite(p): return ""
    if p < 1e-4: return "****"
    if p < 1e-3: return "***"
    if p < 1e-2: return "**"
    if p < 5e-2: return "*"
    return ""

def _posthoc_ref_ttests(dfm, ref_group):
    d = dfm.dropna(subset=["value","XGroup"]).copy()
    ref = d[d["XGroup"] == ref_group]["value"].dropna().to_numpy()
    if ref_group is None or ref_group not in d["XGroup"].unique():
        return "n/a"

    groups = [g for g in d["XGroup"].unique().tolist() if g != ref_group]
    lines = []
    for g in _order_x_groups(groups):
        vals = d[d["XGroup"] == g]["value"].dropna().to_numpy()
        if len(vals) < 2 or len(ref) < 2:
            lines.append(f"{g} vs {ref_group}: not enough data")
            continue
        try:
            p = _pg_get_pval(pg.ttest(vals, ref, paired=False))
        except Exception:
            p = np.nan
        lines.append(f"{g} vs {ref_group}: p={_fmt_p_num(p)} {_p_to_stars(p)}")
    return " | ".join(lines) if lines else "n/a"

def _posthoc_pairs_anova(dfm, pair_list, x_label, hue_label):
    if not pair_list:
        return "n/a"
    lines = []
    for a, b in pair_list:
        sub = dfm[dfm["XGroup"].isin([a, b])].dropna(subset=["value"])
        if sub["XGroup"].nunique() < 2:
            continue
        res = _anova_subset(sub)  # uses your existing helper (p only)
        if not res["ok"]:
            lines.append(f"{a} vs {b}: {res['err'] or 'failed'}")
            continue
        if res["n_h"] >= 2:
            lines.append(
                f"{a} vs {b}: {x_label} p={_fmt_p_num(res['p_x'])} {_p_to_stars(res['p_x'])}, "
                f"{hue_label} p={_fmt_p_num(res['p_h'])}, int p={_fmt_p_num(res['p_int'])}"
            )
        else:
            lines.append(f"{a} vs {b}: p={_fmt_p_num(res['p_x'])} {_p_to_stars(res['p_x'])}")
    return " | ".join(lines) if lines else "n/a"

def build_stats_table(long_df, metrics, sel_x, mode, ref_group=None, pair_list=None):
    x_label_name   = _grouping_label("X")
    hue_label_name = _grouping_label("Hue")

    rows = []
    for metric in metrics:
        dfm = long_df[(long_df["variable"] == metric) & (long_df["XGroup"].isin(sel_x))].copy()
        dfm = dfm.dropna(subset=["value"])
        if dfm.empty:
            continue

        stats = _twoway_anova_full(dfm)
        subjects = _subjects_n_per_group(dfm)

        if not stats.get("ok", False):
            rows.append({
                "Figure": metric,
                "Test": "ANOVA failed",
                "Subjects": subjects,
                "F value interaction": "n/a",
                "p value interaction": "n/a",
                "Main effects": stats.get("err", "unknown error"),
                "Post hoc test": "n/a",
                "Post hoc results": "n/a",
            })
            continue

        if stats["test"] == "Two-way ANOVA":
            main_effects = (
                f"{x_label_name}: {_fmt_F(stats['df_x_num'], stats['df_x_den'], stats['F_x'])}, "
                f"p={_fmt_p_num(stats['p_x'])} {_p_to_stars(stats['p_x'])}; "
                f"{hue_label_name}: {_fmt_F(stats['df_h_num'], stats['df_h_den'], stats['F_h'])}, "
                f"p={_fmt_p_num(stats['p_h'])} {_p_to_stars(stats['p_h'])}"
            )
            f_int = _fmt_F(stats["df_int_num"], stats["df_int_den"], stats["F_int"])
            p_int = _fmt_p_num(stats["p_int"]) + (f" {_p_to_stars(stats['p_int'])}" if np.isfinite(stats["p_int"]) else "")
        else:
            main_effects = (
                f"{x_label_name}: {_fmt_F(stats['df_x_num'], stats['df_x_den'], stats['F_x'])}, "
                f"p={_fmt_p_num(stats['p_x'])} {_p_to_stars(stats['p_x'])}"
            )
            f_int, p_int = "n/a", "n/a"

        if mode == "ref":
            posthoc_test = "Unpaired t-tests vs reference"
            posthoc_res  = _posthoc_ref_ttests(dfm, ref_group)
        else:
            posthoc_test = "Selected pairwise ANOVA"
            posthoc_res  = _posthoc_pairs_anova(dfm, pair_list or [], x_label_name, hue_label_name)

        rows.append({
            "Figure": metric,
            "Test": stats["test"],
            "Subjects": subjects,
            "F value interaction": f_int,
            "p value interaction": p_int,
            "Main effects": main_effects,
            "Post hoc test": posthoc_test,
            "Post hoc results": posthoc_res,
        })

    return pd.DataFrame(rows)










### ------ Plotting Helper functions ------ ###
def _selected_x_and_colors(x_checks,x_colors):
    """
    Called in _run_plots
    """
    sel = _selected_x(x_checks)
    color_map = {}
    for g in sel:
        val = x_colors[g].value.strip()
        color_map[g] = val if val else "tab:blue"
    return sel, color_map

def _selected_x(x_checks):
    return _order_x_groups([g for g, cb in x_checks.items() if cb.value])

def _order_x_groups(groups):
    return sorted(groups, key=_hier_sort_key)

def _choose_ref_group(order):
    for g in order:
        if _is_wt_group(g):
            return g
    return order[0] if order else None

def _grouping_label(which="X"):
    if which.lower().startswith("x"):
        cols = globals().get("selected_group_cols_x", [])
        default = "XGroup"
    else:
        cols = globals().get("selected_group_cols_hue", [])
        default = "HueGroup"
    cols = [str(c).strip() for c in (cols or []) if str(c).strip()]
    return " | ".join(cols) if cols else default

def _dot_palette(hues):
    hues = list(hues)
    if len(hues) == 0: return {}
    if len(hues) == 1: return {hues[0]: "black"}
    if len(hues) == 2: return {hues[0]: "white", hues[1]: "black"}
    defaults = plt.rcParams.get('axes.prop_cycle', None)
    colors = defaults.by_key()['color'] if defaults else ["C0","C1","C2","C3","C4","C5","C6","C7","C8","C9"]
    return {h: colors[i % len(colors)] for i, h in enumerate(hues)}

def _order_hue_groups(hues):
    hp = globals().get("HUE_PRIORITY", ["Female", "Male", "F", "M", "ALL", "UNASSIGNED"])
    hp_lower = [p.lower() for p in hp]
    def _prio(h):
        u = str(h).strip()
        try:
            return (0, hp_lower.index(u.lower()), u.upper())
        except ValueError:
            return (1, u.upper())
    return sorted([h for h in hues if h is not None], key=_prio)

def _draw_bracket(ax, x1, x2, y, h, text):
    ax.plot([x1, x1, x2, x2], [y, y+h, y+h, y], lw=1, c="black", zorder=5)
    ax.text((x1+x2)/2, y+h, text, ha="center", va="bottom", fontsize=16, fontweight="bold")


### ------ PLOT METRICS ------ ###
def _plot_metric_clean(df_metric, variable, x_color_map, *, mode="ref", 
                       ref_group=None, pair_list=None, return_fig=False):
    dfm = df_metric.copy()
    order = _order_x_groups(dfm["XGroup"].dropna().unique().tolist())
    if not order: return None
    if (not ref_group) or (ref_group not in order):
        ref_group = _choose_ref_group(order)

    x_label_name   = _grouping_label("X")
    hue_label_name = _grouping_label("Hue")

    hue_levels = [h for h in dfm["HueGroup"].dropna().unique().tolist()]
    pal_dots = _dot_palette(hue_levels)

    width = max(5, 1 * len(order))
    height = 4.0
    fig, (ax_plot, ax_text) = plt.subplots(
        1, 2, figsize=(width, height), gridspec_kw={'width_ratios': [3, 1]}
    )

    # Bars
    #bar_palette = [x_color_map.get(g, "tab:blue") for g in order]
    bar_palette = {g: x_color_map.get(g, "tab:blue") for g in order}
    # replaced original barplot call
    #sns.barplot(data=dfm, x="XGroup", y="value", order=order, 
    #            ci=None, alpha=ALPHA, ax=ax_plot, 
    #            palette=bar_palette)
    sns.barplot(data=dfm, x="XGroup", y="value", order=order,
                hue="XGroup", legend=False,
                errorbar=None,
                alpha=ALPHA, ax=ax_plot, palette=bar_palette)   

    # Determine hue levels in a controlled order
    raw_hues = dfm["HueGroup"].dropna().unique().tolist()
    hue_levels = _order_hue_groups(raw_hues)

    # Colors for dots — your helper already maps 2 hues as {hues[0]: "white", hues[1]: "black"}
    pal_dots = _dot_palette(hue_levels)

    # Points
    sns.stripplot(
        data=dfm, x="XGroup", y="value",
        order=order,
        hue="HueGroup",
        hue_order=hue_levels,        # <-- enforce hue order
        jitter=True, dodge=False, size=7,
        edgecolor="black", linewidth=1,
        palette=pal_dots,            # <-- colors aligned to hue_order
        ax=ax_plot, zorder=3, alpha=ALPHA
    )
    if ax_plot.legend_ is not None:
        ax_plot.legend_.remove()

    # Legend (right panel) in the same hue order
    if len(hue_levels) >= 2:
        handles = [plt.Line2D([0],[0], marker='o', linestyle='None',
                              markerfacecolor=pal_dots[h], markeredgecolor='black', label=str(h))
                  for h in hue_levels]
        ax_text.legend(handles=handles, title=hue_label_name, loc="upper left", bbox_to_anchor=(0, 0.6))

    # Annotations
    y_min, y_max = ax_plot.get_ylim()
    span = (y_max - y_min) if y_max > y_min else 1.0
    bump = 0.06 * span
    data_max = dfm["value"].max() if dfm["value"].notna().any() else y_max

    if mode == "ref" and (ref_group in order):
        ref_vals = dfm[dfm["XGroup"] == ref_group]["value"].dropna().to_numpy()
        for g in order:
            if g == ref_group: continue
            vals = dfm[dfm["XGroup"] == g]["value"].dropna().to_numpy()
            if len(vals) >= 2 and len(ref_vals) >= 2:
                try:
                    p = _pg_get_pval(pg.ttest(vals, ref_vals, paired=False))
                except Exception:
                    p = np.nan
                if np.isfinite(p) and p < 0.05:
                    xloc = order.index(g)
                    gmax = dfm[dfm["XGroup"] == g]["value"].max()
                    y_star = (gmax if np.isfinite(gmax) else data_max) + bump
                    ax_plot.text(xloc, y_star, _p_to_stars(p),
                                 ha="center", va="bottom", fontsize=16, fontweight="bold")
                    y_max = max(y_max, y_star + bump)
        ax_plot.set_ylim(y_min, y_max)

    elif mode == "pairs" and pair_list:
        base = (dfm["value"].max() if dfm["value"].notna().any() else y_max) + bump
        step = 0.12 * span
        k = 0
        for a,b in pair_list:
            if (a not in order) or (b not in order):
                continue
            sub = dfm[dfm["XGroup"].isin([a,b])].dropna(subset=["value"])
            if sub["XGroup"].nunique() < 2:
                continue
            res = _anova_subset(sub)
            # draw bracket ONLY if XGroup effect significant
            if res["ok"] and np.isfinite(res["p_x"]) and (res["p_x"] < 0.05):
                x1 = order.index(a); x2 = order.index(b)
                if x1 > x2: x1, x2 = x2, x1
                y_here = base + k * step
                _draw_bracket(ax_plot, x1, x2, y_here, 0.04 * span, _p_to_stars(res["p_x"]))
                y_max = max(y_max, y_here + 0.08 * span)
                k += 1
        ax_plot.set_ylim(y_min, y_max)

    ax_plot.set_title("")
    ax_plot.set_xlabel("")
    ax_plot.set_ylabel(variable)
    plt.setp(ax_plot.get_xticklabels(), rotation=45, ha='right')
    sns.despine(ax=ax_plot)

    # Right panel: stats + Hue legend
    ax_text.axis("off")
    ax_text.text(
        0, 1,
        _stats_text(dfm, x_label_name, hue_label_name, mode=mode, ref_group=ref_group, pair_list=pair_list),
        va="top", ha="left", fontsize=12, transform=ax_text.transAxes
    )
    if len(hue_levels) >= 2:
        handles = [plt.Line2D([0],[0], marker='o', linestyle='None',
                              markerfacecolor=pal_dots[h], markeredgecolor='black', label=str(h))
                   for h in hue_levels]
        ax_text.legend(handles=handles, title=hue_label_name, loc="upper left", bbox_to_anchor=(0, 0.6))

    plt.tight_layout()

    return fig if return_fig else plt.show()


def _run_plots(long_df, x_checks, x_colors, ordered_x, root_path, mode = "ref", _=None):
    """
    Function that wraps around the _plot_metric_clean to loop through different metrics
    Returns:
        saved_paths; List
            list of saved paths to the bandit metric plots
    """
    #clear_output()

    status.step("Creating Metric Plots")
    # intitate a empty list to capture the results
    saved_paths  = []

    # Create the directory that will be writen to
    out_dir = Path(root_path, "metric_bar_plots")
    out_dir.mkdir(parents=True, exist_ok=True)


    sel_x, color_map = _selected_x_and_colors(x_checks, x_colors)
    if len(sel_x) < 1:
        print("Select at least one X group."); return

    #mode = mode_radio.valuez
    ref_dropdown = widgets.Dropdown(
        options = ordered_x, value=_choose_ref_group(ordered_x),
        description = "Reference:", layout=widgets.Layout(width="320px")
    )   

    if mode == "ref":
        ref = ref_dropdown.value if (ref_dropdown.value in sel_x) else _choose_ref_group(sel_x)
        status.ok(f"Showing X groups: {sel_x}  |  reference for stars: {ref}")
    else:
        pair_list = _current_pairs()
        if not pair_list:
            print(f"Showing X groups: {sel_x}  |  no pairs selected (select at least one)."); return
        print(f"Showing X groups: {sel_x}  |  pairs: {pair_list}")

    exclude = {"PeakAccuracy_Day","PeakAccuracy_Night",
                "Win-stay_Day","Win-stay_Night",
                "Lose-shift_Day","Lose-shift_Night"}
    metrics = [m for m in long_df["variable"].dropna().unique() if m not in exclude]

    for metric in metrics:
        subset = long_df[(long_df["variable"] == metric) & (long_df["XGroup"].isin(sel_x))]
        if subset["value"].dropna().empty:
            status.warn(f"Skipping {metric} — no data for selected X groups."); continue
        if mode == "ref":
            fig = _plot_metric_clean(
                subset, metric,
                x_color_map={g: color_map[g] for g in sel_x if g in subset['XGroup'].unique()},
                mode="ref", ref_group=ref,
                return_fig=True
            )
        else:
            fig = _plot_metric_clean(
                subset, metric,
                x_color_map={g: color_map[g] for g in sel_x if g in subset['XGroup'].unique()},
                mode="pairs", pair_list=_current_pairs(),
                return_fig=True
            )

        if fig is None:
            status.warn(f"Skipping {metric} — no figure produced.")
            continue

        safe_name = re.sub(r"[^A-Za-z0-9_-]+", "_", metric).strip("_")
        out_path = out_dir / f"{safe_name}.png"

        # Save at print-friendly resolution; bbox_inches="tight" trims the
        # generous whitespace left by the 2-panel layout + rotated x-labels.
        fig.savefig(out_path, dpi=300, bbox_inches="tight")

        plt.close(fig)

        saved_paths.append(out_path)
        status.ok(f"Saved {metric} -> {out_path}")
    
    return saved_paths 


#@@@@@@@@@@@@@@@@@@ Peak Accuracy @@@@@@@@@@@@@@@@@@#


### ------ General Helper functions ------ ###
def _is_empty(x):
    if x is None: return True
    try:
        return len(x) == 0
    except Exception:
        try:
            return np.size(x) == 0
        except Exception:
            return True


def _order_x_groups_local(groups):
    return sorted(groups, key=_hier_sort_key_local)

def _hier_sort_key_local(g):
    lv = _x_levels_local(g)
    wt_present = any(_is_wt_group_label(tok) for tok in lv) or _is_wt_group_label(g)
    wt_rank = 0 if wt_present else 1
    norm = []
    for tok in lv:
        is_blank = 1 if str(tok).strip().upper() in {"", "UNASSIGNED", "NONE", "NA", "N/A"} else 0
        norm.append((is_blank, str(tok).upper()))
    return (wt_rank,) + tuple(norm) + (str(g).upper(),)

def _is_wt_group_label(g):
    u = str(g).strip().upper()
    toks = [t for t in re.split(r'[^A-Z0-9]+', u) if t]
    return any(t in {"WT", "WILDTYPE", "CONTROL", "CTRL"} for t in toks)

def _x_levels_local(g):
    s = str(g)
    return [p.strip() for p in s.split("|")]

### ------ MAIN FUNCTIONS ------ ###
def prep_pa_groups(mapped_df):
    """
    build dictionary of filenames linked to groups

    Returns
        fname_to_xgroup; Dict
            dictionary mapping filenames to groupings
    """
    # filename -> XGroup map (match on basename)
    #grp = files_to_group_both.copy()
    grp = mapped_df.copy()
    src_col = "filename" if "filename" in grp.columns else ("File" if "File" in grp.columns else None)
    if src_col is None:
        raise RuntimeError("`files_to_group_both` must include 'filename' or 'File'.")
    basename = lambda s: os.path.basename(str(s))
    grp["__base__"] = grp[src_col].astype(str).map(basename)
    fname_to_xgroup = dict(grp[["__base__", "XGroup"]].dropna().values)

    return basename, fname_to_xgroup



def build_rev_df(feds, fname_to_xgroup,  basename):
    """
    Builds reversal learning dataframe

    Arguments

    Returns:
        Dataframe for reversal learning plotting
    """
    rows = []
    # --- Build rev_df ---
    for i, sess in enumerate(feds):
        base = basename(getattr(sess, "name", f"session_{i}"))
        xg = fname_to_xgroup.get(base, "UNASSIGNED")

        # compute peri-switch trials using your f3b helper
        try:
            peh = fed3bandit_extracted.reversal_peh(sess, (-TRIALS, TRIALS), return_avg=False)
        except Exception as e:
            print(f"[skip] {base}: reversal_peh failed: {e}")
            continue

        if _is_empty(peh):
            continue

        # peh is list/array of trial-length arrays; stack defensively
        for tr in list(peh):
            arr = np.asarray(tr).ravel()
            for t, v in enumerate(arr):
                rows.append({
                    "Timepoint": t - TRIALS + 1,    # center around 0
                    "Value": float(v) if np.isfinite(v) else np.nan,
                    "Display_Group": xg
                })

    rev_df = pd.DataFrame(rows)
    rev_df = rev_df[np.isfinite(rev_df["Value"])]
    rev_df = rev_df[rev_df["Timepoint"] != 0] # optional: drop center trial
    if rev_df.empty:
        raise RuntimeError("No peri-switch data produced.")
    
    return rev_df


def plot_rev_learning(rev_df, x_colors, ordered_x, bm_md, root_path):
    """
    Creates a reverse learning plot

    Arguments:
        bm_md; Dataframe
            used to pull out the Gene name to replace HET with for vizualization
    """

    status.step("creating reverse learning plot")
    
    # Create the directory that will be written to
    out_dir = Path(root_path, "rev_learning")
    out_dir.mkdir(parents=True, exist_ok=True)

    saved_path = []

    # Pull out the gene name
    genename = bm_md["Gene"][0]

    # Replace "HET" with the genename for vizualization purposes in ordered
    ordered_x = [genename if label == "HET" else label for label in ordered_x]

    # replace in x_colors
    if "HET" in x_colors:
        x_colors[genename] = x_colors.pop("HET")

    # replace HET in rev_df
    rev_df["Display_Group"] = rev_df["Display_Group"].replace("HET", genename)  

    

    _present = rev_df["Display_Group"].dropna().unique().tolist()

    # ORDER: if the first cell was run, follow its ordered_x; otherwise reproduce the same rule.
    if ordered_x:
        group_order = [g for g in ordered_x if g in _present] + [g for g in _present if g not in ordered_x]
    else:
        group_order = _order_x_groups_local(_present)


    # COLORS: pull from the first cell's x_colors widget map; fall back if unavailable.
    palette_map = None
    
    #if "x_colors" in globals() and isinstance(x_colors, dict) and len(x_colors) > 0:
    def _col(g):
        try:
            v = x_colors[g].value
            v = v.strip() if isinstance(v, str) else ""
            return v if v else "tab:blue"
        except Exception:
            return "tab:blue"
    
    palette_map = {g: _col(g) for g in group_order}

    plt.figure(figsize=(7, 5))
    # --- Plot (lines with SEM ribbons) ---
    group_order = sorted(rev_df["Display_Group"].dropna().unique().tolist()) 
    # ensure WT is first
    group_order = ["WT"] + sorted(g for g in group_order if g != "WT")


    ax = sns.lineplot(
        data=rev_df.sort_values(["Display_Group", "Timepoint"]),
        x="Timepoint",
        y="Value",
        hue="Display_Group",
        hue_order=group_order,
        palette=palette_map,
        estimator="mean",
        errorbar="se",
        n_boot=0,
        lw=2
    )

    # Switch marker and label
    ax.axvline(x=0, color="grey", linestyle = (0, (3, 5)), linewidth=1.25)
    
    ax.set_ylim(bottom=0, top=1)
    ymin, ymax = ax.get_ylim()
    
    # switch label
    ax.text(0.5, ymin + 0.95 * (ymax - ymin), "Switch", color="dimgrey",
            fontsize=16, ha="left", va="top", weight = "bold")

    ax.set_xlabel("Trials around switch", fontsize = 18)
    ax.set_ylabel("Peak Accuracy %", fontsize = 18)
    ax.set_title("")
    
    ax.legend(
        title="",
        frameon=False,
        loc="lower left",
        #bbox_to_anchor=(1.12, 0.5),
        borderaxespad=0.2
    )

    sns.despine()
    plt.tight_layout()

    # Embed TrueType fonts so text stays editable in Illustrator/Inkscape
    #mpl.rcParams['pdf.fonttype'] = 42
    #mpl.rcParams['ps.fonttype']  = 42



    fig = ax.get_figure()  # or plt.gcf() if you prefer



    #files.download(os.path.join(outdir, fname))
    #plt.show()

    safe_name = genename + "_rev_learning"
    out_path = out_dir / f"{safe_name}.png"

    # Save at print-friendly resolution; bbox_inches="tight" trims the
    # generous whitespace left by the 2-panel layout + rotated x-labels.
    fig.savefig(out_path, dpi=300, bbox_inches="tight")

    plt.close(fig)
    ### Add download botton instead of auto download ###
    # define path and file name
    #output_file = os.path.join(outdir, fname)

    saved_path.append(out_path)

    status.ok("Reverse learning plot created")
    
    #return the path that it is saved to
    return saved_path






#@@@@@@@@@@@@@@@@@@ Automate L4 Assembly @@@@@@@@@@@@@@@@@@#



#!!!!! WRITTEN WITH HELP VIA CLAUDE Opus 4.8 - Medium !!!!!
def _plot_metric_display(dfm, variable, ax, x_color_map, *,
                         group_order=None, hue_order=None, ylabel=None,
                         pval_fontsize=11, label_fontsize=13):
    """
    Draw ONE metric as a stripped-down bar+strip panel onto a caller-supplied
    Axes, for use in the composite L4 figure.

    Unlike _plot_metric_clean (which owns a 2-panel figure with a stats
    sidebar), this draws only the bar + individual dots + a single top-centered
    genotype p-value. It creates no figure and no per-panel legend: the caller
    (assemble_l4) supplies the Axes and builds one shared Sex legend for the
    whole figure.

    Arguments:
        dfm : DataFrame
            Long-format rows for a SINGLE metric (already filtered to `variable`),
            with columns XGroup / HueGroup / value.
        variable : str
            Metric name; used only as the y-label fallback.
        ax : matplotlib Axes
            Target axes to draw into.
        x_color_map : dict
            {XGroup -> color string} for the bars. Keys must match the (already
            relabeled) XGroup values.
        group_order : list | None
            Bar order along x. Defaults to the library's standard order.
        hue_order : list | None
            Controlled Sex order so dot colors stay consistent across panels.
        ylabel : str | None
            Y-axis label (e.g. "Total pokes"). Falls back to `variable`.

    Returns:
        handles : list[Line2D]
            Legend proxy handles for the hue (Sex) levels, so the caller can
            build a single shared legend. Empty list if fewer than 2 hue levels.
    """
    dfm = dfm.copy()

    # Bar order: caller-provided, else fall back to the library's standard order.
    order = group_order or _order_x_groups(dfm["XGroup"].dropna().unique().tolist())
    if not order:
        return []

    # Hue (Sex) order + dot colors, matching _plot_metric_clean's convention
    # (helper maps 2 hues as {hues[0]: "white", hues[1]: "black"}).
    hue_levels = hue_order or _order_hue_groups(dfm["HueGroup"].dropna().unique().tolist())
    pal_dots = _dot_palette(hue_levels)

    # --- Bars: mean per XGroup, no seaborn error bars, alpha shared with dots ---
    bar_palette = {g: x_color_map.get(g, "tab:blue") for g in order}
    sns.barplot(
        data=dfm, x="XGroup", y="value", order=order,
        hue="XGroup", legend=False, errorbar=None,
        alpha=ALPHA, ax=ax, palette=bar_palette,
    )

    # --- Individual animals as dots, colored by Sex, drawn above the bars ---
    sns.stripplot(
        data=dfm, x="XGroup", y="value", order=order,
        hue="HueGroup", hue_order=hue_levels,
        jitter=True, dodge=False, size=6,
        edgecolor="black", linewidth=1,
        palette=pal_dots, ax=ax, zorder=3, alpha=ALPHA,
    )
    # stripplot auto-attaches a legend to the axes; remove it, because the
    # composite figure carries ONE shared Sex legend built by the caller.
    if ax.legend_ is not None:
        ax.legend_.remove()

    # --- Single genotype p-value from the two-way ANOVA (matches L4 caption) ---
    # We report the XGroup (genotype) main effect p_x, NOT per-group t-tests, so
    # this reads e.g. "p = 0.002" / "p < 0.001" exactly like the deliverable.
    res = _twoway_anova_full(dfm)
    if res.get("ok") and np.isfinite(res.get("p_x", np.nan)):
        ax.text(
            0.5, 1.05, _fmt_p(res["p_x"]),
            transform=ax.transAxes, ha="center", va="top",
            fontsize=pval_fontsize, fontstyle="italic",
        )

    # --- Cosmetics: no title/xlabel, metric name on y, clean spines ---
    ax.set_title("")
    ax.set_xlabel("")
    ax.set_ylabel(ylabel or variable, fontsize=label_fontsize)
    sns.despine(ax=ax)

    # Build (but do NOT place) the Sex legend proxies for the caller to use once.
    handles = []
    if len(hue_levels) >= 2:
        handles = [
            plt.Line2D([0], [0], marker="o", linestyle="None",
                       markerfacecolor=pal_dots[h], markeredgecolor="black",
                       label=str(h))
            for h in hue_levels
        ]
    return handles


#!!!!! WRITTEN WITH HELP VIA CLAUDE Opus 4.8 - Medium !!!!!
def _rev_learning_core(rev_df, ax, palette_map, group_order):
    """
    Draw the reverse-learning line plot (accuracy around the switch) onto a
    caller-supplied Axes. Extracted so both the standalone plot_rev_learning and
    the composite assemble_l4 can share one drawing routine.

    Assumes rev_df["Display_Group"] is ALREADY relabeled (HET -> gene name) and
    that palette_map / group_order are keyed by those final labels.
    """
    sns.lineplot(
        data=rev_df.sort_values(["Display_Group", "Timepoint"]),
        x="Timepoint", y="Value",
        hue="Display_Group", hue_order=group_order,
        palette=palette_map,
        estimator="mean", errorbar="se", n_boot=0, lw=2, ax=ax,
    )

    # Vertical dashed marker at the reversal ("Switch") point.
    ax.axvline(x=0, color="grey", linestyle=(0, (3, 5)), linewidth=1.25)

    ax.set_ylim(bottom=0, top=1)
    ymin, ymax = ax.get_ylim()
    # "Switch" caption pinned just inside the top of the plot area.
    ax.text(0.5, ymin + 0.95 * (ymax - ymin), "Switch",
            color="dimgrey", fontsize=14, ha="left", va="top", weight="bold")

    ax.set_xlabel("Trials around switch", fontsize=14)
    ax.set_ylabel("Peak Accuracy %", fontsize=14)
    ax.set_title("")
    # Genotype legend for the two lines, lower-left inside the panel.
    ax.legend(title="", frameon=False, loc="lower left", borderaxespad=0.2)
    sns.despine(ax=ax)


#!!!!! WRITTEN WITH HELP VIA CLAUDE Opus 4.8 - Medium !!!!!
def find_contrast_pair(df, pellet_tol=15, min_sessions=1, wt_label="WT", het_label="Het"):
    """
    Find one WT mouse and one Het mouse with SIMILAR total pellets but a LARGE gap
    in PeakAccuracy — i.e. a clean "same reward earned, different task performance"
    contrast, the kind of example pair you'd want to highlight in a figure.

    Returns (best_pair_row, full_ranked_table).
    """

    # --- 1. Collapse sessions -> one representative row per mouse ---
    # Every filename is a single session, so we average within a mouse 
    per_mouse = (
        df.groupby("Mouse_ID")
        .agg(
            Genotype=("Genotype", "first"),         # constant within a mouse
            PeakAccuracy=("PeakAccuracy", "mean"),
            Total_pellets=("Total_pellets", "mean"),
            n_sessions=("filename", "size"),
        )
        .reset_index()
    )

    # Drop mice with too few sessions for the mean to be meaningful.
    per_mouse = per_mouse[per_mouse["n_sessions"] >= min_sessions]

    # --- 2. Split by genotype, normalizing case so "Het"/"HET"/"het" all match ---
    geno = per_mouse["Genotype"].str.upper()
    wt = per_mouse[geno == wt_label.upper()].copy()
    het = per_mouse[geno == het_label.upper()].copy()

    # Fail loudly (with the actual labels present) rather than returning nonsense.
    if wt.empty or het.empty:
        raise ValueError(
            f"Need both genotypes. Found {len(wt)} WT and {len(het)} Het. "
            f"Genotype values present: {sorted(per_mouse['Genotype'].unique())}"
        )

    # --- 3. Build every WT x Het candidate pair ---
    # Cross join is fine here: this is mice-by-mice, not sessions, so the table is small.
    pairs = wt.merge(het, how="cross", suffixes=("_WT", "_HET"))

    # --- 4. Score each pair ---
    # pellet_gap -> want SMALL (similar reward);  acc_gap -> want LARGE (different performance).
    pairs["pellet_gap"] = (pairs["Total_pellets_WT"] - pairs["Total_pellets_HET"]).abs()
    pairs["acc_gap"] = (pairs["PeakAccuracy_WT"] - pairs["PeakAccuracy_HET"]).abs()

    # Keep only pairs whose pellet totals are actually close.
    similar = pairs[pairs["pellet_gap"] <= pellet_tol].copy()

    # Edge case: tolerance too tight -> fall back to the closest-pellet pairs so the
    # function still returns a usable result instead of an empty frame.
    if similar.empty:
        print(f"[warn] No pairs within pellet_tol={pellet_tol}; showing closest-pellet pairs instead.")
        similar = pairs.nsmallest(20, "pellet_gap").copy()

    # Among pellet-matched pairs, the best contrast is simply the largest accuracy gap.
    ranked = similar.sort_values("acc_gap", ascending=False).reset_index(drop=True)

    # --- 5. Convenience: pull out the single best pair ---
    cols = [
        "Mouse_ID_WT", "PeakAccuracy_WT", "Total_pellets_WT",
        "Mouse_ID_HET", "PeakAccuracy_HET", "Total_pellets_HET",
        "pellet_gap", "acc_gap",
    ]
    return ranked.loc[0, cols], ranked[cols]




#!!!!! WRITTEN WITH HELP VIA CLAUDE Opus 4.8 - Medium !!!!!
def _plot_pleft_core(df, ax, *, line_color="dodgerblue", behaviour_label=None,
                     show_xlabel=True):
    """
    Draw ONE mouse's choice trace onto a caller-supplied Axes: the true reward
    probability for the left port (grey, the "Rewarded Side") plus the mouse's
    binned P(Left) action (colored). Creates no figure and saves nothing — the
    caller owns the Axes. This is the composable core shared by
    _plot_file_core_display (loop + save) and any composite that needs the trace.

    Arguments:
        df : DataFrame
            A single FED session, already metadata-attached and numeric-coerced.
        ax : matplotlib Axes
            Target axes to draw into.
        line_color : str
            Color for the mouse's action line. For L4 this is the GENOTYPE color
            (WT blue / gene red), not the sex color.
        behaviour_label : str | None
            Optional right-margin label, e.g. "Wildtype behaviour".
        show_xlabel : bool
            Whether to draw the "Trial" x-label (off for the top of a stack).
    """
    # True underlying reward probability for the left port (the step function).
    true_left = fed3bandit_extracted.true_probs(df, offset=5)[0]
    # Mouse's actual choice behaviour, smoothed over a sliding window.
    mouse_left = fed3bandit_extracted.binned_paction(df, window=10)

    # Grey reference = where reward actually was; colored = what the mouse did.
    ax.plot(np.arange(len(true_left)), true_left, color="black", linewidth=2, alpha=0.5)
    ax.plot(np.arange(len(mouse_left)), mouse_left, color=line_color, linewidth=3, alpha=0.7)

    ax.set_ylabel("P(Left)")
    ax.set_yticks([0, 0.5, 1])
    ax.set_xlabel("Trial" if show_xlabel else "")

    if behaviour_label:
        # Label sits just outside the right edge, colored to match the trace.
        ax.text(1.01, 0.5, behaviour_label, transform=ax.transAxes,
                va="center", ha="left", color=line_color, fontsize=12)

    sns.despine(ax=ax)


def _plot_file_core_display(fed_list, metadata_df, root_path, dpi=150,
                            select_ids=None, color_by="sex",
                            genotype_colors=None):
    """
    Plot per-file switch-bandit P(Left) traces and save them.

    L4 use: pass select_ids=[wt_id, het_id] (from find_contrast_pair) to render
    ONLY the two example mice, and color_by="genotype" so the traces match the
    rest of the figure (WT blue / gene red) instead of being colored by sex.

    Arguments:
        fed_list : list
            FED session DataFrames (each carries a .name filename attribute).
        metadata_df : DataFrame
            Stitched metadata; used to attach fields and map filename -> Mouse_ID.
        root_path : str | Path
            Output root; PNGs are written under <root_path>/indv_bandit_plots.
        dpi : int
            Save resolution.
        select_ids : list | set | None
            If given, only mice whose Mouse_ID is in this collection are plotted.
            None -> plot everything (original behaviour).
        color_by : {"sex", "genotype"}
            "sex"      -> red for female, else blue (original behaviour).
            "genotype" -> look up genotype_colors by the mouse's Genotype.
        genotype_colors : dict | None
            {Genotype -> color}, required when color_by="genotype". Keys are the
            RAW genotype labels present in the data (e.g. "WT", "HET").

    Returns:
        saved : dict
            {Mouse_ID (str) -> Path} for every trace saved, so callers can pick
            out specific mice (e.g. WT vs HET) by identity rather than order.
    """
    status.step("Beginning to plot bandit assays")

    out_dir = Path(root_path, "indv_bandit_plots")
    out_dir.mkdir(parents=True, exist_ok=True)

    # Normalize the selection to a set of strings once, for cheap membership tests.
    select_set = None if select_ids is None else {str(s) for s in select_ids}

    saved = {}  # Mouse_ID -> saved path

    for fed in fed_list:
        df = fed.copy()
        full_name = getattr(df, "name", f"File_{fed}")
        file_basename = os.path.basename(str(full_name))

        # Preserve original index once.
        if "Original_Timestamp" not in df.columns:
            df["Original_Timestamp"] = df.index

        # Attach metadata by filename (matching already done upstream).
        meta_row = None
        if "filename" in metadata_df.columns:
            mr = metadata_df.loc[metadata_df["filename"] == file_basename]
            if not mr.empty:
                meta_row = mr.iloc[0]
        if meta_row is not None:
            for col in meta_row.index:
                if col == "filename":
                    continue
                if col not in df.columns:
                    df[col] = meta_row[col]
                else:
                    if pd.isna(df[col]).all() and pd.notna(meta_row[col]):
                        df[col] = meta_row[col]

        # Resolve this file's Mouse_ID (fallback to the filename).
        mouse_id = (
            str(meta_row["Mouse_ID"])
            if (meta_row is not None and "Mouse_ID" in meta_row and pd.notna(meta_row["Mouse_ID"]))
            else file_basename
        )

        # --- Selection filter: skip mice we weren't asked to plot ---
        # Done BEFORE the expensive time/coerce/plot work so we don't waste it.
        if select_set is not None and mouse_id not in select_set:
            continue

        # Time + cleanup.
        try:
            df["timestamp"] = pd.to_datetime(df.index)
        except Exception:
            df["timestamp"] = np.arange(len(df))

        _coerce_numeric_col(df, "Poke_Time", clip_upper=2)
        _coerce_numeric_col(df, "Retrieval_Time", na_map={"Timed_out": np.nan})

        if len(df) == 0:
            status.warn(f"[!] Empty dataframe for {file_basename}. Skipping plot.")
            continue

        # --- Decide the trace color ---
        if color_by == "genotype" and genotype_colors:
            # Match the mouse's genotype (case-insensitively) to a supplied color.
            geno = str(df["Genotype"].iloc[0]).strip().upper() if "Genotype" in df.columns else ""
            # Build an upper-cased lookup so "Het"/"HET" both resolve.
            gc_upper = {str(k).upper(): v for k, v in genotype_colors.items()}
            color = gc_upper.get(geno, "dodgerblue")
        else:
            # Original behaviour: red for female, blue otherwise.
            color = "dodgerblue"
            if "Sex" in df.columns and pd.notna(df["Sex"]).any():
                try:
                    color = "red" if str(df["Sex"].iloc[0]).strip().lower().startswith("f") else "dodgerblue"
                except Exception:
                    pass

        # --- Draw via the shared core, then title + save ---
        fig, ax = plt.subplots(figsize=(10, 3))
        _plot_pleft_core(df, ax, line_color=color)
        ax.set_title(mouse_id)

        plt.tight_layout()

        safe_title = "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in mouse_id)
        out_path = out_dir / f"{safe_title}_pLeft.png"
        fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
        plt.close(fig)

        saved[mouse_id] = out_path
        status.ok(f"saved {out_path.name}")

    status.ok(f"Plots saved to: {out_dir}")
    return saved



#!!!!! WRITTEN WITH HELP VIA CLAUDE Opus 4.8 - Medium !!!!!
def _fed_for_mouse(fed_list, metadata_df, mouse_id):
    """
    Return the FIRST FED session DataFrame whose filename maps (via metadata_df)
    to `mouse_id`, or None if not found. Used by Option 2 above to draw a mouse's
    trace directly rather than re-reading a saved PNG.

    Note: a mouse may have several sessions; this returns the first match. Pick a
    specific session upstream if you need a particular one.
    """
    if "Mouse_ID" not in metadata_df.columns or "filename" not in metadata_df.columns:
        return None
    # All filenames belonging to this mouse.
    files = set(
        metadata_df.loc[metadata_df["Mouse_ID"].astype(str) == str(mouse_id), "filename"]
    )
    if not files:
        return None
    for fed in fed_list:
        name = os.path.basename(str(getattr(fed, "name", "")))
        if name in files:
            return fed
    return None






#!!!!! WRITTEN WITH HELP VIA CLAUDE Opus 4.8 - Medium !!!!!
def assemble_l4(long_df, rev_df, x_colors, ordered_x, bm_md, root_path,
                fed_list, metadata_df, *, schematic_path=None, dpi=300):
    """
    Assemble the composite "L4" deliverable figure for one knockout model:

        A) device schematic (optional) + two example P(Left) traces
           (a WT and a gene mouse chosen for similar reward / different accuracy)
        B) reverse-learning line plot  +  Peak Accuracy bar
        C) Total pokes bar
        D) Win-stay bar
        E) Lose-shift bar

    plus a single shared Sex (Female/Male) legend and a caption. Every bar panel
    reports the genotype main effect from a two-way ANOVA, matching the caption.

    Orchestration only: the drawing lives in _plot_pleft_core, _rev_learning_core
    and _plot_metric_display so the layout logic here stays readable.

    Arguments:
        long_df : DataFrame
            Melted metrics (columns: variable / XGroup / HueGroup / value).
        rev_df : DataFrame
            Per-trial peak accuracy around the switch (Timepoint / Value /
            Display_Group).
        x_colors : dict
            Group -> ipywidgets color widget (plain strings also tolerated).
        ordered_x : list
            X-group order hint from the aesthetics step (WT is forced first).
        bm_md : DataFrame
            Per-session metadata; supplies the gene name AND feeds
            find_contrast_pair to choose the two example mice.
        root_path : str | Path
            Output root; the figure is written under <root_path>/L4.
        fed_list : list
            FED session DataFrames, used to draw the two example traces directly.
        metadata_df : DataFrame
            Stitched metadata, used to map Mouse_ID -> FED session for the traces.
        schematic_path : str | Path | None
            Optional device/behaviour image for the top-left of panel A. If None,
            that corner is left blank for manual assembly.
        dpi : int
            Save resolution.

    Returns:
        out_path : Path
            Path to the saved composite PNG.
    """
    import matplotlib.image as mpimg  # only needed if a schematic is supplied

    status.step("Assembling L4 composite figure")

    out_dir = Path(root_path, "L4")
    out_dir.mkdir(parents=True, exist_ok=True)

    # Gene name that replaces the generic "HET" label throughout the figure.
    genename = bm_md["Gene"][0]

    # --- Pick the two example mice: similar reward, different performance ---
    best, ranked = find_contrast_pair(bm_md, pellet_tol=15)
    wt_id = str(best["Mouse_ID_WT"])
    het_id = str(best["Mouse_ID_HET"])
    status.ok(f"L4 example pair -> WT: {wt_id} | {genename}: {het_id} "
              f"(acc gap {best['acc_gap']:.3f}, pellet gap {best['pellet_gap']:.1f})")

    # --- Resolve colors to a plain {group: color} dict ONCE ---
    # x_colors may hold ipywidgets (with .value) or plain strings; tolerate both.
    def _resolve(g):
        c = x_colors.get(g, None)
        val = getattr(c, "value", c)                 # widget -> .value, else itself
        val = val.strip() if isinstance(val, str) else ""
        return val or "tab:blue"
    color_map = {g: _resolve(g) for g in x_colors}
    # Carry the HET color onto the gene-named key so its bars/line stay red.
    if "HET" in color_map:
        color_map[genename] = color_map.pop("HET")

    # --- Relabel HET -> gene name in BOTH tables (copies; don't mutate caller) ---
    long_df = long_df.copy()
    long_df["XGroup"] = long_df["XGroup"].replace("HET", genename)
    rev_df = rev_df.copy()
    rev_df["Display_Group"] = rev_df["Display_Group"].replace("HET", genename)

    # Canonical order: WT first, then the gene. Controls both bar order and which
    # line draws on top; WT (blue) over the gene (red), matching the deliverable.
    group_order = ["WT"] + [g for g in [genename] if g != "WT"]

    # One controlled Sex order shared by every bar panel so dot colors line up.
    hue_order = _order_hue_groups(long_df["HueGroup"].dropna().unique().tolist())



    # ---------------- Figure + grid layout ----------------
    # Row 0: panel A. Row 1: line plot (wide) + four equal-width bars.
    fig = plt.figure(figsize=(16, 8))
    gs = fig.add_gridspec(
        nrows=2, ncols=5,
        height_ratios=[1.0, 1.4],
        width_ratios=[3, 1, 1, 1, 1],
        hspace=0.35, wspace=0.45,
    )


    # --- Panel A: schematic (left) + two stacked example traces (right) ---
    # Nested grid so the top row can hold both the image and the two traces.
    gs_a = gs[0, :].subgridspec(2, 2, width_ratios=[1, 2.5], hspace=0.25, wspace=0.08)



    # Schematic spans both sub-rows on the left; blank if no image supplied.
    schematic_path=fedassets.get("bandit_schematic.jpg")

    ax_schem = fig.add_subplot(gs_a[:, 0])
    ax_schem.axis("off")

    if schematic_path is not None and Path(schematic_path).exists():
        ax_schem.imshow(mpimg.imread(str(schematic_path)))
    ax_schem.set_title(genename, loc="left", fontsize=20, fontweight="bold")



    # Two example traces, drawn directly onto their axes (no PNG round-trip).
    # (Mouse_ID, right-margin label, genotype color, show x-label on bottom only)
    trace_specs = [
        (wt_id,  "Wildtype behaviour",     color_map["WT"],       False),
        (het_id, f"{genename} behaviour",  color_map[genename],   True),
    ]
    for row, (mid, label, col, show_x) in enumerate(trace_specs):
        ax_tr = fig.add_subplot(gs_a[row, 1])
        fed = _fed_for_mouse(fed_list, metadata_df, mid)
        if fed is None:
            # Missing session shouldn't kill the whole composite.
            status.warn(f"L4: no FED session found for Mouse_ID {mid}; blank trace.")
            ax_tr.axis("off")
            continue
        _plot_pleft_core(fed, ax_tr, line_color=col,
                         behaviour_label=label, show_xlabel=show_x)



    # --- Panel B-left: reverse-learning line plot ---
    ax_line = fig.add_subplot(gs[1, 0])
    _rev_learning_core(rev_df, ax_line, palette_map=color_map, group_order=group_order)



    # --- Panels B-bar / C / D / E: the four scalar metrics, in figure order ---
    # (long_df variable name, y-axis label shown on the panel)
    metric_specs = [
        ("PeakAccuracy", "Peak Accuracy %"),
        ("Total_pokes",  "Total pokes"),
        ("Win-stay",     "Win-stay"),
        ("Lose-shift",   "Lose-shift"),
    ]




    shared_handles = []
    for col, (metric, ylabel) in enumerate(metric_specs, start=1):
        ax_bar = fig.add_subplot(gs[1, col])
        sub = long_df[long_df["variable"] == metric]
        # Guard: a model missing a metric shouldn't crash the whole composite.
        if sub["value"].dropna().empty:
            status.warn(f"L4: no data for {metric}; leaving panel blank.")
            ax_bar.axis("off")
            continue
        handles = _plot_metric_display(
            sub, metric, ax_bar, color_map,
            group_order=group_order, hue_order=hue_order, ylabel=ylabel,
        )
        # Keep the first non-empty proxy set for the single shared legend.
        if handles and not shared_handles:
            shared_handles = handles



    # --- One shared Sex legend for the whole figure (top-right) ---
    if shared_handles:
        fig.legend(
            handles=shared_handles, title="Sex",
            loc="lower right", frameon=False,
            bbox_to_anchor=(0.95, 0.35),
        )



    # --- Caption block beneath the panels ---
    # Assembled line-by-line (each string ends with a space) so the joins never
    # run words together, with explicit \n where a visible line break is wanted.
    caption = (
        "A) FED3 device and example behaviour schematic. "
        "B) Line plot and bar graph of peak accuracy in the 10 trials around a switch.\n"
        "C, D, E) Bar graphs of mean total pokes, win-stay and lose-shift respectively.\n"
        "Win-stay: after a reward, did the mouse choose the same port again. "
        "Lose-shift: after no reward, did it choose the opposite port.\n"
        "Statistics: two-way ANOVA; the reported p-value is the genotype effect "
        "(genotype x sex and sex effects are in the stats table)."
    )
    fig.text(0.1, 0.02, caption, ha="left", va="bottom", fontsize=14)

    # Reserve room at the bottom for the caption (tight_layout can't see fig.text).
    fig.subplots_adjust(bottom=0.2)

    out_path = out_dir / f"{genename}_L4.png"
    # bbox_inches="tight" keeps the caption and shared legend from being clipped.
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)

    status.ok(f"L4 composite saved -> {out_path}")
    return out_path






#@@@@@@@@@@@@@@@@@@ DEFINE PIPELINE AND CLASS @@@@@@@@@@@@@@@@@@#

@dataclass
class BanditResult:
    """Everything the L1->L4 run produced, so callers can inspect or re-plot
    any stage without rerunning the pipeline. Beats returning a bare tuple of
    a dozen values — attributes are self-documenting and order-independent."""
    fed_list: list
    metadata_df: object
    bm_md: object          # metrics + metadata (the table most re-analysis needs)
    bm_long: object        # melted, plot-ready
    rev_df: object
    l3_path: Path
    barplot_paths: list
    l4_path: Path


def run_bandit_l1_l4(l1_path, key_path, root_path, *, colors=None, dpi=300):
    """Run the full Bandit pipeline from an L1 zip to the L4 composite figure.

    Orchestration only — every step delegates to the existing public
    functions, so this stays a readable table of contents for the pipeline.

    Args:
        l1_path, key_path, root_path : the three inputs your notebook sets by hand.
        colors : optional {group: color} override. If None, falls back to
            define_aesthetics' defaults so the function runs headless (no widget
            interaction required).
        dpi : save resolution passed through to assemble_l4.
    """
    root_path = Path(root_path)

    # --- Ingest + key (was cell 4) ---
    fed_list, loaded_files, session_types = core.ingest_l1(l1_path)
    key_df, msg = core._read_key_from_upload(key_path)
    key_df2 = core.build_or_rematch_key_df(loaded_files, session_types, key_df,
                                           msg_hint=f"Key status: {msg}")

    # --- Individual plots + metrics -> L3 (cells 5-6) ---
    metadata_df = clean_key_filename_column(key_df2)
    _plot_file_core(fed_list, metadata_df, root_path)
    md = build_bandit_metakey(metadata_df)
    id_col, other_id = pick_match_method(md)
    bm = compute_bandit_metrics(fed_list, md, id_col)
    bm_md = attach_meta_bm(bm, md, id_col)
    l3_path = output_l3(bm_md, id_col, other_id, root_path)

    # --- Barplots (cell 7) ---
    mapped_df = build_group_selections(md)
    bm_plot = merge_group_selections(bm_md, mapped_df)
    bm_long = melt_bandit(bm_plot)
    # Honor a caller-supplied palette; otherwise use the aesthetics defaults.
    x_checks, x_colors, ordered_x = define_aesthetics(bm_long)
    if colors is not None:
        x_colors = colors
    barplot_paths = _run_plots(bm_long, x_checks, x_colors, ordered_x, root_path)

    # --- Peak accuracy + L4 composite (cells 8-9) ---
    basenames, xgroups = prep_pa_groups(mapped_df)
    rev_df = build_rev_df(fed_list, xgroups, basenames)
    plot_rev_learning(rev_df, x_colors, ordered_x, bm_md, root_path)
    l4_path = assemble_l4(bm_long, rev_df, x_colors, ordered_x, bm_md,
                          root_path, fed_list, metadata_df, dpi=dpi)

    return BanditResult(fed_list, metadata_df, bm_md, bm_long, rev_df,
                        l3_path, barplot_paths, l4_path)
