"""
Functions specificlly for bandit assay and plotting from a FED device
William B. Rubio
"""

# import dependancies
import os
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg  
import seaborn as sns
from pathlib import Path
import re
import tqdm
import ipywidgets as widgets
from dataclasses import dataclass
#import matplotlib as mpl


# stats
import pingouin as pg
from statsmodels.formula.api import ols
import statsmodels.api as sm

# import cousins
from fedverse.fedutils.fedlog import status 
from fedverse.extracted import fed3bandit_extracted, fed3_loading, fed3_fedframe
from fedverse import fedassets
from fedverse.fedcore import core



#@@@@@@@@@@@@@@@@@@ GLOBAL VARIABLES @@@@@@@@@@@@@@@@@@#
# List of bandit meta columns that we are interested in preserving and acting upon
# currenly passed in as a global in this script but scope may change
BANDIT_META_COLS = ["Genotype", "Gene", "Strain", "Sex", "Diet", "Treatment", "Condition","Pellets","Litter", "Sire_Geno", "Dam_Geno",]

# Define exclusions for group plotting
exclude_lower = {"match_status"} # everything else is allowed
ALPHA = 0.6


# Define hue order priority
HUE_PRIORITY = ["Female", "Male", "F", "M", "Day", "Night", "Light", "Dark", "ALL", "UNASSIGNED"]

# for peak accuracy
TRIALS = 11 



#@@@@@@@@@@@@@@@@@@ Bandit Plotting @@@@@@@@@@@@@@@@@@#
### ------ General Helper functions ------- ###
def clean_key_filename_column(key_df):
    """
    ensure that the filename column in the meta data key file is normalized
    Arguments:
        key_df; Dataframe
            Metadatafile dataframe generated by key creation step
    Returns:
        key_df; Dataframe
            Dataframe with normalized "filename" column
    """
    key_df = key_df.copy().reset_index(drop=True)
    if 'filename' in key_df.columns:
        key_df['filename'] = key_df['filename'].astype(str).map(os.path.basename)
    return key_df


def _coerce_numeric_col(df, col, clip_upper=None, na_map=None):
    """
    This function will attempt to coerce columns that are numeric to a numeric typing
    Called in:
        _plot_file_core
    Arguments:
        df; Dataframe
            A FED dataframe
        col - Specified column for attempted coercion to numeric type
    """
    if col not in df.columns:
        return
    s = df[col]
    if na_map:
        s = s.replace(na_map)
    s = pd.to_numeric(s, errors='coerce')
    if clip_upper is not None:
        s.loc[s > clip_upper] = np.nan
    df[col] = s


### ------- Main Plotting Function ------ ###
def _plot_file_core(fed_list, metadata_df, root_path, dpi=150):
    """
    This function will take in a file index to create a switch bandit plot for a particular file.

    Has a mode for creating displays for the L4, this mode requires the input of a dataframe supplied later.

    Aguments:
        fed_list; List
            List contating multiple FED Dataframes  
        metadata_df - the metadata file that has been stiched together in previous step of the workflow
        root_path; string or Path object
            the root path defined where the data lives
        dpi; int, default 150
            resolution for saved pictures
    """

    status.step("Beginning to plot bandit assays")


    # intitate a empty list to capture the results
    saved_paths  = []

    # Create the directory that will be writen to
    out_dir = Path(root_path, "indv_bandit_plots")
    out_dir.mkdir(parents=True, exist_ok=True)
    
    
    # iterate through all the df's within the list 
    for fed in fed_list:
        df = fed.copy()
        full_name = getattr(df, 'name', f"File_{fed}")
        file_basename = os.path.basename(str(full_name))

        # Preserve original index once
        if "Original_Timestamp" not in df.columns:
            df["Original_Timestamp"] = df.index

        # Attach metadata by filename (matching already done upstream)
        meta_row = None
        if 'filename' in metadata_df.columns:
            mr = metadata_df.loc[metadata_df['filename'] == file_basename]
            if not mr.empty:
                meta_row = mr.iloc[0]
        if meta_row is not None:
            for col in meta_row.index:
                if col == 'filename':
                    continue
                if col not in df.columns:
                    df[col] = meta_row[col]
                else:
                    if pd.isna(df[col]).all() and pd.notna(meta_row[col]):
                        df[col] = meta_row[col]

        # Time + cleanup
        try:
            df['timestamp'] = pd.to_datetime(df.index)
        except Exception:
            df['timestamp'] = np.arange(len(df))

        _coerce_numeric_col(df, 'Poke_Time', clip_upper=2)
        _coerce_numeric_col(df, 'Retrieval_Time', na_map={"Timed_out": np.nan})

        if len(df) == 0:
            status.warn(f"[!] Empty dataframe for {file_basename}. Skipping plot.")
            #return None, None
            continue
        
        true_left = fed3bandit_extracted.true_probs(df, offset=5)[0]
        mouse_left = fed3bandit_extracted.binned_paction(df, window=10)


        # Plot
        fig, ax = plt.subplots(figsize=(10, 3))
        ax.plot(np.arange(len(true_left)), true_left, color="black", linewidth=2, alpha=0.5)

        color = "dodgerblue"
        if 'Sex' in df.columns and pd.notna(df['Sex']).any():
            try:
                color = "red" if str(df['Sex'].iloc[0]).strip().lower().startswith("f") else "dodgerblue"
            except Exception:
                pass

        
        ax.plot(np.arange(len(mouse_left)), mouse_left, color=color, linewidth=3, alpha=0.7)

        ax.set_ylabel("P(Left)")
        ax.set_xlabel("Trial")
        ax.set_yticks([1, 0.5, 0])

        # Title = Mouse_ID (fallback to filename)
        title_text = str(meta_row['Mouse_ID']) if (meta_row is not None and 'Mouse_ID' in meta_row and pd.notna(meta_row['Mouse_ID'])) else file_basename
        ax.set_title(title_text)

        sns.despine()
        plt.tight_layout()
        #plt.show()

        # suggest a base filename for saving
        safe_title = "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in title_text)
        suggested = f"{safe_title}_pLeft"

        out_path = out_dir / suggested
        
        
        fig.savefig(out_path, dpi=dpi, bbox_inches="tight")

        # Close the current figure to save memory
        plt.close(fig)

        saved_paths.append(out_path)
        status.ok(f"saved {out_path.name}")


    status.ok(f"Plots saved to: {out_dir} ")

    # return final results
    return saved_paths 




#@@@@@@@@@@@@@@@@@@ Build Bandit L3 @@@@@@@@@@@@@@@@@@#

### ------ General Helper functions ------ ###


def _file_base_lower(pathlike):
    """
    Returns pathname to all lowercase
    
    Argument:
        pathlike; string
            string of path
    """
    return os.path.splitext(os.path.basename(str(pathlike)))[0].lower()





def _split_day_night(df, ts_col="MM:DD:YYYY hh:mm:ss"):
    """Day: 07:00–19:00; Night: otherwise."""
    ts = core._get_timestamp_series(df, ts_col=ts_col)
    valid = ts.notna()
    hrs = ts.dt.hour
    day_mask = valid & (hrs >= 7) & (hrs < 19)
    night_mask = valid & ~day_mask
    return df.loc[day_mask], df.loc[night_mask]


def compute_withinbout_lose_shift(c_df, max_gap_s=120):
    try:
        if "Event" not in c_df.columns or len(c_df) < 2:
            return np.nan
        events = c_df["Event"].to_numpy()
        times = core._get_timestamp_series(c_df).to_numpy()
        total = shifted = 0
        for i in range(len(events) - 1):
            curr_evt, next_evt = events[i], events[i + 1]
            if curr_evt not in ("Left", "Right"):
                continue
            dt_s = (times[i + 1] - times[i]) / np.timedelta64(1, "s")
            if np.isnan(dt_s) or dt_s > max_gap_s:
                continue
            if next_evt == "Pellet":
                continue
            if next_evt in ("Left", "Right"):
                total += 1
                if next_evt != curr_evt:
                    shifted += 1
        return (shifted / total) if total > 0 else np.nan
    except Exception:
        return np.nan
    

def compute_withinbout_win_stay(c_df, max_gap_s=120):
    try:
        if "Event" not in c_df.columns or len(c_df) < 3:
            return np.nan
        events = c_df["Event"].to_numpy()
        times = core._get_timestamp_series(c_df).to_numpy()
        pellet_idx = [i for i in range(1, len(events) - 1) if events[i] == "Pellet"]
        total = same = 0
        for i in pellet_idx:
            prev_event, next_event = events[i - 1], events[i + 1]
            dt_s = (times[i + 1] - times[i]) / np.timedelta64(1, "s")
            if not np.isnan(dt_s) and dt_s <= max_gap_s:
                if prev_event in ("Left", "Right") and next_event in ("Left", "Right"):
                    total += 1
                    if next_event == prev_event:
                        same += 1
        return (same / total) if total > 0 else np.nan
    except Exception:
        return np.nan
    

def compute_peak_accuracy(c_df):
    try:
        rev_avg = fed3bandit_extracted.reversal_peh(c_df, (-10, 10), True)
        if len(rev_avg) == 0:
            return np.nan
        return float(np.mean(rev_avg[:10])) if len(rev_avg) >= 10 else float(np.mean(rev_avg))
    except Exception:
        return np.nan



def compute_inactive_pokes(c_df):
    try:
        if not all(col in c_df.columns for col in ['Event', 'High_prob_poke']):
            return np.nan
        pokes = c_df[c_df['Event'].isin(['Left', 'Right'])].copy()
        if pokes.empty:
            return 0
        inactive = pokes[pokes['Event'] != pokes['High_prob_poke']]
        return len(inactive)
    except Exception:
        return np.nan


def compute_active_pokes(c_df):
    try:
        if not all(col in c_df.columns for col in ['Event', 'High_prob_poke']):
            return np.nan
        pokes = c_df[c_df['Event'].isin(['Left', 'Right'])].copy()
        if pokes.empty:
            return 0
        active = pokes[pokes['Event'] == pokes['High_prob_poke']]
        return len(active)
    except Exception:
        return np.nan
    







### --- crunch the numbers --- ###
def compute_bandit_metrics(fed_list, md, id_col="Mouse_ID"):
    """
    Computes the metrics from the bandit tasks
    Arguments:
        fed_list; List
            List contating multiple FED Dataframes
        md; Dataframe
            meta dataframe that contatins cropped bandit key created by build_bandit_metakey   
        id_col; String, default "Mouse_ID"
            String detailing what column will serve as the key column to link both metadata and metric files
    Returns:
        Banditmetrics; Dataframe
            Dataframe containing aggragate metrics from all mice for Bandit assays
    """

    status.step("Computing Bandit metrics")

    rows = []

    for idx in tqdm.tqdm(range(len(fed_list))):
        c_df = fed_list[idx]
        file_name = core._basename(getattr(c_df, "name", f"File_{idx}"))
        d, ev = core._prep_events(c_df)


        if ev is None or d.empty:
            pellets = left = right = lwp = 0
            rt_med = ipi_med = pt_med = np.nan
        else:
            pellets = int((d[ev] == "Pellet").sum())
            left    = int((d[ev] == "Left").sum())
            right   = int((d[ev] == "Right").sum())
            lwp     = int((c_df[ev] == "LeftWithPellet").sum()) if ev in c_df.columns else 0

        try:
            pre_acc_all = compute_peak_accuracy(c_df)
            clean_retrieval_time = pd.to_numeric(c_df.get("Retrieval_Time", pd.Series(dtype=float)), errors="coerce")
            clean_poke_time = pd.to_numeric(c_df.get("Poke_Time", pd.Series(dtype=float)), errors="coerce")
            clean_poke_time = clean_poke_time[clean_poke_time > 0]

            # Retrieve weight from Key_Df/metadata_df
            weight_val = np.nan
            if id_col in md.columns:
                # Attempt to find the metadata row for this specific session
                # First try to match by filename if possible, then by Mouse_ID if it exists
                meta_match = md.loc[md['filename'] == file_name]
                if meta_match.empty and 'Mouse_ID' in md.columns:
                    # If we can't match filename directly, try to infer Mouse_ID from the filename
                    known_ids = md['Mouse_ID'].dropna().unique().tolist()
                    base_lower = file_name.lower()
                    hits = [mid for mid in known_ids if str(mid).lower() in base_lower]
                    if hits:
                        best_hit = max(hits, key=len)
                        meta_match = md.loc[md['Mouse_ID'] == best_hit]

                if not meta_match.empty and 'Weight5_Friday' in meta_match.columns:
                    weight_val = pd.to_numeric(meta_match['Weight5_Friday'], errors='coerce').mean()

            row = {
                "filename": file_name,
                "PeakAccuracy": pre_acc_all,
                "Total_pellets": fed3bandit_extracted.count_pellets(c_df),
                "Total_pokes": fed3bandit_extracted.count_pokes(c_df),
                "PokesPerPellet": fed3bandit_extracted.pokes_per_pellet(c_df),
                "RetrievalTime": clean_retrieval_time.median() if not clean_retrieval_time.empty else np.nan,
                "PokeTime": clean_poke_time.median() if not clean_poke_time.empty else np.nan,
                "Win-stay": compute_withinbout_win_stay(c_df),
                "Lose-shift": compute_withinbout_lose_shift(c_df),
                "Daily_Pellets": core._estimate_daily_pellets(c_df),
                "Inactive_Pokes": compute_inactive_pokes(c_df),
                "Active_Pokes": compute_active_pokes(c_df),
                "Left Poke with Pellet": lwp,
                "Right_Poke": right,
                "Weight": weight_val
            }
        except Exception as e:
            status.fail(f"Failed to compute OVERALL metrics for {file_name} (idx {idx}): {e}")
            continue

        try:
            day_df, night_df = _split_day_night(c_df, ts_col="MM:DD:YYYY hh:mm:ss")
            row.update({
                "PeakAccuracy_Day": compute_peak_accuracy(day_df),
                "PeakAccuracy_Night": compute_peak_accuracy(night_df),
                "Win-stay_Day": compute_withinbout_win_stay(day_df),
                "Win-stay_Night": compute_withinbout_win_stay(night_df),
                "Lose-shift_Day": compute_withinbout_lose_shift(day_df),
                "Lose-shift_Night": compute_withinbout_lose_shift(night_df),
            })
        except Exception as e:
            status.fail(f"Failed to compute DAY/NIGHT metrics for {file_name} (idx {idx}): {e}")

        rows.append(row)

    Banditmetrics = pd.DataFrame(rows)
    if Banditmetrics.empty:
        display(HTML("<b style='color:#b00'>No files to analyze.</b>"))
        raise SystemExit
    
    status.ok("metrics computed:")
    status.preview(Banditmetrics, msg="Bandit metrics preview:")

    return Banditmetrics




#@@@@@@@@@@@@@@@@@@ Peak Accuracy @@@@@@@@@@@@@@@@@@#


### ------ General Helper functions ------ ###
def _is_empty(x):
    if x is None: return True
    try:
        return len(x) == 0
    except Exception:
        try:
            return np.size(x) == 0
        except Exception:
            return True


def _order_x_groups_local(groups):
    return sorted(groups, key=_hier_sort_key_local)

def _hier_sort_key_local(g):
    lv = _x_levels_local(g)
    wt_present = any(_is_wt_group_label(tok) for tok in lv) or _is_wt_group_label(g)
    wt_rank = 0 if wt_present else 1
    norm = []
    for tok in lv:
        is_blank = 1 if str(tok).strip().upper() in {"", "UNASSIGNED", "NONE", "NA", "N/A"} else 0
        norm.append((is_blank, str(tok).upper()))
    return (wt_rank,) + tuple(norm) + (str(g).upper(),)

def _is_wt_group_label(g):
    u = str(g).strip().upper()
    toks = [t for t in re.split(r'[^A-Z0-9]+', u) if t]
    return any(t in {"WT", "WILDTYPE", "CONTROL", "CTRL"} for t in toks)

def _x_levels_local(g):
    s = str(g)
    return [p.strip() for p in s.split("|")]

### ------ MAIN FUNCTIONS ------ ###
def prep_pa_groups(mapped_df):
    """
    build dictionary of filenames linked to groups

    Returns
        fname_to_xgroup; Dict
            dictionary mapping filenames to groupings
    """
    # filename -> XGroup map (match on basename)
    #grp = files_to_group_both.copy()
    grp = mapped_df.copy()
    src_col = "filename" if "filename" in grp.columns else ("File" if "File" in grp.columns else None)
    if src_col is None:
        raise RuntimeError("`files_to_group_both` must include 'filename' or 'File'.")
    basename = lambda s: os.path.basename(str(s))
    grp["__base__"] = grp[src_col].astype(str).map(basename)
    fname_to_xgroup = dict(grp[["__base__", "XGroup"]].dropna().values)

    return basename, fname_to_xgroup



def build_rev_df(feds, fname_to_xgroup,  basename):
    """
    Builds reversal learning dataframe

    Arguments

    Returns:
        Dataframe for reversal learning plotting
    """
    rows = []
    # --- Build rev_df ---
    for i, sess in enumerate(feds):
        base = basename(getattr(sess, "name", f"session_{i}"))
        xg = fname_to_xgroup.get(base, "UNASSIGNED")

        # compute peri-switch trials using your f3b helper
        try:
            peh = fed3bandit_extracted.reversal_peh(sess, (-TRIALS, TRIALS), return_avg=False)
        except Exception as e:
            print(f"[skip] {base}: reversal_peh failed: {e}")
            continue

        if _is_empty(peh):
            continue

        # peh is list/array of trial-length arrays; stack defensively
        for tr in list(peh):
            arr = np.asarray(tr).ravel()
            for t, v in enumerate(arr):
                rows.append({
                    "Timepoint": t - TRIALS + 1,    # center around 0
                    "Value": float(v) if np.isfinite(v) else np.nan,
                    "Display_Group": xg
                })

    rev_df = pd.DataFrame(rows)
    rev_df = rev_df[np.isfinite(rev_df["Value"])]
    rev_df = rev_df[rev_df["Timepoint"] != 0] # optional: drop center trial
    if rev_df.empty:
        raise RuntimeError("No peri-switch data produced.")
    
    return rev_df


def plot_rev_learning(rev_df, x_colors, ordered_x, bm_md, root_path):
    """
    Creates a reverse learning plot

    Arguments:
        bm_md; Dataframe
            used to pull out the Gene name to replace HET with for vizualization
    """

    status.step("creating reverse learning plot")

    out_dir = Path(root_path, "rev_learning")
    out_dir.mkdir(parents=True, exist_ok=True)

    saved_path = []

    # Pull out the gene name (needed by the relabel lines below).
    genename = bm_md["Gene"][0]

    # Work on COPIES — this function runs before assemble_l4 in the pipeline,
    # and mutating the shared rev_df / x_colors half-relabels them (HET -> gene)
    # before assemble_l4 does its own relabel. Copy so relabeling stays local.
    rev_df = rev_df.copy()
    x_colors = dict(x_colors)          # shallow copy: don't pop the caller's key

    ordered_x = [genename if label == "HET" else label for label in ordered_x]
    if "HET" in x_colors:
        x_colors[genename] = x_colors.pop("HET")
    rev_df["Display_Group"] = rev_df["Display_Group"].replace("HET", genename)
    
    # Create the directory that will be written to
    out_dir = Path(root_path, "rev_learning")
    out_dir.mkdir(parents=True, exist_ok=True)

    saved_path = []

    # Pull out the gene name
    genename = bm_md["Gene"][0]

    # Replace "HET" with the genename for vizualization purposes in ordered
    ordered_x = [genename if label == "HET" else label for label in ordered_x]

    # replace in x_colors
    if "HET" in x_colors:
        x_colors[genename] = x_colors.pop("HET")

    # replace HET in rev_df
    rev_df["Display_Group"] = rev_df["Display_Group"].replace("HET", genename)  

    

    _present = rev_df["Display_Group"].dropna().unique().tolist()

    # ORDER: if the first cell was run, follow its ordered_x; otherwise reproduce the same rule.
    if ordered_x:
        group_order = [g for g in ordered_x if g in _present] + [g for g in _present if g not in ordered_x]
    else:
        group_order = _order_x_groups_local(_present)


    # COLORS: pull from the first cell's x_colors widget map; fall back if unavailable.
    palette_map = None
    
    #if "x_colors" in globals() and isinstance(x_colors, dict) and len(x_colors) > 0:
    def _col(g):
        try:
            v = x_colors[g].value
            v = v.strip() if isinstance(v, str) else ""
            return v if v else "tab:blue"
        except Exception:
            return "tab:blue"
    
    palette_map = {g: _col(g) for g in group_order}

    plt.figure(figsize=(7, 5))
    # --- Plot (lines with SEM ribbons) ---
    group_order = sorted(rev_df["Display_Group"].dropna().unique().tolist()) 
    # ensure WT is first
    group_order = ["WT"] + sorted(g for g in group_order if g != "WT")


    ax = sns.lineplot(
        data=rev_df.sort_values(["Display_Group", "Timepoint"]),
        x="Timepoint",
        y="Value",
        hue="Display_Group",
        hue_order=group_order,
        palette=palette_map,
        estimator="mean",
        errorbar="se",
        n_boot=0,
        lw=2
    )

    # Switch marker and label
    ax.axvline(x=0, color="grey", linestyle = (0, (3, 5)), linewidth=1.25)
    
    ax.set_ylim(bottom=0, top=1)
    ymin, ymax = ax.get_ylim()
    
    # switch label
    ax.text(0.5, ymin + 0.95 * (ymax - ymin), "Switch", color="dimgrey",
            fontsize=16, ha="left", va="top", weight = "bold")

    ax.set_xlabel("Trials around switch", fontsize = 18)
    ax.set_ylabel("Peak Accuracy %", fontsize = 18)
    ax.set_title("")
    
    ax.legend(
        title="",
        frameon=False,
        loc="lower left",
        #bbox_to_anchor=(1.12, 0.5),
        borderaxespad=0.2
    )

    sns.despine()
    plt.tight_layout()

    # Embed TrueType fonts so text stays editable in Illustrator/Inkscape
    #mpl.rcParams['pdf.fonttype'] = 42
    #mpl.rcParams['ps.fonttype']  = 42



    fig = ax.get_figure()  # or plt.gcf() if you prefer



    #files.download(os.path.join(outdir, fname))
    #plt.show()

    safe_name = genename + "_rev_learning"
    out_path = out_dir / f"{safe_name}.png"

    # Save at print-friendly resolution; bbox_inches="tight" trims the
    # generous whitespace left by the 2-panel layout + rotated x-labels.
    fig.savefig(out_path, dpi=300, bbox_inches="tight")

    plt.close(fig)
    ### Add download botton instead of auto download ###
    # define path and file name
    #output_file = os.path.join(outdir, fname)

    saved_path.append(out_path)

    status.ok("Reverse learning plot created")
    
    #return the path that it is saved to
    return saved_path






#@@@@@@@@@@@@@@@@@@ Automate L4 Assembly @@@@@@@@@@@@@@@@@@#








def _rev_learning_core(rev_df, ax, palette_map, group_order):
    """
    Draw the reverse-learning line plot (accuracy around the switch) onto a
    caller-supplied Axes. Extracted so both the standalone plot_rev_learning and
    the composite assemble_l4 can share one drawing routine.

    Assumes rev_df["Display_Group"] is ALREADY relabeled (HET -> gene name) and
    that palette_map / group_order are keyed by those final labels.
    """
    sns.lineplot(
        data=rev_df.sort_values(["Display_Group", "Timepoint"]),
        x="Timepoint", y="Value",
        hue="Display_Group", hue_order=group_order,
        palette=palette_map,
        estimator="mean", errorbar="se", n_boot=0, lw=2, ax=ax,
    )

    # Vertical dashed marker at the reversal ("Switch") point.
    ax.axvline(x=0, color="grey", linestyle=(0, (3, 5)), linewidth=1.25)

    ax.set_ylim(bottom=0, top=1)
    ymin, ymax = ax.get_ylim()
    # "Switch" caption pinned just inside the top of the plot area.
    ax.text(0.5, ymin + 0.95 * (ymax - ymin), "Switch",
            color="dimgrey", fontsize=14, ha="left", va="top", weight="bold")

    ax.set_xlabel("Trials around switch", fontsize=14)
    ax.set_ylabel("Peak Accuracy %", fontsize=14)
    ax.set_title("")
    # Genotype legend for the two lines, lower-left inside the panel.
    ax.legend(title="", frameon=False, loc="lower left", borderaxespad=0.2)
    sns.despine(ax=ax)



def find_contrast_pair(df, pellet_tol=15, min_sessions=1, wt_label="WT", het_label="Het"):
    """
    Find one WT mouse and one Het mouse that are each REPRESENTATIVE of their own
    genotype — their PeakAccuracy sits close to their group's mean — while also
    earning SIMILAR total pellets and being backed by a meaningful number of
    sessions. This is the "typical animal from each group" pair you'd want to show
    as an example figure, rather than a cherry-picked extreme.

    Returns (best_pair_row, full_ranked_table).
    """

    # --- 1. Collapse sessions -> one representative row per mouse ---
    # Every filename is a single session, so we average within a mouse
    per_mouse = (
        df.groupby("Mouse_ID")
        .agg(
            Genotype=("Genotype", "first"),         # constant within a mouse
            PeakAccuracy=("PeakAccuracy", "mean"),
            Total_pellets=("Total_pellets", "mean"),
            n_sessions=("filename", "size"),
        )
        .reset_index()
    )

    # Fail loudly (with the actual labels present) rather than returning nonsense.
    def _split(pm):
        g = pm["Genotype"].str.upper()
        return pm[g == wt_label.upper()].copy(), pm[g == het_label.upper()].copy()

    # --- 2. Prefer well-sampled mice, but don't empty the table on single-session data ---
    # Apply the session floor; if it wipes out either genotype (e.g. every mouse has
    # just one session at this stage), relax it so the function still returns a pair.
    kept = per_mouse[per_mouse["n_sessions"] >= min_sessions]
    wt, het = _split(kept)
    if wt.empty or het.empty:
        print(f"[warn] min_sessions={min_sessions} left {len(wt)} WT / {len(het)} Het; "
              f"ignoring the session floor for this dataset.")
        wt, het = _split(per_mouse)

    # Split by genotype, normalizing case so "Het"/"HET"/"het" all match.
    if wt.empty or het.empty:
        raise ValueError(
            f"Need both genotypes. Found {len(wt)} WT and {len(het)} Het. "
            f"Genotype values present: {sorted(per_mouse['Genotype'].unique())}"
        )

    # --- 3. Group-mean accuracy = the target each representative mouse should sit near ---
    # Computed over the session-averaged, session-count-filtered mice so it matches the
    # population we're actually selecting from.
    wt_mean_acc = wt["PeakAccuracy"].mean()
    het_mean_acc = het["PeakAccuracy"].mean()

    # How far each mouse's accuracy is from its own group's mean (smaller = more typical).
    wt["acc_dist"] = (wt["PeakAccuracy"] - wt_mean_acc).abs()
    het["acc_dist"] = (het["PeakAccuracy"] - het_mean_acc).abs()

    # --- 4. Build every WT x Het candidate pair ---
    # Cross join is fine here: this is mice-by-mice, not sessions, so the table is small.
    pairs = wt.merge(het, how="cross", suffixes=("_WT", "_HET"))

    # --- 5. Score each pair ---
    # pellet_gap    -> want SMALL (similar reward earned).
    # acc_gap       -> reported for context (the group difference this pair illustrates).
    # rep_score     -> want SMALL: how far BOTH mice sit from their respective group means,
    #                  i.e. how representative the pair is of the two genotypes.
    pairs["pellet_gap"] = (pairs["Total_pellets_WT"] - pairs["Total_pellets_HET"]).abs()
    pairs["acc_gap"] = (pairs["PeakAccuracy_WT"] - pairs["PeakAccuracy_HET"]).abs()
    pairs["rep_score"] = pairs["acc_dist_WT"] + pairs["acc_dist_HET"]

    # Keep only pairs whose pellet totals are actually close.
    similar = pairs[pairs["pellet_gap"] <= pellet_tol].copy()

    # Edge case: tolerance too tight -> fall back to the closest-pellet pairs so the
    # function still returns a usable result instead of an empty frame.
    if similar.empty:
        print(f"[warn] No pairs within pellet_tol={pellet_tol}; showing closest-pellet pairs instead.")
        similar = pairs.nsmallest(20, "pellet_gap").copy()

    # Among pellet-matched pairs, the best example is the one where both mice are most
    # typical of their group (smallest combined distance to the group means).
    ranked = similar.sort_values("rep_score", ascending=True).reset_index(drop=True)

    # --- 6. Convenience: pull out the single best pair ---
    cols = [
        "Mouse_ID_WT", "PeakAccuracy_WT", "Total_pellets_WT", "n_sessions_WT", "acc_dist_WT",
        "Mouse_ID_HET", "PeakAccuracy_HET", "Total_pellets_HET", "n_sessions_HET", "acc_dist_HET",
        "pellet_gap", "acc_gap", "rep_score",
    ]
    return ranked.loc[0, cols], ranked[cols]





def _plot_pleft_core(df, ax, *, line_color="dodgerblue", behaviour_label=None,
                     show_xlabel=True):
    """
    Draw ONE mouse's choice trace onto a caller-supplied Axes: the true reward
    probability for the left port (grey, the "Rewarded Side") plus the mouse's
    binned P(Left) action (colored). Creates no figure and saves nothing — the
    caller owns the Axes. This is the composable core shared by
    _plot_file_core_display (loop + save) and any composite that needs the trace.

    Arguments:
        df : DataFrame
            A single FED session, already metadata-attached and numeric-coerced.
        ax : matplotlib Axes
            Target axes to draw into.
        line_color : str
            Color for the mouse's action line. For L4 this is the GENOTYPE color
            (WT blue / gene red), not the sex color.
        behaviour_label : str | None
            Optional right-margin label, e.g. "Wildtype behaviour".
        show_xlabel : bool
            Whether to draw the "Trial" x-label (off for the top of a stack).
    """

    # True underlying reward probability for the left port (the step function).
    true_left = fed3bandit_extracted.true_probs(df, offset=5)[0]

    # Mouse's actual choice behaviour, smoothed over a sliding window.
    mouse_left = fed3bandit_extracted.binned_paction(df, window=10)

    # Grey reference = where reward actually was; colored = what the mouse did.
    ax.plot(np.arange(len(true_left)), true_left, color="black", linewidth=2, alpha=0.5)
    ax.plot(np.arange(len(mouse_left)), mouse_left, color=line_color, linewidth=3, alpha=0.7)

  
    ax.set_ylabel("P(Left)")
    ax.set_yticks([0, 0.5, 1])
    #ax.set_yticks([0, 1])
    #ax.set_yticklabels(["Left", "Right"])

    # add side axis
    ax.text(-0.01, 1, "Right",  transform=ax.transAxes, va="top", ha="right")
    ax.text(-0.01, 0.12, "Left",  transform=ax.transAxes, va="top", ha="right")

    if behaviour_label:
        # Label sits just outside the right edge, colored to match the trace.
        ax.text(1.01, 0.5, behaviour_label, transform=ax.transAxes,
                va="center", ha="left", color=line_color, fontsize=12)

    sns.despine(ax=ax)


def _plot_file_core_display(fed_list, metadata_df, root_path, dpi=150,
                            select_ids=None, color_by="sex",
                            genotype_colors=None):
    """
    Plot per-file switch-bandit P(Left) traces and save them.

    L4 use: pass select_ids=[wt_id, het_id] (from find_contrast_pair) to render
    ONLY the two example mice, and color_by="genotype" so the traces match the
    rest of the figure (WT blue / gene red) instead of being colored by sex.

    Arguments:
        fed_list : list
            FED session DataFrames (each carries a .name filename attribute).
        metadata_df : DataFrame
            Stitched metadata; used to attach fields and map filename -> Mouse_ID.
        root_path : str | Path
            Output root; PNGs are written under <root_path>/indv_bandit_plots.
        dpi : int
            Save resolution.
        select_ids : list | set | None
            If given, only mice whose Mouse_ID is in this collection are plotted.
            None -> plot everything (original behaviour).
        color_by : {"sex", "genotype"}
            "sex"      -> red for female, else blue (original behaviour).
            "genotype" -> look up genotype_colors by the mouse's Genotype.
        genotype_colors : dict | None
            {Genotype -> color}, required when color_by="genotype". Keys are the
            RAW genotype labels present in the data (e.g. "WT", "HET").

    Returns:
        saved : dict
            {Mouse_ID (str) -> Path} for every trace saved, so callers can pick
            out specific mice (e.g. WT vs HET) by identity rather than order.
    """
    status.step("Beginning to plot bandit assays")

    out_dir = Path(root_path, "indv_bandit_plots")
    out_dir.mkdir(parents=True, exist_ok=True)

    # Normalize the selection to a set of strings once, for cheap membership tests.
    select_set = None if select_ids is None else {str(s) for s in select_ids}

    saved = {}  # Mouse_ID -> saved path

    for fed in fed_list:
        df = fed.copy()
        full_name = getattr(df, "name", f"File_{fed}")
        file_basename = os.path.basename(str(full_name))

        # Preserve original index once.
        if "Original_Timestamp" not in df.columns:
            df["Original_Timestamp"] = df.index

        # Attach metadata by filename (matching already done upstream).
        meta_row = None
        if "filename" in metadata_df.columns:
            mr = metadata_df.loc[metadata_df["filename"] == file_basename]
            if not mr.empty:
                meta_row = mr.iloc[0]
        if meta_row is not None:
            for col in meta_row.index:
                if col == "filename":
                    continue
                if col not in df.columns:
                    df[col] = meta_row[col]
                else:
                    if pd.isna(df[col]).all() and pd.notna(meta_row[col]):
                        df[col] = meta_row[col]

        # Resolve this file's Mouse_ID (fallback to the filename).
        mouse_id = (
            str(meta_row["Mouse_ID"])
            if (meta_row is not None and "Mouse_ID" in meta_row and pd.notna(meta_row["Mouse_ID"]))
            else file_basename
        )

        # --- Selection filter: skip mice we weren't asked to plot ---
        # Done BEFORE the expensive time/coerce/plot work so we don't waste it.
        if select_set is not None and mouse_id not in select_set:
            continue

        # Time + cleanup.
        try:
            df["timestamp"] = pd.to_datetime(df.index)
        except Exception:
            df["timestamp"] = np.arange(len(df))

        _coerce_numeric_col(df, "Poke_Time", clip_upper=2)
        _coerce_numeric_col(df, "Retrieval_Time", na_map={"Timed_out": np.nan})

        if len(df) == 0:
            status.warn(f"[!] Empty dataframe for {file_basename}. Skipping plot.")
            continue

        # --- Decide the trace color ---
        if color_by == "genotype" and genotype_colors:
            # Match the mouse's genotype (case-insensitively) to a supplied color.
            geno = str(df["Genotype"].iloc[0]).strip().upper() if "Genotype" in df.columns else ""
            # Build an upper-cased lookup so "Het"/"HET" both resolve.
            gc_upper = {str(k).upper(): v for k, v in genotype_colors.items()}
            color = gc_upper.get(geno, "dodgerblue")
        else:
            # Original behaviour: red for female, blue otherwise.
            color = "dodgerblue"
            if "Sex" in df.columns and pd.notna(df["Sex"]).any():
                try:
                    color = "red" if str(df["Sex"].iloc[0]).strip().lower().startswith("f") else "dodgerblue"
                except Exception:
                    pass

        # --- Draw via the shared core, then title + save ---
        fig, ax = plt.subplots(figsize=(10, 3))
        _plot_pleft_core(df, ax, line_color=color)
        ax.set_title(mouse_id)

        plt.tight_layout()

        safe_title = "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in mouse_id)
        out_path = out_dir / f"{safe_title}_pLeft.png"
        fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
        plt.close(fig)

        saved[mouse_id] = out_path
        status.ok(f"saved {out_path.name}")

    status.ok(f"Plots saved to: {out_dir}")
    return saved








def assemble_bandit_l4(long_df, rev_df, x_colors, ordered_x, bm_md, root_path,
                fed_list, metadata_df, *, bandittype = None, schematic_path=None, dpi=300):
    """
    Assemble the composite "L4" deliverable figure for one knockout model:

        A) device schematic (optional) + two example P(Left) traces
           (a WT and a gene mouse chosen for similar reward / different accuracy)
        B) reverse-learning line plot  +  Peak Accuracy bar
        C) Total pokes bar
        D) Win-stay bar
        E) Lose-shift bar

    plus a single shared Sex (Female/Male) legend and a caption. Every bar panel
    reports the genotype main effect from a two-way ANOVA, matching the caption.

    Orchestration only: the drawing lives in _plot_pleft_core, _rev_learning_core
    and _plot_metric_display so the layout logic here stays readable.

    Arguments:
        long_df : DataFrame
            Melted metrics (columns: variable / XGroup / HueGroup / value).
        rev_df : DataFrame
            Per-trial peak accuracy around the switch (Timepoint / Value /
            Display_Group).
        x_colors : dict
            Group -> ipywidgets color widget (plain strings also tolerated).
        ordered_x : list
            X-group order hint from the aesthetics step (WT is forced first).
        bm_md : DataFrame
            Per-session metadata; supplies the gene name AND feeds
            find_contrast_pair to choose the two example mice.
        root_path : str | Path
            Output root; the figure is written under <root_path>/L4.
        fed_list : list
            FED session DataFrames, used to draw the two example traces directly.
        metadata_df : DataFrame
            Stitched metadata, used to map Mouse_ID -> FED session for the traces.
        bandittype; String | None
            accepts "bandit100" & "bandit80" in order to properly create the schematics.
        schematic_path : str | Path | None
            Optional device/behaviour image for the top-left of panel A. If None,
            that corner is left blank for manual assembly.
        dpi : int
            Save resolution.

    Returns:
        out_path : Path
            Path to the saved composite PNG.
    """


    status.step("Assembling L4 composite figure")

    out_dir = Path(root_path, "L4")
    out_dir.mkdir(parents=True, exist_ok=True)

    # Gene name that replaces the generic "HET" label throughout the figure.
    genename = bm_md["Gene"][0]

    # --- Pick the two example mice: each representative of its genotype, similar reward ---
    best, ranked = find_contrast_pair(bm_md, pellet_tol=50)

    wt_id = str(best["Mouse_ID_WT"])
    het_id = str(best["Mouse_ID_HET"])
    status.ok(f"L4 example pair -> WT: {wt_id} | {genename}: {het_id} "
              f"(acc gap {best['acc_gap']:.3f}, pellet gap {best['pellet_gap']:.1f})")


    # --- Resolve colors to a plain {group: color} dict ONCE ---
    # x_colors may hold ipywidgets (with .value) or plain strings; tolerate both.
    def _resolve(g):
        c = x_colors.get(g, None)
        val = getattr(c, "value", c)                 
        val = val.strip() if isinstance(val, str) else ""
        return val or "tab:blue"
    color_map = {g: _resolve(g) for g in x_colors}


    long_df = long_df.copy()
    rev_df = rev_df.copy()

    # Preferred left-to-right order of zygosities after WT, and their pretty form.
    zygotic_order = ["HET", "HOM", "HEMI"]
    zyg_display   = {"HET": "Het", "HOM": "Hom", "HEMI": "Hemi"}

    present = long_df["XGroup"].dropna().unique().tolist()
    non_wt  = [g for g in present if str(g).upper() != "WT"]
    multi   = len(non_wt) > 1                      # drives the labeling convention

    if not multi:
        # Single mutant -> bare gene name shown on the bar itself.
        relabel = {g: genename for g in non_wt}
    else:
        # Multiple mutants -> zygosity on the bar; gene name goes on the x-axis.
        relabel = {g: zyg_display.get(str(g).upper(), str(g).title()) for g in non_wt}

    long_df["XGroup"] = long_df["XGroup"].replace(relabel)
    rev_df["Display_Group"] = rev_df["Display_Group"].replace(relabel)

    # --- Order: WT first, then mutants by zygotic_order (unknowns sort last) ---
    def _zygo_rank(orig_label):
        up = str(orig_label).upper()
        return zygotic_order.index(up) if up in zygotic_order else len(zygotic_order)

    non_wt_sorted = sorted(non_wt, key=_zygo_rank)
    group_order = ["WT"] + [relabel[g] for g in non_wt_sorted]

    # --- Resolve colors keyed to the FINAL display labels ---
    # x_colors keys are inconsistent upstream (raw "HOM"/"HEMI" but bare "FMR1"
    # for het), so for each final label we try several candidate source keys,
    # case-insensitively, before falling back.
    def _resolve_widget(entry):
        val = getattr(entry, "value", entry)          # widget -> .value, else itself
        val = val.strip() if isinstance(val, str) else ""
        return val or None

    xc_norm = {}                                      # UPPER(source key) -> color
    for k, v in x_colors.items():
        c = _resolve_widget(v)
        if c:
            xc_norm[str(k).upper()] = c

    # Recover each final label's ORIGINAL raw zygosity so we can try it as a key.
    final_to_orig = {new: old for old, new in relabel.items()}
    final_to_orig["WT"] = "WT"

    def _color_for(final_label):
        orig = final_to_orig.get(final_label, final_label)
        # try: raw zygosity ("HOM"), the bare gene ("FMR1", covers het), then the
        # display label itself, then a visible default.
        for cand in (orig, genename, final_label):
            hit = xc_norm.get(str(cand).upper())
            if hit:
                return hit
        return "tab:blue"

    color_map = {g: _color_for(g) for g in group_order}
    # One controlled Sex order shared by every bar panel so dot colors line up.
    hue_order = core._order_hue_groups(long_df["HueGroup"].dropna().unique().tolist())



    # ---------------- Figure + grid layout ----------------
    # Row 0: panel A.
    # Row 1: line plot (wide) + four equal-width bar plots.
    core.set_plot_style()   # one shared font family across every L4 figure
    fig = plt.figure(figsize=(16, 8))
    #create a grid space
    gs = fig.add_gridspec(nrows=2, ncols=1, height_ratios=[1.0, 1.0], hspace=0.45)

    # define the subgridspecs for the top and bottom rows
    gs_top = gs[0, :].subgridspec(2, 3, width_ratios=[1, 2, 0.3], hspace=0.25, wspace=0.08)
    gs_bot = gs[1, :].subgridspec(1, 5, width_ratios=[1.88, 1, 1, 1, 1], wspace=0.45)
    # bar column ratio should be
    # a total of 1/7 (0.14) + 0.45 wspace

    ##### Panel A  #####
    # schematic (left) + two stacked example traces (right)
    # Nested grid so the top row can hold both the image and the two traces.


    # Schematic spans both sub-rows on the left; blank if no image supplied.
    # find what bandit version
    bt = str(bandittype).strip().lower()
    bandit80_dict = {"bandit80", "80"}
    bandit100_dict = {"bandit100", "100"}
    
    if bt in bandit80_dict:
        schematic_path=fedassets.get("bandit80_schematic.jpg")
    elif bt in bandit100_dict:
        schematic_path=fedassets.get("bandit100_schematic.jpg")
    else:
        # fail loudly
        raise ValueError(
            f"Unrecognized bandittype {bandittype!r}; "
            f"expected one of {sorted(bandit80_dict | bandit100_dict)}."
        )

    # add the bandit schematic
    ax_schem = fig.add_subplot(gs_top[:, 0])
    ax_schem.axis("off")
    core._panel_label(ax_schem, "A)", dx=0.05, dy=0.75)

    if schematic_path is not None and Path(schematic_path).exists():
        ax_schem.imshow(mpimg.imread(str(schematic_path)))
    # add genename label at title
    ax_schem.set_title(genename, loc="left", fontsize=30, fontweight="bold")


    ### Switching plots ###
    # Two example traces, drawn directly onto their axes (no PNG round-trip).
    # (Mouse_ID, right-margin label, genotype color, show x-label on bottom only)
    het_raw = next((g for g in non_wt if str(g).upper() == "HET"), None)
    het_display = relabel.get(het_raw, genename)
    het_color = color_map.get(het_display, "tab:blue")

    # Label reads "<gene> behaviour" (bare gene), matching the figure.
    trace_specs = [
        (wt_id,  "Wildtype behaviour",    color_map["WT"], False),
        (het_id, f"{genename} behaviour", het_color,       True),
    ]




    for row, (mid, label, col, show_x) in enumerate(trace_specs):
        ax_tr = fig.add_subplot(gs_top[row, 1])
        fed = core._fed_for_mouse(fed_list, metadata_df, mid)
        
        if fed is None:
            # Missing session shouldn't kill the whole composite.
            status.warn(f"L4: no FED session found for Mouse_ID {mid}; blank trace.")
            ax_tr.axis("off")
            continue
        _plot_pleft_core(fed, ax_tr, line_color=col,
                         behaviour_label=label, show_xlabel=show_x)
        
        # turn off all axis
        ax_tr.axis("off")
        
        if row == 1:
            # add reward side text
            ax_tr.text(1.01, 1.05, "Rewarded Side", transform=ax_tr.transAxes,
                       ha="left", va="bottom", color="0.5", fontsize = 12)

            # Add arrow for both plots
            ax_tr.annotate("",
                    xy=(1.0, -0.2), xytext=(0.15, -0.2),
                    xycoords="axes fraction",
                    annotation_clip=False,  # don't clip content drawn above the axes
                    arrowprops=dict(arrowstyle="->", lw=5, color="0.6"))

            # Label for arrow independently
            ax_tr.text(0.07, -0.28, "3 days", transform=ax_tr.transAxes,
                       ha="left", va="bottom", color="0.5")



    ##### Panel B-left: reverse-learning line plot #####
    ax_line = fig.add_subplot(gs_bot[0, 0])
    core._panel_label(ax_line, "B)")          
    _rev_learning_core(rev_df, ax_line, 
                       palette_map = color_map, 
                       group_order = group_order)

    if multi:
        leg = ax_line.get_legend()
        if leg is not None:
            for txt in leg.get_texts():
                if txt.get_text().upper() != "WT":
                    txt.set_text(f"{genename} {txt.get_text()}")


    ##### Panels B-bar / C / D / E: metrics#####
    # (long_df variable name, y-axis label shown on the panel)
    metric_specs = [
        ("PeakAccuracy", "Peak Accuracy %"),
        ("Total_pokes",  "Total pokes"),
        ("Win-stay",     "Win-stay"),
        ("Lose-shift",   "Lose-shift"),
    ]

    # specify the panel letters for each bar plot metric
    bar_panel_letters = {2: "C)", 3: "D)", 4: "E)"}

    shared_handles = []
    for col, (metric, ylabel) in enumerate(metric_specs, start=1):
        ax_bar = fig.add_subplot(gs_bot[0, col])
        # assign bar plot panels
        if col in bar_panel_letters:
            core._panel_label(ax_bar, bar_panel_letters[col])
        sub = long_df[long_df["variable"] == metric]
        # Guard: a model missing a metric shouldn't crash the whole composite.
        if sub["value"].dropna().empty:
            status.warn(f"L4: no data for {metric}; leaving panel blank.")
            ax_bar.axis("off")
            continue
        handles = core._plot_metric_display(
            sub, metric, ax_bar, color_map,
            group_order=group_order, hue_order=hue_order, ylabel=ylabel,
            xlabel=(genename if multi else ""),
        )
        # Keep the first non-empty proxy set for the single shared legend.
        if handles and not shared_handles:
            shared_handles = handles

    # --- One shared Sex legend for the whole figure (top-right) ---
    if shared_handles:
        fig.legend(
            handles=shared_handles, title="Sex",
            loc="lower right", frameon=False,
            bbox_to_anchor=(0.125, 0.62),
        )

    

    # --- Caption block beneath the panels ---
    # Assembled line-by-line (each string ends with a space) so the joins never
    # run words together, with explicit \n where a visible line break is wanted.
    caption = (
        "A) FED3 device and example behaviour schematic. "
        "B) Line plot and bar graph of peak accuracy in the 10 trials around a switch.\n"
        "C, D, E) Bar graphs of mean total pokes, win-stay and lose-shift respectively.\n"
        "Win-stay: after a reward, did the mouse choose the same port again. "
        "Lose-shift: after no reward, did it choose the opposite port.\n"
        "Statistics: two-way ANOVA; the reported p-value is the genotype effect "
        "(genotype x sex and sex effects are in the stats table)."
    )
    fig.text(0.1, 0.02, caption, ha="left", va="bottom", fontsize=14)


    

    # Reserve room at the bottom for the caption (tight_layout can't see fig.text).
    fig.subplots_adjust(bottom=0.22)

    out_path = out_dir / f"{genename}_L4.svg"
    # bbox_inches="tight" keeps the caption and shared legend from being clipped.
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight", format = "svg")
    plt.close(fig)

    status.ok(f"L4 composite saved -> {out_path}")
    return out_path






#@@@@@@@@@@@@@@@@@@ DEFINE PIPELINE AND CLASS @@@@@@@@@@@@@@@@@@#

@dataclass
class BanditResult:
    """Everything the L1->L4 run produced, so callers can inspect or re-plot
    any stage without rerunning the pipeline. Beats returning a bare tuple of
    a dozen values — attributes are self-documenting and order-independent."""
    fed_list: list
    metadata_df: object
    bm_md: object          # essentailly the L3, bandit metrics and metadata
    bm_long: object        # melted version og bm_md
    rev_df: object
    l3_path: Path
    barplot_paths: list
    stats_df: object
    l4_path: Path




def run_bandit_l1_l4(l1_path, key_path, root_path, *, bandittype = None, colors=None, dpi=300):
    """Run the full Bandit pipeline from an L1 zip to the L4 composite figure.

    Orchestration only — every step delegates to the existing public
    functions, so this stays a readable table of contents for the pipeline.

    Args:
        l1_path, key_path, root_path : the three inputs your notebook sets by hand.
        bandittype; String | None
            accepts "bandit100" & "bandit80" in order to properly create the schematics.
        colors; optional {group: color} override. If None, falls back to
            define_aesthetics' defaults so the function runs headless (no widget
            interaction required).
        dpi; int 
            save resolution passed through to assemble_l4.

    """
    # =========================================================
    # Output directories
    # =========================================================

    l3_dir = root_path / "L3"
    l4_dir = root_path / "L4"
    graph_dir = root_path / "Working data and graphs"

    # Create them if they do not already exist
    l3_dir.mkdir(parents=True, exist_ok=True)
    l4_dir.mkdir(parents=True, exist_ok=True)
    graph_dir.mkdir(parents=True, exist_ok=True)

    # --- Ingest + key  ---
    fed_list, loaded_files, session_types = core.ingest_l1(l1_path)
    key_df, msg = core._read_key_from_upload(key_path)
    key_df2 = core.build_or_rematch_key_df(loaded_files, session_types, key_df,
                                           msg_hint=f"Key status: {msg}")

    metadata_df = clean_key_filename_column(key_df2)

    # Individual graphs go into Working data and graphs
    _plot_file_core(fed_list, metadata_df, graph_dir,)
    meta_cols, md = core.build_metakey(metadata_df, assay="bandit",)
    id_col, other_id = core.pick_match_method(md)
    bm = compute_bandit_metrics(fed_list, md, id_col,)
    bm_md = core.attach_meta(bm, md, id_col,)
    # L3 file goes into the L3 folder
    l3_path = core.output_l3(bm_md,id_col,other_id, meta_cols, l3_dir, assay="bandit",)


    # --- Barplots ---
    mapped_df = core.build_group_selections(md)
    bm_plot = core.merge_group_selections(bm_md, mapped_df)
    bm_long = core.melt_metric(bm_plot, assay="bandit")

    # Honor a caller-supplied palette; otherwise use the aesthetics defaults.
    x_checks, x_colors, ordered_x = core.define_aesthetics(bm_long)
    if colors is not None:
        x_colors = colors
    barplot_paths = core._run_plots(bm_long, x_checks, x_colors, ordered_x, graph_dir,)

    # --- Peak accuracy + L4 composite + stats table ---
    basenames, xgroups = prep_pa_groups(mapped_df)
    rev_df = build_rev_df(fed_list, xgroups, basenames)
    #plot_rev_learning(rev_df, x_colors, ordered_x, bm_md, graph_dir,)

    # --- stats table --- #
    stats_df = core.build_stats_table(bm_long, ordered_x, l4_dir, assay="bandit")

    # --- L4 --- #
    l4_path = assemble_bandit_l4(bm_long, rev_df, x_colors, ordered_x, bm_md,
                          l4_dir, fed_list, metadata_df, bandittype = bandittype, dpi=dpi)

    return BanditResult(fed_list, metadata_df, bm_md, bm_long, rev_df,
                        l3_path, barplot_paths, stats_df, l4_path)
