"""
Core function shared amongst all 3 analysis types: PR1, FR1, and Bandit.
Code is based from code generated by Chantelle Murrell and Sebastian Alves 
6-30-2026
William B. Rubio
"""

import io
import os
import zipfile
import tempfile
from pathlib import Path
import pandas as pd
import numpy as np

# call cousins
from fedlib.extracted import fed3_loading
from fedlib.fedutils.fedlog import status 



# ================================================================= Uploading Files ================================================================= #
# functions need for reading in cleaned FED files

def extract_session_type(csv_path, fallback="Unknown"):
    """
    Read 'Session_Type ' or variants; return first non-empty value.
    Called by: 
        ingest_l1
    Argument:
        csv_path - has to be a pathway to a csv within a zipped file
    """
    try:
        # Read in the individual file
        df = pd.read_csv(csv_path, sep=None, engine='python', dtype=str)
        # isolate columns names 
        df.columns = [c.strip() for c in df.columns]
        lower = {c.casefold(): c for c in df.columns}
        # Loop through column names to locate the session column
        for cand in ["session_type", "session type", "sessiontype", "session"]:
            if cand in lower:
                col = lower[cand]
                vals = df[col].dropna().astype(str).str.strip()
                vals = vals[vals.ne("")]
                if not vals.empty:
                    # Return the first value of the session-like column
                    return vals.iloc[0]
    except Exception:
        pass
    return fallback


def ingest_l1(l1_path):
    """
    Define a function that will ingest data derived from a zipped folder contating fed data
    Argument: 
        l1_path - is required to be a path to a zipped folder that contains processed data from a fed. 
    """
    status.step("Beginning Ingest") 
    # check if the path is a zip file else pass error
    if not zipfile.is_zipfile(l1_path):
        raise ValueError(f"RAW_PATH must be a zip archive: {l1_path}")

    # define lists to populate
    fed_list, loaded_files, session_types = [], [], []

    # Create a empty list to catch error messages
    errors = []
    
    # pathify the name and create dictionary
    l1_path = Path(l1_path)
    uploaded = {l1_path.name: l1_path.read_bytes()}

    # iteracte through the dictionary
    for name, data in uploaded.items():
        ### for ZIP files
        if name.lower().endswith(".zip"):
            with zipfile.ZipFile(io.BytesIO(data)) as zf:
                for zi in zf.infolist():
                    if not zi.filename.lower().endswith(".csv"):
                        continue
                    file_data = zf.read(zi)
                    # if the file is short remove the file
                    if len(file_data) <= 1024:
                        continue
                    with tempfile.NamedTemporaryFile(mode="w+b", suffix=".csv", delete=False) as tmp:
                        tmp.write(file_data); tmp_path = tmp.name
                    # attempt to populate lists
                    try:
                        session_type = extract_session_type(tmp_path)
                        df = fed3_loading.load(tmp_path)
                        df.name = os.path.basename(zi.filename)
                        df.attrs = {"Session_type": session_type}
                        fed_list.append(df)
                        loaded_files.append(os.path.basename(zi.filename))
                        session_types.append(session_type)
                    except Exception as e:
                        errors.append(f"Error loading {zi.filename}: {e}")
                    finally:
                        os.remove(tmp_path)
        ### if a csv file happens to be uploaded
        elif name.lower().endswith(".csv"):
            if len(data) <= 1024:
                continue
            with tempfile.NamedTemporaryFile(mode="w+b", suffix=".csv", delete=False) as tmp:
                tmp.write(data); tmp_path = tmp.name
            try:
                session_type = extract_session_type(tmp_path)
                df = fed3_loading.load(tmp_path)
                df.name = os.path.basename(name)
                df.attrs = {"Session_type": session_type}
                fed_list.append(df)
                loaded_files.append(os.path.basename(name))
                session_types.append(session_type)
            except Exception as e:
                errors.append(f"Error loading {name}: {e}")
            finally:
                os.remove(tmp_path)

    # if any errors occoured return the errors
    if errors:
        print()
        for err in errors:
            status.warn(err)
    
    status.ok(f"Ingest Complete - Loaded {len(loaded_files)} files. Session types captured for all.")

    # return three lists
    return fed_list, loaded_files, session_types


# ================================================================= Key Creation ================================================================= #
# functions needed for creating key columns


def _make_base_key_df(loaded_files, session_types):
    """
    Use two lists from ingest to make a basic df to house meta data
    Called by:
        build_or_rematch_key_df
    Arguments:
        loaded_files - list output from ingest_l1
        session_types - list output from ingest_l1
    """
    return pd.DataFrame({"filename": loaded_files, "Session_type": session_types})

def _file_base(s):
    """
    Called by: 
        build_or_rematch_key_df
    """
    return os.path.splitext(os.path.basename(str(s)))[0].strip()

def _norm_base_lower(s):
    """
    generic function to lowercase strings passed into it
    Called by:
        build_or_rematch_key_df
    """
    return _file_base(s).lower()


def _scan_key_columns(df):
    """
    Accepts keys that have either Mouse_ID or a filename column (filename/File).
    Called by:
        _read_key_from_upload
        build_or_rematch_key_df
    Returns dict:
      {
        'has_mouse': bool,
        'has_filename': bool,
        'filename_col': 'filename'|'File'|None,
        'msg': str
      }
    """
    info = {'has_mouse': False, 'has_filename': False, 'filename_col': None, 'msg': ''}
    try:
        cols = [str(c).strip() for c in df.columns]
        has_mouse = 'Mouse_ID' in cols
        fname_col = 'filename' if 'filename' in cols else ('File' if 'File' in cols else None)
        info.update({
            'has_mouse': has_mouse,
            'has_filename': fname_col is not None,
            'filename_col': fname_col
        })
        if has_mouse:
            info['msg'] = "'Mouse_ID' found."
        elif fname_col:
            info['msg'] = f"'{fname_col}' found; will match on filename."
        else:
            info['msg'] = "Neither 'Mouse_ID' nor 'filename'/'File' found in provided key."
    except Exception as e:
        info['msg'] = f"Error while checking key: {e}"
    return info

def _match_mouse_id_to_filenames(filenames, key_df):
    """
    Called by:
        build_or_rematch_key_df
    Returns:
        DataFrame: filename, Mouse_ID, match_status based on Mouse_ID substring in filename.
    """
    base_names_lower = [_norm_base_lower(f) for f in filenames]
    mouse_ids = (
        key_df['Mouse_ID']
        .dropna().astype(str).map(str.strip)
        .replace({'': np.nan}).dropna().unique().tolist()
    )
    rows = []
    for fname, base in zip(filenames, base_names_lower):
        hits = [mid for mid in mouse_ids if str(mid).lower() in base]
        if len(hits) == 1:
            rows.append({"filename": fname, "Mouse_ID": hits[0], "match_status": "Matched (Mouse_ID in filename)"})
        elif len(hits) > 1:
            longest = max(len(str(h)) for h in hits)
            best = [h for h in hits if len(str(h)) == longest]
            if len(best) == 1:
                rows.append({"filename": fname, "Mouse_ID": best[0], "match_status": "Matched (longest Mouse_ID token)"})
            else:
                rows.append({"filename": fname, "Mouse_ID": None, "match_status": f"Ambiguous Mouse_ID: {hits}"})
        else:
            rows.append({"filename": fname, "Mouse_ID": None, "match_status": "Mouse_ID not found in filename"})
    return pd.DataFrame(rows)

def _collapse_key_suffixes(df, keep_filename_from_base=True):
    """
    Remove duplicate columns created by merge suffixes.
    - If both 'col' and 'col_key' exist, keep the key version (rename col_key -> col, drop base col).
    - Special-case: if keep_filename_from_base and base == 'filename',
      drop 'filename_key' and keep the base 'filename'.

    Called by:
        build_or_rematch_key_df
    """
    cols = list(df.columns)
    rename_map = {}
    drop_cols = []

    for col in cols:
        if col.endswith('_key'):
            base = col[:-4]
            if keep_filename_from_base and base == 'filename':
                # keep the 'filename' from the bare-bones (actual loaded_files)
                drop_cols.append(col)
            elif base in df.columns:
                # key version wins: drop base col, rename *_key -> base
                drop_cols.append(base)
                rename_map[col] = base
            else:
                # no base column; just strip "_key"
                rename_map[col] = base

    df = df.drop(columns=drop_cols, errors='ignore').rename(columns=rename_map)
    return df
    
def _read_key_from_upload(key_path):
    """
    Reads CSV/XLSX bytes from Colab upload.
    Returns: 
        a Dataframe or None, returns a message.
    """
    status.step("Reading in key file")
    # Read in the from the path provided
    name = key_path.name
    content_bytes = key_path.read_bytes()
    
    ext = name.lower().rsplit('.', 1)[-1] if '.' in name else ''
    try:
        bio = io.BytesIO(content_bytes)
        if ext == 'xlsx':
            xls = pd.ExcelFile(bio, engine='openpyxl')
            frames = [pd.read_excel(xls, sheet_name=s) for s in xls.sheet_names]
            key_df = pd.concat(frames, ignore_index=True, sort=False)
        elif ext == 'csv':
            key_df = pd.read_csv(bio, sep=None, engine='python')
        else:
            return None, f"Unsupported key type .{ext}"

        key_df = key_df.copy()
        key_df.columns = [str(c).strip() for c in key_df.columns]
        scan = _scan_key_columns(key_df)
        if not (scan['has_mouse'] or scan['has_filename']):
            return None, scan['msg']

        # Normalize types/columns we might use later
        if scan['has_mouse']:
            globals()['KEY_MATCH_MODE'] = 'mouse_id'
            key_df['Mouse_ID'] = key_df['Mouse_ID'].astype(str).str.strip()

        if scan['has_filename']:
            globals()['KEY_MATCH_MODE'] = 'filename'
            fcol = scan['filename_col']
            key_df[fcol] = key_df[fcol].astype(str).str.strip()
            key_df['_key_file_base_lower'] = key_df[fcol].map(_norm_base_lower)
        else:
            globals()['KEY_MATCH_MODE'] = None

        # REMOVED - Persist a deterministic copy on disk for reproducibility
        #fixed_path = f"_uploaded_key.{ext}"
        #with open(fixed_path, "wb") as f:
        #    f.write(content_bytes)
        #globals()['uploaded_key_path'] = fixed_path

        status.ok("Done - Key loaded")
        return key_df, f"Key loaded from upload ({name}). {scan['msg']}"
    except Exception as e:
        return None, f"Error reading uploaded key: {e}"


def build_or_rematch_key_df(loaded_files, session_types, key_df = None, msg_hint = ""):
    """
    If key_df provided and valid:
      - If a filename column exists (filename/File), always use filename-based merge.
        - If Mouse_ID is also present, it is preserved from the key file.
      - Else, if only Mouse_ID exists, use substring-based Mouse_ID matching.
    Else: keep bare-bones.

    When a key is used, any duplicate column names between the bare-bones
    and the key are resolved so that the key's values win (except 'filename').
    """
    #global Key_Df
    status.step("Building key dataframe") 
    files_df = _make_base_key_df(loaded_files, session_types)#.copy()
    files_df['_file_base_lower'] = files_df['filename'].map(_norm_base_lower)

    # In pipeline should never happen as Red key from download is always called before to make a key
    if key_df is None:
        # Pure bare-bones Key_Df
        Key_Df = files_df.drop(columns=['_file_base_lower']).copy()
        Key_Df["match_status"] = "No key"
        # REMOVED - widget based interactable
        #with status_box:
        #clear_output(wait=True)
        status.sub("Key status: No key provided; showing bare-bones Key_Df.")
        return

    # Identify key capabilities
    scan = _scan_key_columns(key_df)
    kd = key_df.copy()

    # Helper: make a unique version of the key for whichever join we use
    def _dedup(df, subset_cols):
        dup_counts = df[subset_cols].astype(str).agg('|'.join, axis=1).value_counts()
        n_dups = int((dup_counts > 1).sum())
        if n_dups:
            # REMOVED - widget based interactable
            #with status_box:
            #clear_output(wait=True)
            status.sub(f"Note: {n_dups} duplicate key(s) on {subset_cols}; taking the first occurrence.")
        return df.drop_duplicates(subset=subset_cols, keep="first")

    # ---------------------------
    # 1) Prefer filename-based route whenever filename column exists
    #    (whether or not Mouse_ID is present)
    # ---------------------------
    if scan['has_filename']:
        fcol = scan['filename_col']

        # Normalize filename column in key
        kd[fcol] = kd[fcol].astype(str).str.strip()
        kd['_key_file_base_lower'] = kd[fcol].map(_norm_base_lower)

        # One row per normalized filename in the key
        key_unique = _dedup(kd, ['_key_file_base_lower'])

        # Merge by normalized basename (case-insensitive, extension-stripped)
        Key_Df = (
            files_df
            .merge(
                key_unique,
                left_on="_file_base_lower",
                right_on="_key_file_base_lower",
                how="left",
                suffixes=("", "_key")
            )
            .drop(columns=['_file_base_lower', '_key_file_base_lower'])
        )

        # Clean up duplicate columns so key overwrites bare-bones where appropriate
        Key_Df = _collapse_key_suffixes(Key_Df, keep_filename_from_base=True)

        # match_status for filename-based matching
        Key_Df["match_status"] = np.where(
            Key_Df[fcol].notna(),
            "Matched (filename)",
            "Filename not found in key"
        )

    # ---------------------------
    # 2) If no filename column but Mouse_ID exists, use substring route
    # ---------------------------
    elif scan['has_mouse']:
        # Mouse_ID route (fallback when no filename column exists)
        kd['Mouse_ID'] = kd['Mouse_ID'].astype(str).str.strip()
        key_unique = _dedup(kd, ['Mouse_ID'])

        matched = _match_mouse_id_to_filenames(
            files_df['filename'].tolist(),
            key_unique
        )[["filename", "Mouse_ID", "match_status"]]

        Key_Df = (
            files_df
            .merge(matched, on="filename", how="left")
            .merge(key_unique, on="Mouse_ID", how="left", suffixes=("", "_key"))
            .drop(columns=['_file_base_lower'])
        )

        # Clean up duplicate columns (e.g., Mouse_ID vs Mouse_ID_key)
        Key_Df = _collapse_key_suffixes(Key_Df, keep_filename_from_base=True)

    # ---------------------------
    # 3) Neither filename nor Mouse_ID in key
    # ---------------------------
    else:
        # Neither route available (shouldn't happen due to earlier check)
        Key_Df = files_df.drop(columns=['_file_base_lower']).copy()
        Key_Df["match_status"] = "Key missing Mouse_ID and filename columns"
    
    # REMOVED - widget based interactable
    #with status_box:
    #clear_output(wait=True)
    
    if msg_hint:
        status.ok(msg_hint)
    status.ok(f"Merged key columns into Key_Df ({len(Key_Df)} rows, {len(Key_Df.columns)} cols).")
    return Key_Df