"""
Functions specificlly for bandit assay and plotting from a FED device
William B. Rubio
"""


import os
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# import cousin
from fedlib.fedutils.fedlog import status 


# ================================================================= Bandit Plotting ================================================================= #

def clean_key_filename_column(key_df):
    """
    ensure that the filename column in the meta data key file is normalized
    Arguments:
        Metadatafile dataframe generated by key creation step
    Returns:
        Dataframe with normalized "filename" column
    """
    key_df = key_df.copy().reset_index(drop=True)
    if 'filename' in key_df.columns:
        key_df['filename'] = key_df['filename'].astype(str).map(os.path.basename)
    return key_df


def _coerce_numeric_col(df, col, clip_upper=None, na_map=None):
    """
    This function will attempt to coerce columns that are numeric to a numeric typing
    Called in:
        _plot_file_core
    Arguments:
        df - teh 
    """
    if col not in df.columns:
        return
    s = df[col]
    if na_map:
        s = s.replace(na_map)
    s = pd.to_numeric(s, errors='coerce')
    if clip_upper is not None:
        s.loc[s > clip_upper] = np.nan
    df[col] = s